/*
###############################################################
#  Generated by:      Cadence Innovus 16.12-s051_1
#  OS:                Linux x86_64(Host ID ecegrid-thin7.ecn.purdue.edu)
#  Generated on:      Thu Apr 16 20:43:18 2020
#  Design:            closed_loop_current_controller
#  Command:           saveNetlist /home/sparclab/a/ghosh69/march_20_tapeout/current_source_controller/logs/closed_loop_current_controller.gate.v -excludepowerground -excludeLeafCell
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : L-2016.03-SP2
// Date      : Thu Apr 16 19:08:47 2020
/////////////////////////////////////////////////////////////
module closed_loop_current_controller (
	OSC_OUT, 
	RST_N, 
	CLK, 
	LOOP_BYPASS, 
	CURRENT_SOURCE_ENABLE, 
	TOTAL_COUNT, 
	LOWER_VOLTAGE_BOUND, 
	UPPER_VOLTAGE_BOUND, 
	VDD, 
	VSS);
   input OSC_OUT;
   input RST_N;
   input CLK;
   input LOOP_BYPASS;
   output [31:0] CURRENT_SOURCE_ENABLE;
   input [7:0] TOTAL_COUNT;
   input [7:0] LOWER_VOLTAGE_BOUND;
   input [7:0] UPPER_VOLTAGE_BOUND;
   inout VDD;
   inout VSS;

   // Internal wires
   wire FE_ECON2_RST_N;
   wire FE_ECON1_RST_N;
   wire FE_ECON0_RST_N;
   wire FE_RN_2_0;
   wire FE_RN_1_0;
   wire FE_RN_0_0;
   wire OUT_CLK;
   wire COUNT_DONE;
   wire \u_osc_counter/n1 ;
   wire \u_osc_counter/n2 ;
   wire \u_osc_counter/N11 ;
   wire \u_osc_counter/N10 ;
   wire \u_osc_counter/N9 ;
   wire \u_osc_counter/N8 ;
   wire \u_osc_counter/N7 ;
   wire \u_osc_counter/N6 ;
   wire \u_osc_counter/N5 ;
   wire \u_osc_counter/N4 ;
   wire \u_fd/div_4 ;
   wire \u_fd/div_2 ;
   wire \u_fd/ff1/n1 ;
   wire \u_fd/ff2/n1 ;
   wire \u_fd/ff3/n1 ;
   wire \u_loop_top/u_counter/n1 ;
   wire \u_loop_top/u_counter/n14 ;
   wire \u_loop_top/u_counter/n13 ;
   wire \u_loop_top/u_counter/n12 ;
   wire \u_loop_top/u_counter/n11 ;
   wire \u_loop_top/u_counter/n10 ;
   wire \u_loop_top/u_counter/n9 ;
   wire \u_loop_top/u_counter/n8 ;
   wire \u_loop_top/u_counter/n7 ;
   wire \u_loop_top/u_counter/n6 ;
   wire \u_loop_top/u_counter/n5 ;
   wire \u_loop_top/u_counter/N19 ;
   wire \u_loop_top/u_counter/N18 ;
   wire \u_loop_top/u_counter/N17 ;
   wire \u_loop_top/u_counter/N16 ;
   wire \u_loop_top/u_counter/N15 ;
   wire \u_loop_top/u_counter/N14 ;
   wire \u_loop_top/u_counter/N13 ;
   wire \u_loop_top/u_counter/N12 ;
   wire \u_loop_top/u_counter/N11 ;
   wire \u_loop_top/u_counter/N10 ;
   wire \u_loop_top/u_counter/N9 ;
   wire \u_loop_top/u_counter/N8 ;
   wire \u_loop_top/u_counter/N7 ;
   wire \u_loop_top/u_counter/N6 ;
   wire \u_loop_top/u_counter/N5 ;
   wire \u_loop_top/u_counter/N4 ;
   wire \u_loop_top/u_counter/N2 ;
   wire \u_loop_top/u_counter/count[0] ;
   wire \u_loop_top/u_counter/count[1] ;
   wire \u_loop_top/u_counter/count[2] ;
   wire \u_loop_top/u_counter/count[3] ;
   wire \u_loop_top/u_counter/count[4] ;
   wire \u_loop_top/u_counter/count[5] ;
   wire \u_loop_top/u_counter/count[6] ;
   wire \u_loop_top/u_counter/count[7] ;
   wire \u_loop_top/u_counter/add_22/n3 ;
   wire \u_loop_top/u_counter/add_22/n2 ;
   wire \u_loop_top/u_counter/add_22/n1 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n147 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n146 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n145 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n144 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n143 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n142 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n141 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n140 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n139 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n138 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n137 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n136 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n135 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n134 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n133 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n132 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n131 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n130 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n129 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n128 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n127 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n126 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n125 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n124 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n123 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n122 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n121 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n120 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n119 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n118 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n117 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n116 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n115 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n114 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n113 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n112 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n111 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n110 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n109 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n108 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n107 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n106 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n105 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n104 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n103 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n102 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n101 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n100 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n96 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n95 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n94 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n93 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n92 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n90 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n89 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n88 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n87 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n86 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n85 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n84 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n82 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n81 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n80 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n79 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n78 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n77 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n76 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n75 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n74 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n73 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n72 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n71 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n70 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n69 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n68 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n67 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n66 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n64 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n61 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n59 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n58 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n57 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n56 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n55 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n54 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n53 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n51 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n50 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n49 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n32 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n31 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n29 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n28 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n27 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n24 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n23 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n21 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n20 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n18 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n17 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n16 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n15 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n14 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n13 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n12 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n11 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n10 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n9 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n8 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n7 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n6 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n5 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n4 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n3 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n2 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n1 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n48 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n47 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n46 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n45 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n44 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n43 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n42 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n41 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n40 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n39 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n38 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n37 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n36 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n35 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n34 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n33 ;
   wire [7:0] COUNTER;
   wire [7:0] \u_osc_counter/internal_counter ;
   wire [7:2] \u_osc_counter/add_26/carry ;
   wire [7:2] \u_loop_top/u_counter/add_22/carry ;
   wire [31:0] \u_loop_top/u_up_down_counter_32b_avg/out_count_next ;

   CKBD4 FE_ECOC2_RST_N (.I(RST_N),
	.Z(FE_ECON2_RST_N));
   CKBD4 FE_ECOC1_RST_N (.I(FE_ECON2_RST_N),
	.Z(FE_ECON1_RST_N));
   CKBD4 FE_ECOC0_RST_N (.I(FE_ECON1_RST_N),
	.Z(FE_ECON0_RST_N));
   IOA22D0 FE_RC_9_0 (.A1(\u_loop_top/u_up_down_counter_32b_avg/n67 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n66 ),
	.B1(UPPER_VOLTAGE_BOUND[7]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n64 ),
	.ZN(FE_RN_1_0));
   INR2XD1 FE_RC_8_0 (.A1(\u_loop_top/u_up_down_counter_32b_avg/n103 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n101 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n27 ));
   CKND0 FE_RC_6_0 (.I(\u_loop_top/u_up_down_counter_32b_avg/n100 ),
	.ZN(FE_RN_2_0));
   OA31D0 FE_RC_5_0 (.A1(FE_RN_2_0),
	.A2(FE_RN_1_0),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n102 ),
	.B(COUNT_DONE),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n101 ));
   FCICIND1 FE_RC_4_0 (.A(COUNTER[6]),
	.B(\u_loop_top/u_up_down_counter_32b_avg/n61 ),
	.CIN(UPPER_VOLTAGE_BOUND[6]),
	.CO(\u_loop_top/u_up_down_counter_32b_avg/n67 ));
   IOA21D0 FE_RC_3_0 (.A1(UPPER_VOLTAGE_BOUND[4]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n75 ),
	.B(\u_loop_top/u_up_down_counter_32b_avg/n66 ),
	.ZN(FE_RN_0_0));
   AOI21D0 FE_RC_2_0 (.A1(\u_loop_top/u_up_down_counter_32b_avg/n54 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n53 ),
	.B(FE_RN_0_0),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n56 ));
   IND3D0 FE_RC_1_0 (.A1(COUNTER[6]),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n92 ),
	.B2(LOWER_VOLTAGE_BOUND[6]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n94 ));
   IND2D0 FE_RC_0_0 (.A1(LOWER_VOLTAGE_BOUND[3]),
	.B1(COUNTER[3]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n89 ));
   IND2D0 \u_osc_counter/U4  (.A1(COUNT_DONE),
	.B1(RST_N),
	.ZN(\u_osc_counter/n2 ));
   CKND1 \u_osc_counter/U3  (.I(\u_osc_counter/n2 ),
	.ZN(\u_osc_counter/n1 ));
   EDFQD1 \u_osc_counter/COUNTER_reg[6]  (.CP(OUT_CLK),
	.D(\u_osc_counter/internal_counter [6]),
	.E(\u_osc_counter/n1 ),
	.Q(COUNTER[6]));
   EDFQD1 \u_osc_counter/COUNTER_reg[3]  (.CP(OUT_CLK),
	.D(\u_osc_counter/internal_counter [3]),
	.E(\u_osc_counter/n1 ),
	.Q(COUNTER[3]));
   EDFQD1 \u_osc_counter/COUNTER_reg[2]  (.CP(OUT_CLK),
	.D(\u_osc_counter/internal_counter [2]),
	.E(\u_osc_counter/n1 ),
	.Q(COUNTER[2]));
   EDFQD1 \u_osc_counter/COUNTER_reg[7]  (.CP(OUT_CLK),
	.D(\u_osc_counter/internal_counter [7]),
	.E(\u_osc_counter/n1 ),
	.Q(COUNTER[7]));
   EDFQD1 \u_osc_counter/COUNTER_reg[5]  (.CP(OUT_CLK),
	.D(\u_osc_counter/internal_counter [5]),
	.E(\u_osc_counter/n1 ),
	.Q(COUNTER[5]));
   EDFQD1 \u_osc_counter/COUNTER_reg[4]  (.CP(OUT_CLK),
	.D(\u_osc_counter/internal_counter [4]),
	.E(\u_osc_counter/n1 ),
	.Q(COUNTER[4]));
   EDFQD1 \u_osc_counter/COUNTER_reg[1]  (.CP(OUT_CLK),
	.D(\u_osc_counter/internal_counter [1]),
	.E(\u_osc_counter/n1 ),
	.Q(COUNTER[1]));
   EDFQD1 \u_osc_counter/COUNTER_reg[0]  (.CP(OUT_CLK),
	.D(\u_osc_counter/internal_counter [0]),
	.E(\u_osc_counter/n1 ),
	.Q(COUNTER[0]));
   DFCNQD1 \u_osc_counter/internal_counter_reg[7]  (.CDN(\u_osc_counter/n1 ),
	.CP(OUT_CLK),
	.D(\u_osc_counter/N11 ),
	.Q(\u_osc_counter/internal_counter [7]));
   DFCNQD1 \u_osc_counter/internal_counter_reg[6]  (.CDN(\u_osc_counter/n1 ),
	.CP(OUT_CLK),
	.D(\u_osc_counter/N10 ),
	.Q(\u_osc_counter/internal_counter [6]));
   DFCNQD1 \u_osc_counter/internal_counter_reg[5]  (.CDN(\u_osc_counter/n1 ),
	.CP(OUT_CLK),
	.D(\u_osc_counter/N9 ),
	.Q(\u_osc_counter/internal_counter [5]));
   DFCNQD1 \u_osc_counter/internal_counter_reg[4]  (.CDN(\u_osc_counter/n1 ),
	.CP(OUT_CLK),
	.D(\u_osc_counter/N8 ),
	.Q(\u_osc_counter/internal_counter [4]));
   DFCNQD1 \u_osc_counter/internal_counter_reg[3]  (.CDN(\u_osc_counter/n1 ),
	.CP(OUT_CLK),
	.D(\u_osc_counter/N7 ),
	.Q(\u_osc_counter/internal_counter [3]));
   DFCNQD1 \u_osc_counter/internal_counter_reg[2]  (.CDN(\u_osc_counter/n1 ),
	.CP(OUT_CLK),
	.D(\u_osc_counter/N6 ),
	.Q(\u_osc_counter/internal_counter [2]));
   DFCNQD1 \u_osc_counter/internal_counter_reg[1]  (.CDN(\u_osc_counter/n1 ),
	.CP(OUT_CLK),
	.D(\u_osc_counter/N5 ),
	.Q(\u_osc_counter/internal_counter [1]));
   DFCNQD1 \u_osc_counter/internal_counter_reg[0]  (.CDN(\u_osc_counter/n1 ),
	.CP(OUT_CLK),
	.D(\u_osc_counter/N4 ),
	.Q(\u_osc_counter/internal_counter [0]));
   CKXOR2D0 \u_osc_counter/add_26/U2  (.A1(\u_osc_counter/add_26/carry [7]),
	.A2(\u_osc_counter/internal_counter [7]),
	.Z(\u_osc_counter/N11 ));
   CKND0 \u_osc_counter/add_26/U1  (.I(\u_osc_counter/internal_counter [0]),
	.ZN(\u_osc_counter/N4 ));
   HA1D0 \u_osc_counter/add_26/U1_1_1  (.A(\u_osc_counter/internal_counter [1]),
	.B(\u_osc_counter/internal_counter [0]),
	.CO(\u_osc_counter/add_26/carry [2]),
	.S(\u_osc_counter/N5 ));
   HA1D0 \u_osc_counter/add_26/U1_1_5  (.A(\u_osc_counter/internal_counter [5]),
	.B(\u_osc_counter/add_26/carry [5]),
	.CO(\u_osc_counter/add_26/carry [6]),
	.S(\u_osc_counter/N9 ));
   HA1D0 \u_osc_counter/add_26/U1_1_4  (.A(\u_osc_counter/internal_counter [4]),
	.B(\u_osc_counter/add_26/carry [4]),
	.CO(\u_osc_counter/add_26/carry [5]),
	.S(\u_osc_counter/N8 ));
   HA1D0 \u_osc_counter/add_26/U1_1_3  (.A(\u_osc_counter/internal_counter [3]),
	.B(\u_osc_counter/add_26/carry [3]),
	.CO(\u_osc_counter/add_26/carry [4]),
	.S(\u_osc_counter/N7 ));
   HA1D0 \u_osc_counter/add_26/U1_1_2  (.A(\u_osc_counter/internal_counter [2]),
	.B(\u_osc_counter/add_26/carry [2]),
	.CO(\u_osc_counter/add_26/carry [3]),
	.S(\u_osc_counter/N6 ));
   HA1D0 \u_osc_counter/add_26/U1_1_6  (.A(\u_osc_counter/internal_counter [6]),
	.B(\u_osc_counter/add_26/carry [6]),
	.CO(\u_osc_counter/add_26/carry [7]),
	.S(\u_osc_counter/N10 ));
   CKND0 \u_fd/ff1/U3  (.I(\u_fd/div_2 ),
	.ZN(\u_fd/ff1/n1 ));
   DFCNQD1 \u_fd/ff1/q_reg  (.CDN(RST_N),
	.CP(OSC_OUT),
	.D(\u_fd/ff1/n1 ),
	.Q(\u_fd/div_2 ));
   CKND0 \u_fd/ff2/U3  (.I(\u_fd/div_4 ),
	.ZN(\u_fd/ff2/n1 ));
   DFCNQD1 \u_fd/ff2/q_reg  (.CDN(RST_N),
	.CP(\u_fd/div_2 ),
	.D(\u_fd/ff2/n1 ),
	.Q(\u_fd/div_4 ));
   CKND0 \u_fd/ff3/U3  (.I(OUT_CLK),
	.ZN(\u_fd/ff3/n1 ));
   DFCNQD1 \u_fd/ff3/q_reg  (.CDN(RST_N),
	.CP(\u_fd/div_4 ),
	.D(\u_fd/ff3/n1 ),
	.Q(OUT_CLK));
   INR2D0 \u_loop_top/u_counter/U22  (.A1(\u_loop_top/u_counter/N4 ),
	.B1(\u_loop_top/u_counter/N2 ),
	.ZN(\u_loop_top/u_counter/N12 ));
   NR4D0 \u_loop_top/u_counter/U17  (.A1(\u_loop_top/u_counter/n7 ),
	.A2(\u_loop_top/u_counter/n8 ),
	.A3(\u_loop_top/u_counter/n9 ),
	.A4(\u_loop_top/u_counter/n10 ),
	.ZN(\u_loop_top/u_counter/n6 ));
   NR4D0 \u_loop_top/u_counter/U12  (.A1(\u_loop_top/u_counter/n11 ),
	.A2(\u_loop_top/u_counter/n12 ),
	.A3(\u_loop_top/u_counter/n13 ),
	.A4(\u_loop_top/u_counter/n14 ),
	.ZN(\u_loop_top/u_counter/n5 ));
   CKAN2D0 \u_loop_top/u_counter/U11  (.A1(\u_loop_top/u_counter/n5 ),
	.A2(\u_loop_top/u_counter/n6 ),
	.Z(\u_loop_top/u_counter/N2 ));
   CKBD0 \u_loop_top/u_counter/U10  (.I(FE_ECON0_RST_N),
	.Z(\u_loop_top/u_counter/n1 ));
   INR2D0 \u_loop_top/u_counter/U9  (.A1(\u_loop_top/u_counter/N5 ),
	.B1(\u_loop_top/u_counter/N2 ),
	.ZN(\u_loop_top/u_counter/N13 ));
   INR2D0 \u_loop_top/u_counter/U8  (.A1(\u_loop_top/u_counter/N6 ),
	.B1(\u_loop_top/u_counter/N2 ),
	.ZN(\u_loop_top/u_counter/N14 ));
   INR2D0 \u_loop_top/u_counter/U7  (.A1(\u_loop_top/u_counter/N7 ),
	.B1(\u_loop_top/u_counter/N2 ),
	.ZN(\u_loop_top/u_counter/N15 ));
   INR2D0 \u_loop_top/u_counter/U6  (.A1(\u_loop_top/u_counter/N8 ),
	.B1(\u_loop_top/u_counter/N2 ),
	.ZN(\u_loop_top/u_counter/N16 ));
   INR2D0 \u_loop_top/u_counter/U5  (.A1(\u_loop_top/u_counter/N9 ),
	.B1(\u_loop_top/u_counter/N2 ),
	.ZN(\u_loop_top/u_counter/N17 ));
   INR2D0 \u_loop_top/u_counter/U4  (.A1(\u_loop_top/u_counter/N10 ),
	.B1(\u_loop_top/u_counter/N2 ),
	.ZN(\u_loop_top/u_counter/N18 ));
   INR2D0 \u_loop_top/u_counter/U3  (.A1(\u_loop_top/u_counter/N11 ),
	.B1(\u_loop_top/u_counter/N2 ),
	.ZN(\u_loop_top/u_counter/N19 ));
   DFCNQD1 \u_loop_top/u_counter/count_reg[5]  (.CDN(\u_loop_top/u_counter/n1 ),
	.CP(CLK),
	.D(\u_loop_top/u_counter/N17 ),
	.Q(\u_loop_top/u_counter/count[5] ));
   CKXOR2D0 \u_loop_top/u_counter/U21  (.A1(TOTAL_COUNT[7]),
	.A2(\u_loop_top/u_counter/count[7] ),
	.Z(\u_loop_top/u_counter/n11 ));
   CKXOR2D0 \u_loop_top/u_counter/U20  (.A1(TOTAL_COUNT[6]),
	.A2(\u_loop_top/u_counter/count[6] ),
	.Z(\u_loop_top/u_counter/n12 ));
   CKXOR2D0 \u_loop_top/u_counter/U19  (.A1(TOTAL_COUNT[5]),
	.A2(\u_loop_top/u_counter/count[5] ),
	.Z(\u_loop_top/u_counter/n13 ));
   CKXOR2D0 \u_loop_top/u_counter/U18  (.A1(TOTAL_COUNT[4]),
	.A2(\u_loop_top/u_counter/count[4] ),
	.Z(\u_loop_top/u_counter/n14 ));
   CKXOR2D0 \u_loop_top/u_counter/U16  (.A1(TOTAL_COUNT[3]),
	.A2(\u_loop_top/u_counter/count[3] ),
	.Z(\u_loop_top/u_counter/n7 ));
   CKXOR2D0 \u_loop_top/u_counter/U15  (.A1(TOTAL_COUNT[2]),
	.A2(\u_loop_top/u_counter/count[2] ),
	.Z(\u_loop_top/u_counter/n8 ));
   CKXOR2D0 \u_loop_top/u_counter/U14  (.A1(TOTAL_COUNT[1]),
	.A2(\u_loop_top/u_counter/count[1] ),
	.Z(\u_loop_top/u_counter/n9 ));
   CKXOR2D0 \u_loop_top/u_counter/U13  (.A1(TOTAL_COUNT[0]),
	.A2(\u_loop_top/u_counter/count[0] ),
	.Z(\u_loop_top/u_counter/n10 ));
   DFCNQD1 \u_loop_top/u_counter/count_reg[7]  (.CDN(\u_loop_top/u_counter/n1 ),
	.CP(CLK),
	.D(\u_loop_top/u_counter/N19 ),
	.Q(\u_loop_top/u_counter/count[7] ));
   DFCNQD1 \u_loop_top/u_counter/count_reg[6]  (.CDN(\u_loop_top/u_counter/n1 ),
	.CP(CLK),
	.D(\u_loop_top/u_counter/N18 ),
	.Q(\u_loop_top/u_counter/count[6] ));
   DFCNQD1 \u_loop_top/u_counter/count_reg[4]  (.CDN(\u_loop_top/u_counter/n1 ),
	.CP(CLK),
	.D(\u_loop_top/u_counter/N16 ),
	.Q(\u_loop_top/u_counter/count[4] ));
   DFCNQD1 \u_loop_top/u_counter/count_reg[3]  (.CDN(\u_loop_top/u_counter/n1 ),
	.CP(CLK),
	.D(\u_loop_top/u_counter/N15 ),
	.Q(\u_loop_top/u_counter/count[3] ));
   DFCNQD1 \u_loop_top/u_counter/count_reg[2]  (.CDN(\u_loop_top/u_counter/n1 ),
	.CP(CLK),
	.D(\u_loop_top/u_counter/N14 ),
	.Q(\u_loop_top/u_counter/count[2] ));
   DFCNQD1 \u_loop_top/u_counter/count_reg[1]  (.CDN(\u_loop_top/u_counter/n1 ),
	.CP(CLK),
	.D(\u_loop_top/u_counter/N13 ),
	.Q(\u_loop_top/u_counter/count[1] ));
   DFCNQD1 \u_loop_top/u_counter/count_done_reg  (.CDN(\u_loop_top/u_counter/n1 ),
	.CP(CLK),
	.D(\u_loop_top/u_counter/N2 ),
	.Q(COUNT_DONE));
   DFCNQD1 \u_loop_top/u_counter/count_reg[0]  (.CDN(\u_loop_top/u_counter/n1 ),
	.CP(CLK),
	.D(\u_loop_top/u_counter/N12 ),
	.Q(\u_loop_top/u_counter/count[0] ));
   CKND0 \u_loop_top/u_counter/add_22/U8  (.I(\u_loop_top/u_counter/count[0] ),
	.ZN(\u_loop_top/u_counter/N4 ));
   CKXOR2D0 \u_loop_top/u_counter/add_22/U7  (.A1(\u_loop_top/u_counter/count[1] ),
	.A2(\u_loop_top/u_counter/count[0] ),
	.Z(\u_loop_top/u_counter/N5 ));
   CKXOR2D0 \u_loop_top/u_counter/add_22/U6  (.A1(\u_loop_top/u_counter/count[5] ),
	.A2(\u_loop_top/u_counter/add_22/carry [5]),
	.Z(\u_loop_top/u_counter/N9 ));
   CKXOR2D0 \u_loop_top/u_counter/add_22/U5  (.A1(\u_loop_top/u_counter/count[2] ),
	.A2(\u_loop_top/u_counter/add_22/n3 ),
	.Z(\u_loop_top/u_counter/N6 ));
   CKXOR2D0 \u_loop_top/u_counter/add_22/U4  (.A1(\u_loop_top/u_counter/add_22/carry [7]),
	.A2(\u_loop_top/u_counter/count[7] ),
	.Z(\u_loop_top/u_counter/N11 ));
   CKAN2D0 \u_loop_top/u_counter/add_22/U3  (.A1(\u_loop_top/u_counter/count[1] ),
	.A2(\u_loop_top/u_counter/count[0] ),
	.Z(\u_loop_top/u_counter/add_22/n3 ));
   CKAN2D0 \u_loop_top/u_counter/add_22/U2  (.A1(\u_loop_top/u_counter/count[5] ),
	.A2(\u_loop_top/u_counter/add_22/carry [5]),
	.Z(\u_loop_top/u_counter/add_22/n2 ));
   CKAN2D0 \u_loop_top/u_counter/add_22/U1  (.A1(\u_loop_top/u_counter/count[2] ),
	.A2(\u_loop_top/u_counter/add_22/n3 ),
	.Z(\u_loop_top/u_counter/add_22/n1 ));
   HA1D0 \u_loop_top/u_counter/add_22/U1_1_3  (.A(\u_loop_top/u_counter/count[3] ),
	.B(\u_loop_top/u_counter/add_22/n1 ),
	.CO(\u_loop_top/u_counter/add_22/carry [4]),
	.S(\u_loop_top/u_counter/N7 ));
   HA1D0 \u_loop_top/u_counter/add_22/U1_1_6  (.A(\u_loop_top/u_counter/count[6] ),
	.B(\u_loop_top/u_counter/add_22/n2 ),
	.CO(\u_loop_top/u_counter/add_22/carry [7]),
	.S(\u_loop_top/u_counter/N10 ));
   HA1D0 \u_loop_top/u_counter/add_22/U1_1_4  (.A(\u_loop_top/u_counter/count[4] ),
	.B(\u_loop_top/u_counter/add_22/carry [4]),
	.CO(\u_loop_top/u_counter/add_22/carry [5]),
	.S(\u_loop_top/u_counter/N8 ));
   NR2D0 \u_loop_top/u_up_down_counter_32b_avg/U166  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n21 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n146 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [31]));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U165  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n14 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n144 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n21 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n143 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [30]));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U164  (.I(CURRENT_SOURCE_ENABLE[31]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n144 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U163  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n146 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n145 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n21 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n142 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [29]));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U162  (.I(CURRENT_SOURCE_ENABLE[30]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n146 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U161  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n14 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n143 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n21 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n141 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [28]));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U160  (.I(CURRENT_SOURCE_ENABLE[29]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n143 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U159  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n14 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n142 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n21 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n140 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [27]));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U158  (.I(CURRENT_SOURCE_ENABLE[28]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n142 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U157  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n14 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n141 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n21 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n139 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [26]));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U156  (.I(CURRENT_SOURCE_ENABLE[27]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n141 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U155  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n14 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n140 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n21 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n138 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [25]));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U154  (.I(CURRENT_SOURCE_ENABLE[26]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n140 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U153  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n14 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n139 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n21 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n137 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [24]));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U152  (.I(CURRENT_SOURCE_ENABLE[25]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n139 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U151  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n14 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n138 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n21 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n136 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [23]));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U150  (.I(CURRENT_SOURCE_ENABLE[24]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n138 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U149  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n14 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n137 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n21 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n135 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [22]));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U148  (.I(CURRENT_SOURCE_ENABLE[23]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n137 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U147  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n14 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n136 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n21 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n134 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [21]));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U146  (.I(CURRENT_SOURCE_ENABLE[22]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n136 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U145  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n14 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n135 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n20 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n133 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [20]));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U144  (.I(CURRENT_SOURCE_ENABLE[21]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n135 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U143  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n14 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n134 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n20 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n132 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [19]));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U142  (.I(CURRENT_SOURCE_ENABLE[20]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n134 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U141  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n14 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n133 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n20 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n131 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [18]));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U140  (.I(CURRENT_SOURCE_ENABLE[19]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n133 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U139  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n145 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n132 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n20 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n130 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [17]));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U138  (.I(CURRENT_SOURCE_ENABLE[18]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n132 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U137  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n145 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n131 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n20 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n129 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [16]));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U136  (.I(CURRENT_SOURCE_ENABLE[17]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n131 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U135  (.I(CURRENT_SOURCE_ENABLE[0]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n127 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U134  (.I(CURRENT_SOURCE_ENABLE[1]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n128 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U133  (.I(CURRENT_SOURCE_ENABLE[2]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n123 ));
   AOI31D0 \u_loop_top/u_up_down_counter_32b_avg/U132  (.A1(CURRENT_SOURCE_ENABLE[5]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.B(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n118 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U131  (.I(CURRENT_SOURCE_ENABLE[3]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n121 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U130  (.I(CURRENT_SOURCE_ENABLE[4]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n119 ));
   AOI31D0 \u_loop_top/u_up_down_counter_32b_avg/U129  (.A1(CURRENT_SOURCE_ENABLE[7]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.B(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n114 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U128  (.I(CURRENT_SOURCE_ENABLE[5]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n117 ));
   AOI31D0 \u_loop_top/u_up_down_counter_32b_avg/U127  (.A1(CURRENT_SOURCE_ENABLE[8]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.B(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n112 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U126  (.I(CURRENT_SOURCE_ENABLE[6]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n115 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U125  (.I(CURRENT_SOURCE_ENABLE[7]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n113 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U124  (.I(CURRENT_SOURCE_ENABLE[8]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n109 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U123  (.I(CURRENT_SOURCE_ENABLE[9]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n110 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U122  (.I(CURRENT_SOURCE_ENABLE[10]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n108 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U121  (.I(CURRENT_SOURCE_ENABLE[11]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n107 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U120  (.I(CURRENT_SOURCE_ENABLE[12]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n106 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U119  (.I(CURRENT_SOURCE_ENABLE[13]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n105 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U118  (.I(CURRENT_SOURCE_ENABLE[15]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n129 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U117  (.I(\u_loop_top/u_up_down_counter_32b_avg/n145 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n126 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U116  (.I(CURRENT_SOURCE_ENABLE[16]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n130 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U115  (.I(CURRENT_SOURCE_ENABLE[14]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n104 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U113  (.I(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n103 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U109  (.I(LOWER_VOLTAGE_BOUND[7]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n70 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U108  (.I(\u_loop_top/u_up_down_counter_32b_avg/n73 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n78 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U107  (.A1(COUNTER[6]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n68 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n73 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U106  (.I(LOWER_VOLTAGE_BOUND[6]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n68 ));
   OAI32D0 \u_loop_top/u_up_down_counter_32b_avg/U104  (.A1(UPPER_VOLTAGE_BOUND[4]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n59 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n75 ),
	.B1(UPPER_VOLTAGE_BOUND[5]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n58 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n61 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U103  (.I(\u_loop_top/u_up_down_counter_32b_avg/n57 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n59 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U102  (.A1(UPPER_VOLTAGE_BOUND[5]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n58 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n57 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U101  (.I(COUNTER[5]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n58 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U100  (.A1(UPPER_VOLTAGE_BOUND[7]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n64 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n66 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U99  (.I(COUNTER[7]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n64 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U98  (.I(COUNTER[4]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n75 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U97  (.I(COUNTER[0]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n79 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U96  (.I(COUNTER[1]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n80 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U95  (.I(COUNTER[2]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n84 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U94  (.A1(UPPER_VOLTAGE_BOUND[3]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n86 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n51 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U93  (.I(COUNTER[3]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n86 ));
   INR2D0 \u_loop_top/u_up_down_counter_32b_avg/U91  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n92 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n76 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n77 ));
   ND3D0 \u_loop_top/u_up_down_counter_32b_avg/U90  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n56 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n55 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n57 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n100 ));
   ND3D0 \u_loop_top/u_up_down_counter_32b_avg/U89  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n89 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n84 ),
	.A3(LOWER_VOLTAGE_BOUND[2]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n85 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U88  (.A1(UPPER_VOLTAGE_BOUND[1]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n80 ),
	.B1(UPPER_VOLTAGE_BOUND[0]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n79 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n49 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U87  (.A1(UPPER_VOLTAGE_BOUND[2]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n84 ),
	.B1(UPPER_VOLTAGE_BOUND[1]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n80 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n50 ));
   ND3D0 \u_loop_top/u_up_down_counter_32b_avg/U86  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n51 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n50 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n49 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n53 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U80  (.A1(LOWER_VOLTAGE_BOUND[1]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n80 ),
	.B1(LOWER_VOLTAGE_BOUND[0]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n79 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n82 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U79  (.A1(LOWER_VOLTAGE_BOUND[2]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n84 ),
	.B1(LOWER_VOLTAGE_BOUND[1]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n80 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n81 ));
   IND2D0 \u_loop_top/u_up_down_counter_32b_avg/U76  (.A1(COUNTER[7]),
	.B1(LOWER_VOLTAGE_BOUND[7]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n93 ));
   OAI211D1 \u_loop_top/u_up_down_counter_32b_avg/U75  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n96 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n95 ),
	.B(\u_loop_top/u_up_down_counter_32b_avg/n94 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n93 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n102 ));
   IOA21D0 \u_loop_top/u_up_down_counter_32b_avg/U74  (.A1(LOWER_VOLTAGE_BOUND[3]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n86 ),
	.B(\u_loop_top/u_up_down_counter_32b_avg/n85 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n88 ));
   NR2D0 \u_loop_top/u_up_down_counter_32b_avg/U73  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n82 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n81 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n90 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U72  (.I(UPPER_VOLTAGE_BOUND[3]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n31 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U71  (.I(UPPER_VOLTAGE_BOUND[2]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n32 ));
   AOI32D0 \u_loop_top/u_up_down_counter_32b_avg/U70  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n51 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n32 ),
	.A3(COUNTER[2]),
	.B1(COUNTER[3]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n31 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n54 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U69  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n113 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n115 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n112 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n39 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U68  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n115 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n114 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n38 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U67  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n119 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n116 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n37 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U66  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n119 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n121 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n118 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n36 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U65  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n128 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n122 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n34 ));
   BUFFD1 \u_loop_top/u_up_down_counter_32b_avg/U63  (.I(FE_ECON0_RST_N),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n29 ));
   BUFFD1 \u_loop_top/u_up_down_counter_32b_avg/U62  (.I(FE_ECON0_RST_N),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n28 ));
   CKND2 \u_loop_top/u_up_down_counter_32b_avg/U60  (.I(\u_loop_top/u_up_down_counter_32b_avg/n27 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n23 ));
   IND2D0 \u_loop_top/u_up_down_counter_32b_avg/U58  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n125 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n103 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n147 ));
   OAI222D0 \u_loop_top/u_up_down_counter_32b_avg/U57  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n20 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n105 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n129 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n111 ),
	.C1(\u_loop_top/u_up_down_counter_32b_avg/n24 ),
	.C2(\u_loop_top/u_up_down_counter_32b_avg/n104 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n46 ));
   OAI222D0 \u_loop_top/u_up_down_counter_32b_avg/U56  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n20 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n106 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n111 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n104 ),
	.C1(\u_loop_top/u_up_down_counter_32b_avg/n24 ),
	.C2(\u_loop_top/u_up_down_counter_32b_avg/n105 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n45 ));
   OAI222D0 \u_loop_top/u_up_down_counter_32b_avg/U55  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n20 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n107 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n111 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n105 ),
	.C1(\u_loop_top/u_up_down_counter_32b_avg/n24 ),
	.C2(\u_loop_top/u_up_down_counter_32b_avg/n106 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n44 ));
   OAI222D0 \u_loop_top/u_up_down_counter_32b_avg/U54  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n20 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n108 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n111 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n106 ),
	.C1(\u_loop_top/u_up_down_counter_32b_avg/n24 ),
	.C2(\u_loop_top/u_up_down_counter_32b_avg/n107 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n43 ));
   OAI222D0 \u_loop_top/u_up_down_counter_32b_avg/U53  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n20 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n104 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n130 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n111 ),
	.C1(\u_loop_top/u_up_down_counter_32b_avg/n24 ),
	.C2(\u_loop_top/u_up_down_counter_32b_avg/n129 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n47 ));
   AOI31D0 \u_loop_top/u_up_down_counter_32b_avg/U52  (.A1(CURRENT_SOURCE_ENABLE[6]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n24 ),
	.B(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n116 ));
   AOI31D0 \u_loop_top/u_up_down_counter_32b_avg/U51  (.A1(CURRENT_SOURCE_ENABLE[3]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n24 ),
	.B(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n122 ));
   AOI31D0 \u_loop_top/u_up_down_counter_32b_avg/U50  (.A1(CURRENT_SOURCE_ENABLE[4]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n24 ),
	.B(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n120 ));
   AOI211D0 \u_loop_top/u_up_down_counter_32b_avg/U49  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n90 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n89 ),
	.B(\u_loop_top/u_up_down_counter_32b_avg/n88 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n15 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n95 ));
   IND2D0 \u_loop_top/u_up_down_counter_32b_avg/U48  (.A1(COUNTER[6]),
	.B1(UPPER_VOLTAGE_BOUND[6]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n55 ));
   OR3D0 \u_loop_top/u_up_down_counter_32b_avg/U46  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n16 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n17 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n18 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n40 ));
   NR2D0 \u_loop_top/u_up_down_counter_32b_avg/U45  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n24 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n109 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n18 ));
   NR2D0 \u_loop_top/u_up_down_counter_32b_avg/U44  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n111 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n110 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n17 ));
   NR2D0 \u_loop_top/u_up_down_counter_32b_avg/U43  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n20 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n113 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n16 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U42  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n125 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n103 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n145 ));
   ND2D0 \u_loop_top/u_up_down_counter_32b_avg/U41  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n125 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n103 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n14 ));
   OR3D0 \u_loop_top/u_up_down_counter_32b_avg/U40  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n11 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n12 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n13 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n42 ));
   NR2D0 \u_loop_top/u_up_down_counter_32b_avg/U39  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n24 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n108 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n13 ));
   NR2D0 \u_loop_top/u_up_down_counter_32b_avg/U38  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n111 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n107 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n12 ));
   NR2D0 \u_loop_top/u_up_down_counter_32b_avg/U37  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n20 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n110 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n11 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U35  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n27 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n128 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n24 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n127 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n126 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n48 ));
   ND3D0 \u_loop_top/u_up_down_counter_32b_avg/U34  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n7 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n8 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n120 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n35 ));
   OR2D0 \u_loop_top/u_up_down_counter_32b_avg/U33  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n8 ));
   OAI211D0 \u_loop_top/u_up_down_counter_32b_avg/U32  (.A1(LOWER_VOLTAGE_BOUND[4]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n75 ),
	.B(\u_loop_top/u_up_down_counter_32b_avg/n74 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n73 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n76 ));
   OR3D0 \u_loop_top/u_up_down_counter_32b_avg/U31  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n4 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n5 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n6 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n41 ));
   NR2D0 \u_loop_top/u_up_down_counter_32b_avg/U30  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n24 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n110 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n6 ));
   NR2D0 \u_loop_top/u_up_down_counter_32b_avg/U29  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n111 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n108 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n5 ));
   NR2D0 \u_loop_top/u_up_down_counter_32b_avg/U28  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n20 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n109 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n4 ));
   OR2D0 \u_loop_top/u_up_down_counter_32b_avg/U26  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n121 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n7 ));
   OR2D0 \u_loop_top/u_up_down_counter_32b_avg/U25  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n145 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n27 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n111 ));
   NR2D0 \u_loop_top/u_up_down_counter_32b_avg/U24  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n3 ),
	.A2(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n124 ));
   ND3D0 \u_loop_top/u_up_down_counter_32b_avg/U23  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n1 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n2 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n124 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n33 ));
   OR2D0 \u_loop_top/u_up_down_counter_32b_avg/U22  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n127 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n2 ));
   OR2D0 \u_loop_top/u_up_down_counter_32b_avg/U21  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n128 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n1 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U20  (.A1(COUNTER[7]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n70 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n92 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U19  (.A1(COUNTER[5]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n71 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n74 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U18  (.I(\u_loop_top/u_up_down_counter_32b_avg/n9 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n10 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U17  (.I(\u_loop_top/u_up_down_counter_32b_avg/n125 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n9 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U16  (.A1(COUNT_DONE),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n102 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n125 ));
   ND3D0 \u_loop_top/u_up_down_counter_32b_avg/U15  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n72 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n92 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n74 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n87 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U14  (.I(LOWER_VOLTAGE_BOUND[4]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n69 ));
   AN3D0 \u_loop_top/u_up_down_counter_32b_avg/U12  (.A1(CURRENT_SOURCE_ENABLE[2]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n3 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U11  (.A1(COUNTER[5]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n71 ),
	.B1(COUNTER[4]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n69 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n72 ));
   AN3D0 \u_loop_top/u_up_down_counter_32b_avg/U10  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n72 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n92 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n74 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n15 ));
   CKBD0 \u_loop_top/u_up_down_counter_32b_avg/U8  (.I(\u_loop_top/u_up_down_counter_32b_avg/n147 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n21 ));
   CKBD0 \u_loop_top/u_up_down_counter_32b_avg/U7  (.I(\u_loop_top/u_up_down_counter_32b_avg/n147 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n20 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U6  (.I(LOWER_VOLTAGE_BOUND[5]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n71 ));
   CKND1 \u_loop_top/u_up_down_counter_32b_avg/U5  (.I(\u_loop_top/u_up_down_counter_32b_avg/n27 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n24 ));
   IAO21D0 \u_loop_top/u_up_down_counter_32b_avg/U3  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n78 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n87 ),
	.B(\u_loop_top/u_up_down_counter_32b_avg/n77 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n96 ));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[16]  (.CDN(FE_ECON0_RST_N),
	.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [16]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n24 ),
	.Q(CURRENT_SOURCE_ENABLE[16]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[17]  (.CDN(FE_ECON0_RST_N),
	.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [17]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n24 ),
	.Q(CURRENT_SOURCE_ENABLE[17]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[19]  (.CDN(FE_ECON0_RST_N),
	.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [19]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n24 ),
	.Q(CURRENT_SOURCE_ENABLE[19]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[20]  (.CDN(FE_ECON0_RST_N),
	.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [20]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n24 ),
	.Q(CURRENT_SOURCE_ENABLE[20]));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[2]  (.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n34 ),
	.Q(CURRENT_SOURCE_ENABLE[2]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n29 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[3]  (.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n35 ),
	.Q(CURRENT_SOURCE_ENABLE[3]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n29 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[4]  (.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n36 ),
	.Q(CURRENT_SOURCE_ENABLE[4]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n28 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[5]  (.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n37 ),
	.Q(CURRENT_SOURCE_ENABLE[5]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n28 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[6]  (.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n38 ),
	.Q(CURRENT_SOURCE_ENABLE[6]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n28 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[7]  (.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n39 ),
	.Q(CURRENT_SOURCE_ENABLE[7]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n28 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[8]  (.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n40 ),
	.Q(CURRENT_SOURCE_ENABLE[8]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n28 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[1]  (.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n33 ),
	.Q(CURRENT_SOURCE_ENABLE[1]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n29 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[9]  (.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n41 ),
	.Q(CURRENT_SOURCE_ENABLE[9]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n28 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[10]  (.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n42 ),
	.Q(CURRENT_SOURCE_ENABLE[10]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n28 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[11]  (.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n43 ),
	.Q(CURRENT_SOURCE_ENABLE[11]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n28 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[12]  (.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n44 ),
	.Q(CURRENT_SOURCE_ENABLE[12]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n28 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[13]  (.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n45 ),
	.Q(CURRENT_SOURCE_ENABLE[13]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n28 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[14]  (.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n46 ),
	.Q(CURRENT_SOURCE_ENABLE[14]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n28 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[15]  (.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n47 ),
	.Q(CURRENT_SOURCE_ENABLE[15]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n28 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[0]  (.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n48 ),
	.Q(CURRENT_SOURCE_ENABLE[0]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n28 ));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[18]  (.CDN(FE_ECON0_RST_N),
	.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [18]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.Q(CURRENT_SOURCE_ENABLE[18]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[21]  (.CDN(FE_ECON0_RST_N),
	.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [21]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.Q(CURRENT_SOURCE_ENABLE[21]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[22]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n29 ),
	.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [22]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.Q(CURRENT_SOURCE_ENABLE[22]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[23]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n29 ),
	.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [23]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.Q(CURRENT_SOURCE_ENABLE[23]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[24]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n29 ),
	.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [24]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.Q(CURRENT_SOURCE_ENABLE[24]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[25]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n29 ),
	.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [25]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.Q(CURRENT_SOURCE_ENABLE[25]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[26]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n29 ),
	.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [26]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.Q(CURRENT_SOURCE_ENABLE[26]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[27]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n29 ),
	.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [27]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.Q(CURRENT_SOURCE_ENABLE[27]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[28]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n29 ),
	.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [28]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.Q(CURRENT_SOURCE_ENABLE[28]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[29]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n29 ),
	.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [29]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.Q(CURRENT_SOURCE_ENABLE[29]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[30]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n29 ),
	.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [30]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.Q(CURRENT_SOURCE_ENABLE[30]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[31]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n29 ),
	.CP(CLK),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [31]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.Q(CURRENT_SOURCE_ENABLE[31]));
endmodule

