/*
###############################################################
#  Generated by:      Cadence Innovus 16.12-s051_1
#  OS:                Linux x86_64(Host ID ecegrid-thin3.ecn.purdue.edu)
#  Generated on:      Thu Apr 23 14:59:38 2020
#  Design:            closed_loop_current_controller_v2
#  Command:           saveNetlist /home/sparclab/a/ghosh69/march_20_tapeout/current_source_controller/logs/closed_loop_current_controller_v2.gate.v -excludepowerground -excludeLeafCell
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : L-2016.03-SP2
// Date      : Thu Apr 23 14:19:40 2020
/////////////////////////////////////////////////////////////
module closed_loop_current_controller_v2 (
	OUT_CLK, 
	RST_N, 
	CLK, 
	LOOP_BYPASS, 
	CURRENT_SOURCE_ENABLE, 
	TOTAL_COUNT, 
	LOWER_VOLTAGE_BOUND, 
	UPPER_VOLTAGE_BOUND, 
	COUNTER, 
	NO_CURRENT_SOURCE, 
	VDD, 
	VSS);
   input OUT_CLK;
   input RST_N;
   input CLK;
   input LOOP_BYPASS;
   output [31:0] CURRENT_SOURCE_ENABLE;
   input [7:0] TOTAL_COUNT;
   input [7:0] LOWER_VOLTAGE_BOUND;
   input [7:0] UPPER_VOLTAGE_BOUND;
   output [7:0] COUNTER;
   input [31:0] NO_CURRENT_SOURCE;
   inout VDD;
   inout VSS;

   // Internal wires
   wire FE_ECON0_RST_N;
   wire CTS_12;
   wire CTS_11;
   wire CTS_10;
   wire COUNT_DONE;
   wire \u_osc_counter/n1 ;
   wire \u_osc_counter/n2 ;
   wire \u_osc_counter/N11 ;
   wire \u_osc_counter/N10 ;
   wire \u_osc_counter/N9 ;
   wire \u_osc_counter/N8 ;
   wire \u_osc_counter/N7 ;
   wire \u_osc_counter/N6 ;
   wire \u_osc_counter/N5 ;
   wire \u_osc_counter/N4 ;
   wire \u_loop_top/u_counter/n4 ;
   wire \u_loop_top/u_counter/n3 ;
   wire \u_loop_top/u_counter/n2 ;
   wire \u_loop_top/u_counter/n1 ;
   wire \u_loop_top/u_counter/n14 ;
   wire \u_loop_top/u_counter/n13 ;
   wire \u_loop_top/u_counter/n12 ;
   wire \u_loop_top/u_counter/n11 ;
   wire \u_loop_top/u_counter/n10 ;
   wire \u_loop_top/u_counter/n9 ;
   wire \u_loop_top/u_counter/n8 ;
   wire \u_loop_top/u_counter/n7 ;
   wire \u_loop_top/u_counter/N19 ;
   wire \u_loop_top/u_counter/N18 ;
   wire \u_loop_top/u_counter/N17 ;
   wire \u_loop_top/u_counter/N16 ;
   wire \u_loop_top/u_counter/N15 ;
   wire \u_loop_top/u_counter/N14 ;
   wire \u_loop_top/u_counter/N13 ;
   wire \u_loop_top/u_counter/N12 ;
   wire \u_loop_top/u_counter/N11 ;
   wire \u_loop_top/u_counter/N10 ;
   wire \u_loop_top/u_counter/N9 ;
   wire \u_loop_top/u_counter/N8 ;
   wire \u_loop_top/u_counter/N7 ;
   wire \u_loop_top/u_counter/N6 ;
   wire \u_loop_top/u_counter/N5 ;
   wire \u_loop_top/u_counter/N4 ;
   wire \u_loop_top/u_counter/count[0] ;
   wire \u_loop_top/u_counter/count[1] ;
   wire \u_loop_top/u_counter/count[2] ;
   wire \u_loop_top/u_counter/count[3] ;
   wire \u_loop_top/u_counter/count[4] ;
   wire \u_loop_top/u_counter/count[5] ;
   wire \u_loop_top/u_counter/count[6] ;
   wire \u_loop_top/u_counter/count[7] ;
   wire \u_loop_top/u_counter/add_22/n2 ;
   wire \u_loop_top/u_counter/add_22/n1 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n123 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n122 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n121 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n120 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n119 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n118 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n117 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n116 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n115 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n114 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n113 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n112 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n111 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n110 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n109 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n108 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n107 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n106 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n105 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n104 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n103 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n102 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n101 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n100 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n99 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n98 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n97 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n96 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n95 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n94 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n93 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n92 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n91 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n90 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n89 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n88 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n87 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n86 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n85 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n84 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n83 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n82 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n80 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n79 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n78 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n77 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n76 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n75 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n74 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n73 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n72 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n71 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n70 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n68 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n67 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n66 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n65 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n64 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n63 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n62 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n61 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n60 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n59 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n58 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n57 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n56 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n54 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n53 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n52 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n51 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n49 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n48 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n47 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n30 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n29 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n28 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n27 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n26 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n25 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n24 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n23 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n22 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n21 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n20 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n19 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n18 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n17 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n15 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n14 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n13 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n12 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n11 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n10 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n9 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n8 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n7 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n6 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n5 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n4 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n3 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n2 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n1 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n46 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n45 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n44 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n43 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n42 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n41 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n40 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n39 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n38 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n37 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n36 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n35 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n34 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n33 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n32 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/n31 ;
   wire \u_loop_top/u_up_down_counter_32b_avg/N6 ;
   wire [7:0] \u_osc_counter/internal_counter ;
   wire [7:2] \u_osc_counter/add_26/carry ;
   wire [7:2] \u_loop_top/u_counter/add_22/carry ;
   wire [31:0] \u_loop_top/u_up_down_counter_32b_avg/out_count_next ;

   CKBD0 FE_ECOC0_RST_N (.I(RST_N),
	.Z(FE_ECON0_RST_N));
   IND2D0 FE_RC_3_0 (.A1(LOWER_VOLTAGE_BOUND[6]),
	.B1(COUNTER[6]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n73 ));
   IND2D0 FE_RC_2_0 (.A1(UPPER_VOLTAGE_BOUND[7]),
	.B1(COUNTER[7]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n52 ));
   CKBD4 CTS_ccl_BUF_CLK_G0_L1_3 (.I(CLK),
	.Z(CTS_12));
   CKBD4 CTS_ccl_BUF_CLK_G0_L1_2 (.I(CLK),
	.Z(CTS_11));
   CKBD4 CTS_ccl_BUF_CLK_G0_L1_1 (.I(CLK),
	.Z(CTS_10));
   IINR4D1 FE_RC_1_0 (.A1(\u_loop_top/u_up_down_counter_32b_avg/n73 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n72 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n68 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n67 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n83 ));
   IOA21D0 FE_RC_0_0 (.A1(\u_loop_top/u_up_down_counter_32b_avg/n79 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n78 ),
	.B(\u_loop_top/u_up_down_counter_32b_avg/n80 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n82 ));
   IND2D0 \u_osc_counter/U4  (.A1(COUNT_DONE),
	.B1(FE_ECON0_RST_N),
	.ZN(\u_osc_counter/n2 ));
   CKND1 \u_osc_counter/U3  (.I(\u_osc_counter/n2 ),
	.ZN(\u_osc_counter/n1 ));
   EDFQD1 \u_osc_counter/COUNTER_reg[4]  (.CP(OUT_CLK),
	.D(\u_osc_counter/internal_counter [4]),
	.E(\u_osc_counter/n1 ),
	.Q(COUNTER[4]));
   EDFQD1 \u_osc_counter/COUNTER_reg[7]  (.CP(OUT_CLK),
	.D(\u_osc_counter/internal_counter [7]),
	.E(\u_osc_counter/n1 ),
	.Q(COUNTER[7]));
   EDFQD1 \u_osc_counter/COUNTER_reg[5]  (.CP(OUT_CLK),
	.D(\u_osc_counter/internal_counter [5]),
	.E(\u_osc_counter/n1 ),
	.Q(COUNTER[5]));
   EDFQD1 \u_osc_counter/COUNTER_reg[6]  (.CP(OUT_CLK),
	.D(\u_osc_counter/internal_counter [6]),
	.E(\u_osc_counter/n1 ),
	.Q(COUNTER[6]));
   EDFQD1 \u_osc_counter/COUNTER_reg[3]  (.CP(OUT_CLK),
	.D(\u_osc_counter/internal_counter [3]),
	.E(\u_osc_counter/n1 ),
	.Q(COUNTER[3]));
   EDFQD1 \u_osc_counter/COUNTER_reg[2]  (.CP(OUT_CLK),
	.D(\u_osc_counter/internal_counter [2]),
	.E(\u_osc_counter/n1 ),
	.Q(COUNTER[2]));
   EDFQD1 \u_osc_counter/COUNTER_reg[1]  (.CP(OUT_CLK),
	.D(\u_osc_counter/internal_counter [1]),
	.E(\u_osc_counter/n1 ),
	.Q(COUNTER[1]));
   EDFQD1 \u_osc_counter/COUNTER_reg[0]  (.CP(OUT_CLK),
	.D(\u_osc_counter/internal_counter [0]),
	.E(\u_osc_counter/n1 ),
	.Q(COUNTER[0]));
   DFCNQD1 \u_osc_counter/internal_counter_reg[7]  (.CDN(\u_osc_counter/n1 ),
	.CP(OUT_CLK),
	.D(\u_osc_counter/N11 ),
	.Q(\u_osc_counter/internal_counter [7]));
   DFCNQD1 \u_osc_counter/internal_counter_reg[6]  (.CDN(\u_osc_counter/n1 ),
	.CP(OUT_CLK),
	.D(\u_osc_counter/N10 ),
	.Q(\u_osc_counter/internal_counter [6]));
   DFCNQD1 \u_osc_counter/internal_counter_reg[5]  (.CDN(\u_osc_counter/n1 ),
	.CP(OUT_CLK),
	.D(\u_osc_counter/N9 ),
	.Q(\u_osc_counter/internal_counter [5]));
   DFCNQD1 \u_osc_counter/internal_counter_reg[4]  (.CDN(\u_osc_counter/n1 ),
	.CP(OUT_CLK),
	.D(\u_osc_counter/N8 ),
	.Q(\u_osc_counter/internal_counter [4]));
   DFCNQD1 \u_osc_counter/internal_counter_reg[3]  (.CDN(\u_osc_counter/n1 ),
	.CP(OUT_CLK),
	.D(\u_osc_counter/N7 ),
	.Q(\u_osc_counter/internal_counter [3]));
   DFCNQD1 \u_osc_counter/internal_counter_reg[2]  (.CDN(\u_osc_counter/n1 ),
	.CP(OUT_CLK),
	.D(\u_osc_counter/N6 ),
	.Q(\u_osc_counter/internal_counter [2]));
   DFCNQD1 \u_osc_counter/internal_counter_reg[1]  (.CDN(\u_osc_counter/n1 ),
	.CP(OUT_CLK),
	.D(\u_osc_counter/N5 ),
	.Q(\u_osc_counter/internal_counter [1]));
   DFCNQD1 \u_osc_counter/internal_counter_reg[0]  (.CDN(\u_osc_counter/n1 ),
	.CP(OUT_CLK),
	.D(\u_osc_counter/N4 ),
	.Q(\u_osc_counter/internal_counter [0]));
   CKXOR2D0 \u_osc_counter/add_26/U2  (.A1(\u_osc_counter/add_26/carry [7]),
	.A2(\u_osc_counter/internal_counter [7]),
	.Z(\u_osc_counter/N11 ));
   CKND0 \u_osc_counter/add_26/U1  (.I(\u_osc_counter/internal_counter [0]),
	.ZN(\u_osc_counter/N4 ));
   HA1D0 \u_osc_counter/add_26/U1_1_1  (.A(\u_osc_counter/internal_counter [1]),
	.B(\u_osc_counter/internal_counter [0]),
	.CO(\u_osc_counter/add_26/carry [2]),
	.S(\u_osc_counter/N5 ));
   HA1D0 \u_osc_counter/add_26/U1_1_5  (.A(\u_osc_counter/internal_counter [5]),
	.B(\u_osc_counter/add_26/carry [5]),
	.CO(\u_osc_counter/add_26/carry [6]),
	.S(\u_osc_counter/N9 ));
   HA1D0 \u_osc_counter/add_26/U1_1_4  (.A(\u_osc_counter/internal_counter [4]),
	.B(\u_osc_counter/add_26/carry [4]),
	.CO(\u_osc_counter/add_26/carry [5]),
	.S(\u_osc_counter/N8 ));
   HA1D0 \u_osc_counter/add_26/U1_1_3  (.A(\u_osc_counter/internal_counter [3]),
	.B(\u_osc_counter/add_26/carry [3]),
	.CO(\u_osc_counter/add_26/carry [4]),
	.S(\u_osc_counter/N7 ));
   HA1D0 \u_osc_counter/add_26/U1_1_2  (.A(\u_osc_counter/internal_counter [2]),
	.B(\u_osc_counter/add_26/carry [2]),
	.CO(\u_osc_counter/add_26/carry [3]),
	.S(\u_osc_counter/N6 ));
   HA1D0 \u_osc_counter/add_26/U1_1_6  (.A(\u_osc_counter/internal_counter [6]),
	.B(\u_osc_counter/add_26/carry [6]),
	.CO(\u_osc_counter/add_26/carry [7]),
	.S(\u_osc_counter/N10 ));
   INR2D0 \u_loop_top/u_counter/U22  (.A1(\u_loop_top/u_counter/N4 ),
	.B1(\u_loop_top/u_counter/n1 ),
	.ZN(\u_loop_top/u_counter/N12 ));
   INR2D0 \u_loop_top/u_counter/U17  (.A1(\u_loop_top/u_counter/N11 ),
	.B1(\u_loop_top/u_counter/n1 ),
	.ZN(\u_loop_top/u_counter/N19 ));
   CKBD0 \u_loop_top/u_counter/U12  (.I(FE_ECON0_RST_N),
	.Z(\u_loop_top/u_counter/n4 ));
   INR2D0 \u_loop_top/u_counter/U11  (.A1(\u_loop_top/u_counter/N5 ),
	.B1(\u_loop_top/u_counter/n1 ),
	.ZN(\u_loop_top/u_counter/N13 ));
   INR2D0 \u_loop_top/u_counter/U10  (.A1(\u_loop_top/u_counter/N6 ),
	.B1(\u_loop_top/u_counter/n1 ),
	.ZN(\u_loop_top/u_counter/N14 ));
   INR2D0 \u_loop_top/u_counter/U9  (.A1(\u_loop_top/u_counter/N7 ),
	.B1(\u_loop_top/u_counter/n1 ),
	.ZN(\u_loop_top/u_counter/N15 ));
   INR2D0 \u_loop_top/u_counter/U8  (.A1(\u_loop_top/u_counter/N8 ),
	.B1(\u_loop_top/u_counter/n1 ),
	.ZN(\u_loop_top/u_counter/N16 ));
   INR2D0 \u_loop_top/u_counter/U7  (.A1(\u_loop_top/u_counter/N9 ),
	.B1(\u_loop_top/u_counter/n1 ),
	.ZN(\u_loop_top/u_counter/N17 ));
   NR4D0 \u_loop_top/u_counter/U6  (.A1(\u_loop_top/u_counter/n12 ),
	.A2(\u_loop_top/u_counter/n11 ),
	.A3(\u_loop_top/u_counter/n14 ),
	.A4(\u_loop_top/u_counter/n13 ),
	.ZN(\u_loop_top/u_counter/n3 ));
   NR4D0 \u_loop_top/u_counter/U5  (.A1(\u_loop_top/u_counter/n8 ),
	.A2(\u_loop_top/u_counter/n7 ),
	.A3(\u_loop_top/u_counter/n10 ),
	.A4(\u_loop_top/u_counter/n9 ),
	.ZN(\u_loop_top/u_counter/n2 ));
   CKAN2D0 \u_loop_top/u_counter/U4  (.A1(\u_loop_top/u_counter/n2 ),
	.A2(\u_loop_top/u_counter/n3 ),
	.Z(\u_loop_top/u_counter/n1 ));
   INR2D0 \u_loop_top/u_counter/U3  (.A1(\u_loop_top/u_counter/N10 ),
	.B1(\u_loop_top/u_counter/n1 ),
	.ZN(\u_loop_top/u_counter/N18 ));
   DFCNQD1 \u_loop_top/u_counter/count_reg[4]  (.CDN(\u_loop_top/u_counter/n4 ),
	.CP(CTS_10),
	.D(\u_loop_top/u_counter/N16 ),
	.Q(\u_loop_top/u_counter/count[4] ));
   CKXOR2D0 \u_loop_top/u_counter/U21  (.A1(TOTAL_COUNT[7]),
	.A2(\u_loop_top/u_counter/count[7] ),
	.Z(\u_loop_top/u_counter/n11 ));
   CKXOR2D0 \u_loop_top/u_counter/U20  (.A1(TOTAL_COUNT[6]),
	.A2(\u_loop_top/u_counter/count[6] ),
	.Z(\u_loop_top/u_counter/n12 ));
   CKXOR2D0 \u_loop_top/u_counter/U19  (.A1(TOTAL_COUNT[5]),
	.A2(\u_loop_top/u_counter/count[5] ),
	.Z(\u_loop_top/u_counter/n13 ));
   CKXOR2D0 \u_loop_top/u_counter/U18  (.A1(TOTAL_COUNT[4]),
	.A2(\u_loop_top/u_counter/count[4] ),
	.Z(\u_loop_top/u_counter/n14 ));
   CKXOR2D0 \u_loop_top/u_counter/U16  (.A1(TOTAL_COUNT[3]),
	.A2(\u_loop_top/u_counter/count[3] ),
	.Z(\u_loop_top/u_counter/n7 ));
   CKXOR2D0 \u_loop_top/u_counter/U15  (.A1(TOTAL_COUNT[2]),
	.A2(\u_loop_top/u_counter/count[2] ),
	.Z(\u_loop_top/u_counter/n8 ));
   CKXOR2D0 \u_loop_top/u_counter/U14  (.A1(TOTAL_COUNT[1]),
	.A2(\u_loop_top/u_counter/count[1] ),
	.Z(\u_loop_top/u_counter/n9 ));
   CKXOR2D0 \u_loop_top/u_counter/U13  (.A1(TOTAL_COUNT[0]),
	.A2(\u_loop_top/u_counter/count[0] ),
	.Z(\u_loop_top/u_counter/n10 ));
   DFCNQD1 \u_loop_top/u_counter/count_reg[7]  (.CDN(\u_loop_top/u_counter/n4 ),
	.CP(CTS_10),
	.D(\u_loop_top/u_counter/N19 ),
	.Q(\u_loop_top/u_counter/count[7] ));
   DFCNQD1 \u_loop_top/u_counter/count_reg[6]  (.CDN(\u_loop_top/u_counter/n4 ),
	.CP(CTS_10),
	.D(\u_loop_top/u_counter/N18 ),
	.Q(\u_loop_top/u_counter/count[6] ));
   DFCNQD1 \u_loop_top/u_counter/count_reg[5]  (.CDN(\u_loop_top/u_counter/n4 ),
	.CP(CTS_10),
	.D(\u_loop_top/u_counter/N17 ),
	.Q(\u_loop_top/u_counter/count[5] ));
   DFCNQD1 \u_loop_top/u_counter/count_reg[3]  (.CDN(\u_loop_top/u_counter/n4 ),
	.CP(CTS_10),
	.D(\u_loop_top/u_counter/N15 ),
	.Q(\u_loop_top/u_counter/count[3] ));
   DFCNQD1 \u_loop_top/u_counter/count_reg[2]  (.CDN(\u_loop_top/u_counter/n4 ),
	.CP(CTS_10),
	.D(\u_loop_top/u_counter/N14 ),
	.Q(\u_loop_top/u_counter/count[2] ));
   DFCNQD1 \u_loop_top/u_counter/count_reg[1]  (.CDN(\u_loop_top/u_counter/n4 ),
	.CP(CTS_10),
	.D(\u_loop_top/u_counter/N13 ),
	.Q(\u_loop_top/u_counter/count[1] ));
   DFCNQD1 \u_loop_top/u_counter/count_done_reg  (.CDN(\u_loop_top/u_counter/n4 ),
	.CP(CTS_10),
	.D(\u_loop_top/u_counter/n1 ),
	.Q(COUNT_DONE));
   DFCNQD1 \u_loop_top/u_counter/count_reg[0]  (.CDN(\u_loop_top/u_counter/n4 ),
	.CP(CTS_10),
	.D(\u_loop_top/u_counter/N12 ),
	.Q(\u_loop_top/u_counter/count[0] ));
   CKXOR2D0 \u_loop_top/u_counter/add_22/U6  (.A1(\u_loop_top/u_counter/add_22/carry [7]),
	.A2(\u_loop_top/u_counter/count[7] ),
	.Z(\u_loop_top/u_counter/N11 ));
   CKND0 \u_loop_top/u_counter/add_22/U5  (.I(\u_loop_top/u_counter/count[0] ),
	.ZN(\u_loop_top/u_counter/N4 ));
   CKXOR2D0 \u_loop_top/u_counter/add_22/U4  (.A1(\u_loop_top/u_counter/count[1] ),
	.A2(\u_loop_top/u_counter/count[0] ),
	.Z(\u_loop_top/u_counter/N5 ));
   CKXOR2D0 \u_loop_top/u_counter/add_22/U3  (.A1(\u_loop_top/u_counter/count[4] ),
	.A2(\u_loop_top/u_counter/add_22/carry [4]),
	.Z(\u_loop_top/u_counter/N8 ));
   CKAN2D0 \u_loop_top/u_counter/add_22/U2  (.A1(\u_loop_top/u_counter/count[1] ),
	.A2(\u_loop_top/u_counter/count[0] ),
	.Z(\u_loop_top/u_counter/add_22/n2 ));
   CKAN2D0 \u_loop_top/u_counter/add_22/U1  (.A1(\u_loop_top/u_counter/count[4] ),
	.A2(\u_loop_top/u_counter/add_22/carry [4]),
	.Z(\u_loop_top/u_counter/add_22/n1 ));
   HA1D0 \u_loop_top/u_counter/add_22/U1_1_5  (.A(\u_loop_top/u_counter/count[5] ),
	.B(\u_loop_top/u_counter/add_22/n1 ),
	.CO(\u_loop_top/u_counter/add_22/carry [6]),
	.S(\u_loop_top/u_counter/N9 ));
   HA1D0 \u_loop_top/u_counter/add_22/U1_1_3  (.A(\u_loop_top/u_counter/count[3] ),
	.B(\u_loop_top/u_counter/add_22/carry [3]),
	.CO(\u_loop_top/u_counter/add_22/carry [4]),
	.S(\u_loop_top/u_counter/N7 ));
   HA1D0 \u_loop_top/u_counter/add_22/U1_1_2  (.A(\u_loop_top/u_counter/count[2] ),
	.B(\u_loop_top/u_counter/add_22/n2 ),
	.CO(\u_loop_top/u_counter/add_22/carry [3]),
	.S(\u_loop_top/u_counter/N6 ));
   HA1D0 \u_loop_top/u_counter/add_22/U1_1_6  (.A(\u_loop_top/u_counter/count[6] ),
	.B(\u_loop_top/u_counter/add_22/carry [6]),
	.CO(\u_loop_top/u_counter/add_22/carry [7]),
	.S(\u_loop_top/u_counter/N10 ));
   MOAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U142  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n122 ),
	.B1(NO_CURRENT_SOURCE[31]),
	.B2(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [31]));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U141  (.I(CURRENT_SOURCE_ENABLE[30]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n122 ));
   AO222D0 \u_loop_top/u_up_down_counter_32b_avg/U140  (.A1(CURRENT_SOURCE_ENABLE[31]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B1(CURRENT_SOURCE_ENABLE[29]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n5 ),
	.C1(NO_CURRENT_SOURCE[30]),
	.C2(LOOP_BYPASS),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [30]));
   AO222D0 \u_loop_top/u_up_down_counter_32b_avg/U139  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.A2(CURRENT_SOURCE_ENABLE[30]),
	.B1(CURRENT_SOURCE_ENABLE[28]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n5 ),
	.C1(NO_CURRENT_SOURCE[29]),
	.C2(LOOP_BYPASS),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [29]));
   AO222D0 \u_loop_top/u_up_down_counter_32b_avg/U138  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.A2(CURRENT_SOURCE_ENABLE[29]),
	.B1(CURRENT_SOURCE_ENABLE[27]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n5 ),
	.C1(NO_CURRENT_SOURCE[28]),
	.C2(LOOP_BYPASS),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [28]));
   AO222D0 \u_loop_top/u_up_down_counter_32b_avg/U137  (.A1(CURRENT_SOURCE_ENABLE[28]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B1(CURRENT_SOURCE_ENABLE[26]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n5 ),
	.C1(NO_CURRENT_SOURCE[27]),
	.C2(\u_loop_top/u_up_down_counter_32b_avg/n12 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [27]));
   AO222D0 \u_loop_top/u_up_down_counter_32b_avg/U136  (.A1(CURRENT_SOURCE_ENABLE[27]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B1(CURRENT_SOURCE_ENABLE[25]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n5 ),
	.C1(NO_CURRENT_SOURCE[26]),
	.C2(\u_loop_top/u_up_down_counter_32b_avg/n12 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [26]));
   AO222D0 \u_loop_top/u_up_down_counter_32b_avg/U135  (.A1(CURRENT_SOURCE_ENABLE[26]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B1(CURRENT_SOURCE_ENABLE[24]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n5 ),
	.C1(NO_CURRENT_SOURCE[25]),
	.C2(\u_loop_top/u_up_down_counter_32b_avg/n12 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [25]));
   AO222D0 \u_loop_top/u_up_down_counter_32b_avg/U134  (.A1(CURRENT_SOURCE_ENABLE[25]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B1(CURRENT_SOURCE_ENABLE[23]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n5 ),
	.C1(NO_CURRENT_SOURCE[24]),
	.C2(\u_loop_top/u_up_down_counter_32b_avg/n12 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [24]));
   AO222D0 \u_loop_top/u_up_down_counter_32b_avg/U133  (.A1(CURRENT_SOURCE_ENABLE[24]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B1(CURRENT_SOURCE_ENABLE[22]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n5 ),
	.C1(NO_CURRENT_SOURCE[23]),
	.C2(\u_loop_top/u_up_down_counter_32b_avg/n12 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [23]));
   AO222D0 \u_loop_top/u_up_down_counter_32b_avg/U132  (.A1(CURRENT_SOURCE_ENABLE[23]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B1(CURRENT_SOURCE_ENABLE[21]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n121 ),
	.C1(NO_CURRENT_SOURCE[22]),
	.C2(\u_loop_top/u_up_down_counter_32b_avg/n12 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [22]));
   OAI211D0 \u_loop_top/u_up_down_counter_32b_avg/U131  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n11 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n119 ),
	.B(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n118 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n46 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U130  (.A1(CURRENT_SOURCE_ENABLE[0]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.B1(NO_CURRENT_SOURCE[0]),
	.B2(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n118 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U129  (.A1(CURRENT_SOURCE_ENABLE[1]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.B1(NO_CURRENT_SOURCE[1]),
	.B2(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n114 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U128  (.I(CURRENT_SOURCE_ENABLE[0]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n116 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U127  (.A1(CURRENT_SOURCE_ENABLE[2]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.B1(NO_CURRENT_SOURCE[2]),
	.B2(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n112 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U126  (.I(CURRENT_SOURCE_ENABLE[1]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n119 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U125  (.A1(CURRENT_SOURCE_ENABLE[3]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.B1(NO_CURRENT_SOURCE[3]),
	.B2(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n110 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U124  (.I(CURRENT_SOURCE_ENABLE[2]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n115 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U123  (.A1(CURRENT_SOURCE_ENABLE[4]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.B1(NO_CURRENT_SOURCE[4]),
	.B2(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n108 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U122  (.I(CURRENT_SOURCE_ENABLE[3]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n113 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U121  (.A1(CURRENT_SOURCE_ENABLE[5]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.B1(NO_CURRENT_SOURCE[5]),
	.B2(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n106 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U120  (.I(CURRENT_SOURCE_ENABLE[4]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n111 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U119  (.I(CURRENT_SOURCE_ENABLE[5]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n109 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U118  (.A1(CURRENT_SOURCE_ENABLE[7]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.B1(NO_CURRENT_SOURCE[7]),
	.B2(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n102 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U117  (.I(CURRENT_SOURCE_ENABLE[6]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n107 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U116  (.A1(CURRENT_SOURCE_ENABLE[8]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.B1(NO_CURRENT_SOURCE[8]),
	.B2(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n100 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U115  (.I(CURRENT_SOURCE_ENABLE[7]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n105 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U114  (.A1(CURRENT_SOURCE_ENABLE[9]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.B1(NO_CURRENT_SOURCE[9]),
	.B2(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n98 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U113  (.I(CURRENT_SOURCE_ENABLE[8]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n103 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U112  (.A1(CURRENT_SOURCE_ENABLE[10]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.B1(NO_CURRENT_SOURCE[10]),
	.B2(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n96 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U111  (.I(CURRENT_SOURCE_ENABLE[9]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n101 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U110  (.A1(CURRENT_SOURCE_ENABLE[11]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.B1(NO_CURRENT_SOURCE[11]),
	.B2(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n94 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U109  (.I(CURRENT_SOURCE_ENABLE[10]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n99 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U108  (.A1(CURRENT_SOURCE_ENABLE[12]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.B1(NO_CURRENT_SOURCE[12]),
	.B2(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n92 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U107  (.I(CURRENT_SOURCE_ENABLE[11]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n97 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U106  (.A1(CURRENT_SOURCE_ENABLE[13]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.B1(NO_CURRENT_SOURCE[13]),
	.B2(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n90 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U105  (.I(CURRENT_SOURCE_ENABLE[12]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n95 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U104  (.A1(CURRENT_SOURCE_ENABLE[14]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.B1(NO_CURRENT_SOURCE[14]),
	.B2(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n88 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U103  (.I(CURRENT_SOURCE_ENABLE[15]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n89 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U102  (.I(CURRENT_SOURCE_ENABLE[13]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n93 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U101  (.A1(CURRENT_SOURCE_ENABLE[15]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.B1(NO_CURRENT_SOURCE[15]),
	.B2(LOOP_BYPASS),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n86 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U100  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/N6 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n120 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U99  (.I(CURRENT_SOURCE_ENABLE[16]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n87 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U98  (.I(CURRENT_SOURCE_ENABLE[14]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n91 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U97  (.A1(COUNTER[5]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n56 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n72 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U96  (.I(LOWER_VOLTAGE_BOUND[5]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n56 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U93  (.A1(UPPER_VOLTAGE_BOUND[7]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n79 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n47 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U92  (.A1(UPPER_VOLTAGE_BOUND[5]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n70 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n28 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U91  (.I(COUNTER[6]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n74 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U90  (.I(COUNTER[0]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n57 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U89  (.I(COUNTER[1]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n58 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U88  (.A1(UPPER_VOLTAGE_BOUND[3]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n59 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n21 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U87  (.I(COUNTER[3]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n59 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U86  (.I(COUNTER[2]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n60 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U85  (.I(COUNTER[5]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n70 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U84  (.I(COUNTER[4]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n71 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U83  (.I(COUNTER[7]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n79 ));
   CKBD0 \u_loop_top/u_up_down_counter_32b_avg/U81  (.I(LOOP_BYPASS),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n12 ));
   IND2D0 \u_loop_top/u_up_down_counter_32b_avg/U80  (.A1(UPPER_VOLTAGE_BOUND[5]),
	.B1(COUNTER[5]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n30 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U79  (.A1(LOWER_VOLTAGE_BOUND[1]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n58 ),
	.B1(LOWER_VOLTAGE_BOUND[0]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n57 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n63 ));
   OAI31D0 \u_loop_top/u_up_down_counter_32b_avg/U78  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n3 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n64 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n63 ),
	.B(\u_loop_top/u_up_down_counter_32b_avg/n62 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n65 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U77  (.I(LOWER_VOLTAGE_BOUND[7]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n66 ));
   IND3D0 \u_loop_top/u_up_down_counter_32b_avg/U76  (.A1(UPPER_VOLTAGE_BOUND[4]),
	.B1(COUNTER[4]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n28 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n29 ));
   INR2D0 \u_loop_top/u_up_down_counter_32b_avg/U75  (.A1(COUNTER[4]),
	.B1(LOWER_VOLTAGE_BOUND[4]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n68 ));
   AOI21D0 \u_loop_top/u_up_down_counter_32b_avg/U74  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n24 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n23 ),
	.B(\u_loop_top/u_up_down_counter_32b_avg/n1 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n27 ));
   AOI21D0 \u_loop_top/u_up_down_counter_32b_avg/U73  (.A1(UPPER_VOLTAGE_BOUND[4]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n71 ),
	.B(\u_loop_top/u_up_down_counter_32b_avg/n25 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n26 ));
   ND3D0 \u_loop_top/u_up_down_counter_32b_avg/U72  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n27 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n28 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n26 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n54 ));
   AOI21D0 \u_loop_top/u_up_down_counter_32b_avg/U71  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n30 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n29 ),
	.B(\u_loop_top/u_up_down_counter_32b_avg/n1 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n48 ));
   NR2D0 \u_loop_top/u_up_down_counter_32b_avg/U70  (.A1(UPPER_VOLTAGE_BOUND[6]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n74 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n49 ));
   OAI21D0 \u_loop_top/u_up_down_counter_32b_avg/U69  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n49 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n48 ),
	.B(\u_loop_top/u_up_down_counter_32b_avg/n47 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n53 ));
   OAI21D0 \u_loop_top/u_up_down_counter_32b_avg/U66  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n78 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n79 ),
	.B(LOWER_VOLTAGE_BOUND[7]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n80 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U65  (.A1(UPPER_VOLTAGE_BOUND[1]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n58 ),
	.B1(UPPER_VOLTAGE_BOUND[0]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n57 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n22 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U64  (.A1(UPPER_VOLTAGE_BOUND[1]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n58 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n19 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U63  (.A1(UPPER_VOLTAGE_BOUND[2]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n60 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n20 ));
   ND4D0 \u_loop_top/u_up_down_counter_32b_avg/U62  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n22 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n21 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n20 ),
	.A4(\u_loop_top/u_up_down_counter_32b_avg/n19 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n23 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U61  (.I(UPPER_VOLTAGE_BOUND[3]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n17 ));
   NR2D0 \u_loop_top/u_up_down_counter_32b_avg/U60  (.A1(UPPER_VOLTAGE_BOUND[2]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n60 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n18 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U59  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n18 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n21 ),
	.B1(COUNTER[3]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n17 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n24 ));
   OAI22D0 \u_loop_top/u_up_down_counter_32b_avg/U58  (.A1(LOWER_VOLTAGE_BOUND[2]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n60 ),
	.B1(LOWER_VOLTAGE_BOUND[1]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n58 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n64 ));
   AOI32D0 \u_loop_top/u_up_down_counter_32b_avg/U57  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n61 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n60 ),
	.A3(LOWER_VOLTAGE_BOUND[2]),
	.B1(LOWER_VOLTAGE_BOUND[3]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n59 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n62 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U56  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n73 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n72 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n76 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U55  (.A1(LOWER_VOLTAGE_BOUND[4]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n71 ),
	.B1(LOWER_VOLTAGE_BOUND[5]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n70 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n77 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U54  (.A1(LOWER_VOLTAGE_BOUND[6]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n74 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n75 ));
   OAI21D0 \u_loop_top/u_up_down_counter_32b_avg/U53  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n77 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n76 ),
	.B(\u_loop_top/u_up_down_counter_32b_avg/n75 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n78 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U52  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n95 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n11 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n91 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n90 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n43 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U51  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n97 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n11 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n93 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n92 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n42 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U50  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n99 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n11 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n95 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n94 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n41 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U49  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n101 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n11 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n97 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n96 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n40 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U48  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n103 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n11 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n99 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n98 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n39 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U47  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n105 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n11 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n101 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n100 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n38 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U46  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n107 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n11 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n103 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n102 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n37 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U45  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n111 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n11 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n107 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n106 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n35 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U44  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n113 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n11 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n109 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n108 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n34 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U43  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n115 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n11 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n111 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n110 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n33 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U42  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n119 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n11 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n113 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n112 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n32 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U41  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n116 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n11 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n115 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n114 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n31 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U40  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n91 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n87 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n11 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n86 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n45 ));
   OAI221D0 \u_loop_top/u_up_down_counter_32b_avg/U39  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n93 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n89 ),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n11 ),
	.C(\u_loop_top/u_up_down_counter_32b_avg/n88 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n44 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U38  (.I(COUNT_DONE),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n51 ));
   AOI31D0 \u_loop_top/u_up_down_counter_32b_avg/U36  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n54 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n53 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n52 ),
	.B(\u_loop_top/u_up_down_counter_32b_avg/n51 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n84 ));
   BUFFD1 \u_loop_top/u_up_down_counter_32b_avg/U34  (.I(FE_ECON0_RST_N),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n15 ));
   BUFFD1 \u_loop_top/u_up_down_counter_32b_avg/U33  (.I(FE_ECON0_RST_N),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n14 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U32  (.I(\u_loop_top/u_up_down_counter_32b_avg/n12 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n13 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U31  (.I(\u_loop_top/u_up_down_counter_32b_avg/n47 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n25 ));
   AO222D0 \u_loop_top/u_up_down_counter_32b_avg/U30  (.A1(CURRENT_SOURCE_ENABLE[22]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B1(CURRENT_SOURCE_ENABLE[20]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n121 ),
	.C1(NO_CURRENT_SOURCE[21]),
	.C2(\u_loop_top/u_up_down_counter_32b_avg/n12 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [21]));
   AO222D0 \u_loop_top/u_up_down_counter_32b_avg/U29  (.A1(CURRENT_SOURCE_ENABLE[21]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B1(CURRENT_SOURCE_ENABLE[19]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n121 ),
	.C1(NO_CURRENT_SOURCE[20]),
	.C2(\u_loop_top/u_up_down_counter_32b_avg/n12 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [20]));
   AO222D0 \u_loop_top/u_up_down_counter_32b_avg/U28  (.A1(CURRENT_SOURCE_ENABLE[20]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B1(CURRENT_SOURCE_ENABLE[18]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n121 ),
	.C1(NO_CURRENT_SOURCE[19]),
	.C2(\u_loop_top/u_up_down_counter_32b_avg/n12 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [19]));
   AO222D0 \u_loop_top/u_up_down_counter_32b_avg/U27  (.A1(CURRENT_SOURCE_ENABLE[19]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B1(CURRENT_SOURCE_ENABLE[17]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n121 ),
	.C1(NO_CURRENT_SOURCE[18]),
	.C2(\u_loop_top/u_up_down_counter_32b_avg/n12 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [18]));
   AO222D0 \u_loop_top/u_up_down_counter_32b_avg/U26  (.A1(CURRENT_SOURCE_ENABLE[18]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B1(CURRENT_SOURCE_ENABLE[16]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n121 ),
	.C1(NO_CURRENT_SOURCE[17]),
	.C2(\u_loop_top/u_up_down_counter_32b_avg/n12 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [17]));
   AO222D0 \u_loop_top/u_up_down_counter_32b_avg/U25  (.A1(CURRENT_SOURCE_ENABLE[17]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.B1(CURRENT_SOURCE_ENABLE[15]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n121 ),
	.C1(NO_CURRENT_SOURCE[16]),
	.C2(\u_loop_top/u_up_down_counter_32b_avg/n12 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [16]));
   BUFFD1 \u_loop_top/u_up_down_counter_32b_avg/U23  (.I(\u_loop_top/u_up_down_counter_32b_avg/n120 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n11 ));
   AOI22D0 \u_loop_top/u_up_down_counter_32b_avg/U22  (.A1(CURRENT_SOURCE_ENABLE[6]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.B1(NO_CURRENT_SOURCE[6]),
	.B2(\u_loop_top/u_up_down_counter_32b_avg/n12 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n104 ));
   ND3D0 \u_loop_top/u_up_down_counter_32b_avg/U21  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n7 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n8 ),
	.A3(\u_loop_top/u_up_down_counter_32b_avg/n104 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n36 ));
   OR2D0 \u_loop_top/u_up_down_counter_32b_avg/U20  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n109 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n7 ));
   CKND2 \u_loop_top/u_up_down_counter_32b_avg/U19  (.I(\u_loop_top/u_up_down_counter_32b_avg/n117 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n6 ));
   OR2D0 \u_loop_top/u_up_down_counter_32b_avg/U18  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n11 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n105 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n8 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U17  (.I(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n121 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U16  (.I(\u_loop_top/u_up_down_counter_32b_avg/n123 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n5 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U15  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n9 ),
	.A2(COUNTER[3]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n61 ));
   OAI21D0 \u_loop_top/u_up_down_counter_32b_avg/U14  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n83 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n82 ),
	.B(COUNT_DONE),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n4 ));
   IND2D2 \u_loop_top/u_up_down_counter_32b_avg/U13  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n4 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n13 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n123 ));
   OAI21D0 \u_loop_top/u_up_down_counter_32b_avg/U12  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n82 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n83 ),
	.B(COUNT_DONE),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n85 ));
   CKAN2D0 \u_loop_top/u_up_down_counter_32b_avg/U11  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n9 ),
	.A2(COUNTER[3]),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n3 ));
   CKND2D0 \u_loop_top/u_up_down_counter_32b_avg/U10  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n85 ),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n13 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n2 ));
   CKAN2D0 \u_loop_top/u_up_down_counter_32b_avg/U9  (.A1(UPPER_VOLTAGE_BOUND[6]),
	.A2(\u_loop_top/u_up_down_counter_32b_avg/n74 ),
	.Z(\u_loop_top/u_up_down_counter_32b_avg/n1 ));
   IND2D0 \u_loop_top/u_up_down_counter_32b_avg/U8  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n84 ),
	.B1(\u_loop_top/u_up_down_counter_32b_avg/n10 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/N6 ));
   CKND0 \u_loop_top/u_up_down_counter_32b_avg/U7  (.I(LOWER_VOLTAGE_BOUND[3]),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n9 ));
   CKND2 \u_loop_top/u_up_down_counter_32b_avg/U6  (.I(\u_loop_top/u_up_down_counter_32b_avg/n2 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n10 ));
   IOA21D0 \u_loop_top/u_up_down_counter_32b_avg/U5  (.A1(\u_loop_top/u_up_down_counter_32b_avg/n66 ),
	.A2(COUNTER[7]),
	.B(\u_loop_top/u_up_down_counter_32b_avg/n65 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n67 ));
   CKND1 \u_loop_top/u_up_down_counter_32b_avg/U3  (.I(\u_loop_top/u_up_down_counter_32b_avg/N6 ),
	.ZN(\u_loop_top/u_up_down_counter_32b_avg/n117 ));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[16]  (.CDN(FE_ECON0_RST_N),
	.CP(CTS_12),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [16]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n6 ),
	.Q(CURRENT_SOURCE_ENABLE[16]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[17]  (.CDN(FE_ECON0_RST_N),
	.CP(CTS_12),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [17]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n6 ),
	.Q(CURRENT_SOURCE_ENABLE[17]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[18]  (.CDN(FE_ECON0_RST_N),
	.CP(CTS_12),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [18]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n6 ),
	.Q(CURRENT_SOURCE_ENABLE[18]));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[15]  (.CP(CTS_11),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n45 ),
	.Q(CURRENT_SOURCE_ENABLE[15]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n14 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[1]  (.CP(CTS_11),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n31 ),
	.Q(CURRENT_SOURCE_ENABLE[1]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n15 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[2]  (.CP(CTS_11),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n32 ),
	.Q(CURRENT_SOURCE_ENABLE[2]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n15 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[3]  (.CP(CTS_11),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n33 ),
	.Q(CURRENT_SOURCE_ENABLE[3]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n15 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[4]  (.CP(CTS_11),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n34 ),
	.Q(CURRENT_SOURCE_ENABLE[4]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n14 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[5]  (.CP(CTS_11),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n35 ),
	.Q(CURRENT_SOURCE_ENABLE[5]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n14 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[6]  (.CP(CTS_11),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n36 ),
	.Q(CURRENT_SOURCE_ENABLE[6]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n14 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[7]  (.CP(CTS_11),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n37 ),
	.Q(CURRENT_SOURCE_ENABLE[7]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n14 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[8]  (.CP(CTS_11),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n38 ),
	.Q(CURRENT_SOURCE_ENABLE[8]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n14 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[9]  (.CP(CTS_11),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n39 ),
	.Q(CURRENT_SOURCE_ENABLE[9]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n14 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[10]  (.CP(CTS_11),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n40 ),
	.Q(CURRENT_SOURCE_ENABLE[10]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n14 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[11]  (.CP(CTS_11),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n41 ),
	.Q(CURRENT_SOURCE_ENABLE[11]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n14 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[12]  (.CP(CTS_11),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n42 ),
	.Q(CURRENT_SOURCE_ENABLE[12]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n14 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[13]  (.CP(CTS_11),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n43 ),
	.Q(CURRENT_SOURCE_ENABLE[13]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n14 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[14]  (.CP(CTS_11),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n44 ),
	.Q(CURRENT_SOURCE_ENABLE[14]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n14 ));
   DFSNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[0]  (.CP(CTS_11),
	.D(\u_loop_top/u_up_down_counter_32b_avg/n46 ),
	.Q(CURRENT_SOURCE_ENABLE[0]),
	.SDN(\u_loop_top/u_up_down_counter_32b_avg/n14 ));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[19]  (.CDN(FE_ECON0_RST_N),
	.CP(CTS_12),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [19]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n6 ),
	.Q(CURRENT_SOURCE_ENABLE[19]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[20]  (.CDN(FE_ECON0_RST_N),
	.CP(CTS_12),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [20]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n6 ),
	.Q(CURRENT_SOURCE_ENABLE[20]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[21]  (.CDN(FE_ECON0_RST_N),
	.CP(CTS_12),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [21]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n6 ),
	.Q(CURRENT_SOURCE_ENABLE[21]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[22]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n15 ),
	.CP(CTS_12),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [22]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n6 ),
	.Q(CURRENT_SOURCE_ENABLE[22]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[23]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n15 ),
	.CP(CTS_12),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [23]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n6 ),
	.Q(CURRENT_SOURCE_ENABLE[23]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[24]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n15 ),
	.CP(CTS_12),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [24]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n6 ),
	.Q(CURRENT_SOURCE_ENABLE[24]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[25]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n15 ),
	.CP(CTS_12),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [25]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n6 ),
	.Q(CURRENT_SOURCE_ENABLE[25]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[26]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n15 ),
	.CP(CTS_12),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [26]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n6 ),
	.Q(CURRENT_SOURCE_ENABLE[26]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[27]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n15 ),
	.CP(CTS_12),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [27]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n6 ),
	.Q(CURRENT_SOURCE_ENABLE[27]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[28]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n15 ),
	.CP(CTS_12),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [28]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n6 ),
	.Q(CURRENT_SOURCE_ENABLE[28]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[29]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n15 ),
	.CP(CTS_12),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [29]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n6 ),
	.Q(CURRENT_SOURCE_ENABLE[29]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[30]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n15 ),
	.CP(CTS_12),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [30]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n6 ),
	.Q(CURRENT_SOURCE_ENABLE[30]));
   EDFCNQD1 \u_loop_top/u_up_down_counter_32b_avg/OUT_COUNT_reg[31]  (.CDN(\u_loop_top/u_up_down_counter_32b_avg/n15 ),
	.CP(CTS_12),
	.D(\u_loop_top/u_up_down_counter_32b_avg/out_count_next [31]),
	.E(\u_loop_top/u_up_down_counter_32b_avg/n6 ),
	.Q(CURRENT_SOURCE_ENABLE[31]));
endmodule

