/*
###############################################################
#  Generated by:      Cadence Innovus 16.12-s051_1
#  OS:                Linux x86_64(Host ID ecegrid-thin7.ecn.purdue.edu)
#  Generated on:      Tue Apr  7 20:11:50 2020
#  Design:            loop_top
#  Command:           saveNetlist /home/sparclab/a/ghosh69/march_20_tapeout/current_source_controller/logs/loop_top_power.gate.v -includepowerground -excludeLeafCell
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : L-2016.03-SP2
// Date      : Mon Apr  6 18:42:53 2020
/////////////////////////////////////////////////////////////
module loop_top (
	CLK, 
	RST_N, 
	LOOP_BYPASS, 
	COUNT_DONE, 
	TOTAL_COUNT, 
	COUNTER, 
	LOWER_VOLTAGE_BOUND, 
	UPPER_VOLTAGE_BOUND, 
	CURRENT_SOURCE_ENABLE, 
	VDD, 
	VSS);
   input CLK;
   input RST_N;
   input LOOP_BYPASS;
   output COUNT_DONE;
   input [12:0] TOTAL_COUNT;
   input [15:0] COUNTER;
   input [15:0] LOWER_VOLTAGE_BOUND;
   input [15:0] UPPER_VOLTAGE_BOUND;
   output [31:0] CURRENT_SOURCE_ENABLE;
   inout VDD;
   inout VSS;

   // Internal wires
   wire CTS_12;
   wire CTS_11;
   wire CTS_10;
   wire \u_counter/n28 ;
   wire \u_counter/n27 ;
   wire \u_counter/n26 ;
   wire \u_counter/n25 ;
   wire \u_counter/n24 ;
   wire \u_counter/n23 ;
   wire \u_counter/n22 ;
   wire \u_counter/n21 ;
   wire \u_counter/n20 ;
   wire \u_counter/n19 ;
   wire \u_counter/n18 ;
   wire \u_counter/n17 ;
   wire \u_counter/n16 ;
   wire \u_counter/n15 ;
   wire \u_counter/n13 ;
   wire \u_counter/n11 ;
   wire \u_counter/n10 ;
   wire \u_counter/n9 ;
   wire \u_counter/n8 ;
   wire \u_counter/n7 ;
   wire \u_counter/n6 ;
   wire \u_counter/n5 ;
   wire \u_counter/n4 ;
   wire \u_counter/n3 ;
   wire \u_counter/n2 ;
   wire \u_counter/n1 ;
   wire \u_counter/N29 ;
   wire \u_counter/N28 ;
   wire \u_counter/N27 ;
   wire \u_counter/N26 ;
   wire \u_counter/N25 ;
   wire \u_counter/N24 ;
   wire \u_counter/N23 ;
   wire \u_counter/N22 ;
   wire \u_counter/N21 ;
   wire \u_counter/N20 ;
   wire \u_counter/N19 ;
   wire \u_counter/N18 ;
   wire \u_counter/N17 ;
   wire \u_counter/N16 ;
   wire \u_counter/N15 ;
   wire \u_counter/N14 ;
   wire \u_counter/N13 ;
   wire \u_counter/N12 ;
   wire \u_counter/N11 ;
   wire \u_counter/N10 ;
   wire \u_counter/N9 ;
   wire \u_counter/N8 ;
   wire \u_counter/N7 ;
   wire \u_counter/N6 ;
   wire \u_counter/N5 ;
   wire \u_counter/N4 ;
   wire \u_counter/N2 ;
   wire \u_counter/count[0] ;
   wire \u_counter/count[1] ;
   wire \u_counter/count[2] ;
   wire \u_counter/count[3] ;
   wire \u_counter/count[4] ;
   wire \u_counter/count[5] ;
   wire \u_counter/count[6] ;
   wire \u_counter/count[7] ;
   wire \u_counter/count[8] ;
   wire \u_counter/count[9] ;
   wire \u_counter/count[10] ;
   wire \u_counter/count[11] ;
   wire \u_counter/count[12] ;
   wire \u_counter/add_22/n75 ;
   wire \u_counter/add_22/n74 ;
   wire \u_counter/add_22/n73 ;
   wire \u_counter/add_22/n72 ;
   wire \u_counter/add_22/n38 ;
   wire \u_counter/add_22/n37 ;
   wire \u_counter/add_22/n31 ;
   wire \u_counter/add_22/n30 ;
   wire \u_counter/add_22/n29 ;
   wire \u_counter/add_22/n28 ;
   wire \u_counter/add_22/n22 ;
   wire \u_counter/add_22/n21 ;
   wire \u_counter/add_22/n13 ;
   wire \u_counter/add_22/n12 ;
   wire \u_counter/add_22/n11 ;
   wire \u_counter/add_22/n9 ;
   wire \u_counter/add_22/n8 ;
   wire \u_counter/add_22/n7 ;
   wire \u_counter/add_22/n3 ;
   wire \u_counter/add_22/n2 ;
   wire \u_counter/add_22/n1 ;
   wire \u_up_down_counter_32b_avg/n218 ;
   wire \u_up_down_counter_32b_avg/n216 ;
   wire \u_up_down_counter_32b_avg/n215 ;
   wire \u_up_down_counter_32b_avg/n214 ;
   wire \u_up_down_counter_32b_avg/n213 ;
   wire \u_up_down_counter_32b_avg/n212 ;
   wire \u_up_down_counter_32b_avg/n211 ;
   wire \u_up_down_counter_32b_avg/n210 ;
   wire \u_up_down_counter_32b_avg/n209 ;
   wire \u_up_down_counter_32b_avg/n208 ;
   wire \u_up_down_counter_32b_avg/n207 ;
   wire \u_up_down_counter_32b_avg/n206 ;
   wire \u_up_down_counter_32b_avg/n205 ;
   wire \u_up_down_counter_32b_avg/n204 ;
   wire \u_up_down_counter_32b_avg/n203 ;
   wire \u_up_down_counter_32b_avg/n202 ;
   wire \u_up_down_counter_32b_avg/n201 ;
   wire \u_up_down_counter_32b_avg/n200 ;
   wire \u_up_down_counter_32b_avg/n199 ;
   wire \u_up_down_counter_32b_avg/n198 ;
   wire \u_up_down_counter_32b_avg/n197 ;
   wire \u_up_down_counter_32b_avg/n195 ;
   wire \u_up_down_counter_32b_avg/n194 ;
   wire \u_up_down_counter_32b_avg/n192 ;
   wire \u_up_down_counter_32b_avg/n191 ;
   wire \u_up_down_counter_32b_avg/n190 ;
   wire \u_up_down_counter_32b_avg/n189 ;
   wire \u_up_down_counter_32b_avg/n188 ;
   wire \u_up_down_counter_32b_avg/n187 ;
   wire \u_up_down_counter_32b_avg/n186 ;
   wire \u_up_down_counter_32b_avg/n185 ;
   wire \u_up_down_counter_32b_avg/n184 ;
   wire \u_up_down_counter_32b_avg/n183 ;
   wire \u_up_down_counter_32b_avg/n181 ;
   wire \u_up_down_counter_32b_avg/n180 ;
   wire \u_up_down_counter_32b_avg/n179 ;
   wire \u_up_down_counter_32b_avg/n178 ;
   wire \u_up_down_counter_32b_avg/n177 ;
   wire \u_up_down_counter_32b_avg/n176 ;
   wire \u_up_down_counter_32b_avg/n175 ;
   wire \u_up_down_counter_32b_avg/n174 ;
   wire \u_up_down_counter_32b_avg/n173 ;
   wire \u_up_down_counter_32b_avg/n172 ;
   wire \u_up_down_counter_32b_avg/n171 ;
   wire \u_up_down_counter_32b_avg/n170 ;
   wire \u_up_down_counter_32b_avg/n169 ;
   wire \u_up_down_counter_32b_avg/n168 ;
   wire \u_up_down_counter_32b_avg/n167 ;
   wire \u_up_down_counter_32b_avg/n166 ;
   wire \u_up_down_counter_32b_avg/n165 ;
   wire \u_up_down_counter_32b_avg/n164 ;
   wire \u_up_down_counter_32b_avg/n163 ;
   wire \u_up_down_counter_32b_avg/n162 ;
   wire \u_up_down_counter_32b_avg/n161 ;
   wire \u_up_down_counter_32b_avg/n160 ;
   wire \u_up_down_counter_32b_avg/n159 ;
   wire \u_up_down_counter_32b_avg/n158 ;
   wire \u_up_down_counter_32b_avg/n157 ;
   wire \u_up_down_counter_32b_avg/n156 ;
   wire \u_up_down_counter_32b_avg/n154 ;
   wire \u_up_down_counter_32b_avg/n153 ;
   wire \u_up_down_counter_32b_avg/n152 ;
   wire \u_up_down_counter_32b_avg/n151 ;
   wire \u_up_down_counter_32b_avg/n150 ;
   wire \u_up_down_counter_32b_avg/n149 ;
   wire \u_up_down_counter_32b_avg/n147 ;
   wire \u_up_down_counter_32b_avg/n146 ;
   wire \u_up_down_counter_32b_avg/n145 ;
   wire \u_up_down_counter_32b_avg/n144 ;
   wire \u_up_down_counter_32b_avg/n143 ;
   wire \u_up_down_counter_32b_avg/n142 ;
   wire \u_up_down_counter_32b_avg/n141 ;
   wire \u_up_down_counter_32b_avg/n140 ;
   wire \u_up_down_counter_32b_avg/n139 ;
   wire \u_up_down_counter_32b_avg/n138 ;
   wire \u_up_down_counter_32b_avg/n137 ;
   wire \u_up_down_counter_32b_avg/n136 ;
   wire \u_up_down_counter_32b_avg/n135 ;
   wire \u_up_down_counter_32b_avg/n134 ;
   wire \u_up_down_counter_32b_avg/n133 ;
   wire \u_up_down_counter_32b_avg/n132 ;
   wire \u_up_down_counter_32b_avg/n131 ;
   wire \u_up_down_counter_32b_avg/n129 ;
   wire \u_up_down_counter_32b_avg/n128 ;
   wire \u_up_down_counter_32b_avg/n127 ;
   wire \u_up_down_counter_32b_avg/n126 ;
   wire \u_up_down_counter_32b_avg/n125 ;
   wire \u_up_down_counter_32b_avg/n124 ;
   wire \u_up_down_counter_32b_avg/n123 ;
   wire \u_up_down_counter_32b_avg/n122 ;
   wire \u_up_down_counter_32b_avg/n121 ;
   wire \u_up_down_counter_32b_avg/n120 ;
   wire \u_up_down_counter_32b_avg/n119 ;
   wire \u_up_down_counter_32b_avg/n118 ;
   wire \u_up_down_counter_32b_avg/n117 ;
   wire \u_up_down_counter_32b_avg/n116 ;
   wire \u_up_down_counter_32b_avg/n115 ;
   wire \u_up_down_counter_32b_avg/n112 ;
   wire \u_up_down_counter_32b_avg/n111 ;
   wire \u_up_down_counter_32b_avg/n110 ;
   wire \u_up_down_counter_32b_avg/n109 ;
   wire \u_up_down_counter_32b_avg/n108 ;
   wire \u_up_down_counter_32b_avg/n107 ;
   wire \u_up_down_counter_32b_avg/n106 ;
   wire \u_up_down_counter_32b_avg/n105 ;
   wire \u_up_down_counter_32b_avg/n104 ;
   wire \u_up_down_counter_32b_avg/n103 ;
   wire \u_up_down_counter_32b_avg/n102 ;
   wire \u_up_down_counter_32b_avg/n101 ;
   wire \u_up_down_counter_32b_avg/n100 ;
   wire \u_up_down_counter_32b_avg/n99 ;
   wire \u_up_down_counter_32b_avg/n98 ;
   wire \u_up_down_counter_32b_avg/n97 ;
   wire \u_up_down_counter_32b_avg/n96 ;
   wire \u_up_down_counter_32b_avg/n95 ;
   wire \u_up_down_counter_32b_avg/n94 ;
   wire \u_up_down_counter_32b_avg/n93 ;
   wire \u_up_down_counter_32b_avg/n92 ;
   wire \u_up_down_counter_32b_avg/n91 ;
   wire \u_up_down_counter_32b_avg/n90 ;
   wire \u_up_down_counter_32b_avg/n89 ;
   wire \u_up_down_counter_32b_avg/n88 ;
   wire \u_up_down_counter_32b_avg/n86 ;
   wire \u_up_down_counter_32b_avg/n85 ;
   wire \u_up_down_counter_32b_avg/n84 ;
   wire \u_up_down_counter_32b_avg/n83 ;
   wire \u_up_down_counter_32b_avg/n82 ;
   wire \u_up_down_counter_32b_avg/n81 ;
   wire \u_up_down_counter_32b_avg/n80 ;
   wire \u_up_down_counter_32b_avg/n79 ;
   wire \u_up_down_counter_32b_avg/n78 ;
   wire \u_up_down_counter_32b_avg/n77 ;
   wire \u_up_down_counter_32b_avg/n74 ;
   wire \u_up_down_counter_32b_avg/n73 ;
   wire \u_up_down_counter_32b_avg/n70 ;
   wire \u_up_down_counter_32b_avg/n69 ;
   wire \u_up_down_counter_32b_avg/n68 ;
   wire \u_up_down_counter_32b_avg/n67 ;
   wire \u_up_down_counter_32b_avg/n66 ;
   wire \u_up_down_counter_32b_avg/n64 ;
   wire \u_up_down_counter_32b_avg/n63 ;
   wire \u_up_down_counter_32b_avg/n62 ;
   wire \u_up_down_counter_32b_avg/n60 ;
   wire \u_up_down_counter_32b_avg/n59 ;
   wire \u_up_down_counter_32b_avg/n58 ;
   wire \u_up_down_counter_32b_avg/n57 ;
   wire \u_up_down_counter_32b_avg/n56 ;
   wire \u_up_down_counter_32b_avg/n55 ;
   wire \u_up_down_counter_32b_avg/n54 ;
   wire \u_up_down_counter_32b_avg/n53 ;
   wire \u_up_down_counter_32b_avg/n52 ;
   wire \u_up_down_counter_32b_avg/n51 ;
   wire \u_up_down_counter_32b_avg/n50 ;
   wire \u_up_down_counter_32b_avg/n49 ;
   wire \u_up_down_counter_32b_avg/n32 ;
   wire \u_up_down_counter_32b_avg/n31 ;
   wire \u_up_down_counter_32b_avg/n30 ;
   wire \u_up_down_counter_32b_avg/n29 ;
   wire \u_up_down_counter_32b_avg/n28 ;
   wire \u_up_down_counter_32b_avg/n27 ;
   wire \u_up_down_counter_32b_avg/n26 ;
   wire \u_up_down_counter_32b_avg/n25 ;
   wire \u_up_down_counter_32b_avg/n24 ;
   wire \u_up_down_counter_32b_avg/n23 ;
   wire \u_up_down_counter_32b_avg/n22 ;
   wire \u_up_down_counter_32b_avg/n21 ;
   wire \u_up_down_counter_32b_avg/n20 ;
   wire \u_up_down_counter_32b_avg/n19 ;
   wire \u_up_down_counter_32b_avg/n18 ;
   wire \u_up_down_counter_32b_avg/n17 ;
   wire \u_up_down_counter_32b_avg/n16 ;
   wire \u_up_down_counter_32b_avg/n15 ;
   wire \u_up_down_counter_32b_avg/n14 ;
   wire \u_up_down_counter_32b_avg/n13 ;
   wire \u_up_down_counter_32b_avg/n12 ;
   wire \u_up_down_counter_32b_avg/n11 ;
   wire \u_up_down_counter_32b_avg/n10 ;
   wire \u_up_down_counter_32b_avg/n9 ;
   wire \u_up_down_counter_32b_avg/n8 ;
   wire \u_up_down_counter_32b_avg/n7 ;
   wire \u_up_down_counter_32b_avg/n6 ;
   wire \u_up_down_counter_32b_avg/n5 ;
   wire \u_up_down_counter_32b_avg/n4 ;
   wire \u_up_down_counter_32b_avg/n3 ;
   wire \u_up_down_counter_32b_avg/n2 ;
   wire \u_up_down_counter_32b_avg/n1 ;
   wire \u_up_down_counter_32b_avg/n48 ;
   wire \u_up_down_counter_32b_avg/n47 ;
   wire \u_up_down_counter_32b_avg/n46 ;
   wire \u_up_down_counter_32b_avg/n45 ;
   wire \u_up_down_counter_32b_avg/n44 ;
   wire \u_up_down_counter_32b_avg/n43 ;
   wire \u_up_down_counter_32b_avg/n42 ;
   wire \u_up_down_counter_32b_avg/n41 ;
   wire \u_up_down_counter_32b_avg/n40 ;
   wire \u_up_down_counter_32b_avg/n39 ;
   wire \u_up_down_counter_32b_avg/n38 ;
   wire \u_up_down_counter_32b_avg/n37 ;
   wire \u_up_down_counter_32b_avg/n36 ;
   wire \u_up_down_counter_32b_avg/n35 ;
   wire \u_up_down_counter_32b_avg/n34 ;
   wire \u_up_down_counter_32b_avg/n33 ;
   wire [31:0] \u_up_down_counter_32b_avg/out_count_next ;

   // Module instantiations
   CKBD4 CTS_ccl_BUF_CLK_G0_L1_3 (
	.I(CLK),
	.Z(CTS_12), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD4 CTS_ccl_BUF_CLK_G0_L1_2 (
	.I(CLK),
	.Z(CTS_11), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD4 CTS_ccl_BUF_CLK_G0_L1_1 (
	.I(CLK),
	.Z(CTS_10), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D0 FE_RC_8_0 (
	.A1(LOWER_VOLTAGE_BOUND[13]),
	.B1(COUNTER[13]),
	.ZN(\u_up_down_counter_32b_avg/n9 ), 
	.VSS(VSS), 
	.VDD(VDD));
   ND4D0 FE_RC_7_0 (
	.A1(\u_up_down_counter_32b_avg/n11 ),
	.A2(\u_up_down_counter_32b_avg/n12 ),
	.A3(\u_up_down_counter_32b_avg/n10 ),
	.A4(\u_up_down_counter_32b_avg/n175 ),
	.ZN(\u_up_down_counter_32b_avg/n34 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D0 FE_RC_6_0 (
	.A1(\u_up_down_counter_32b_avg/n175 ),
	.B1(\u_up_down_counter_32b_avg/n53 ),
	.ZN(\u_up_down_counter_32b_avg/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   IND4D0 FE_RC_5_0 (
	.A1(\u_up_down_counter_32b_avg/n5 ),
	.B1(\u_up_down_counter_32b_avg/n63 ),
	.B2(\u_up_down_counter_32b_avg/n4 ),
	.B3(\u_up_down_counter_32b_avg/n115 ),
	.ZN(\u_up_down_counter_32b_avg/n116 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI32D0 FE_RC_4_0 (
	.A1(COUNTER[14]),
	.A2(\u_up_down_counter_32b_avg/n74 ),
	.A3(\u_up_down_counter_32b_avg/n73 ),
	.B1(\u_up_down_counter_32b_avg/n54 ),
	.B2(\u_up_down_counter_32b_avg/n77 ),
	.ZN(\u_up_down_counter_32b_avg/n121 ), 
	.VSS(VSS), 
	.VDD(VDD));
   IND4D0 FE_RC_3_0 (
	.A1(\u_counter/add_22/n22 ),
	.B1(\u_counter/count[6] ),
	.B2(\u_counter/count[7] ),
	.B3(\u_counter/add_22/n30 ),
	.ZN(\u_counter/add_22/n13 ), 
	.VSS(VSS), 
	.VDD(VDD));
   IND2D1 FE_RC_2_0 (
	.A1(UPPER_VOLTAGE_BOUND[11]),
	.B1(COUNTER[11]),
	.ZN(\u_up_down_counter_32b_avg/n152 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D0 FE_RC_1_0 (
	.A1(COUNTER[14]),
	.B1(UPPER_VOLTAGE_BOUND[14]),
	.ZN(\u_up_down_counter_32b_avg/n18 ), 
	.VSS(VSS), 
	.VDD(VDD));
   IND2D0 FE_RC_0_0 (
	.A1(COUNTER[12]),
	.B1(LOWER_VOLTAGE_BOUND[12]),
	.ZN(\u_up_down_counter_32b_avg/n51 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_counter/U44  (
	.I(\u_counter/n28 ),
	.ZN(\u_counter/N2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \u_counter/U43  (
	.A1(\u_counter/N4 ),
	.A2(\u_counter/n28 ),
	.Z(\u_counter/N17 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \u_counter/U42  (
	.A1(\u_counter/N16 ),
	.A2(\u_counter/n28 ),
	.Z(\u_counter/N29 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \u_counter/U41  (
	.A1(\u_counter/N8 ),
	.A2(\u_counter/n28 ),
	.Z(\u_counter/N21 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \u_counter/U40  (
	.A1(\u_counter/N12 ),
	.A2(\u_counter/n28 ),
	.Z(\u_counter/N25 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \u_counter/U39  (
	.A1(\u_counter/N10 ),
	.A2(\u_counter/n28 ),
	.Z(\u_counter/N23 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \u_counter/U38  (
	.A1(\u_counter/N7 ),
	.A2(\u_counter/n28 ),
	.Z(\u_counter/N20 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \u_counter/U37  (
	.A1(\u_counter/N15 ),
	.A2(\u_counter/n28 ),
	.Z(\u_counter/N28 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \u_counter/U36  (
	.A1(\u_counter/N14 ),
	.A2(\u_counter/n28 ),
	.Z(\u_counter/N27 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \u_counter/U35  (
	.A1(\u_counter/N11 ),
	.A2(\u_counter/n28 ),
	.Z(\u_counter/N24 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \u_counter/U34  (
	.A1(\u_counter/N9 ),
	.A2(\u_counter/n28 ),
	.Z(\u_counter/N22 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \u_counter/U33  (
	.A1(\u_counter/N13 ),
	.A2(\u_counter/n28 ),
	.Z(\u_counter/N26 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \u_counter/U32  (
	.A1(\u_counter/N5 ),
	.A2(\u_counter/n28 ),
	.Z(\u_counter/N18 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \u_counter/U31  (
	.A1(\u_counter/N6 ),
	.A2(\u_counter/n28 ),
	.Z(\u_counter/N19 ), 
	.VSS(VSS), 
	.VDD(VDD));
   ND3D0 \u_counter/U30  (
	.A1(\u_counter/n23 ),
	.A2(\u_counter/n22 ),
	.A3(\u_counter/n21 ),
	.ZN(\u_counter/n24 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/U29  (
	.A1(TOTAL_COUNT[3]),
	.A2(\u_counter/n20 ),
	.Z(\u_counter/n21 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_counter/U28  (
	.I(\u_counter/count[3] ),
	.ZN(\u_counter/n20 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/U27  (
	.A1(TOTAL_COUNT[12]),
	.A2(\u_counter/n19 ),
	.Z(\u_counter/n22 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_counter/U26  (
	.I(\u_counter/count[12] ),
	.ZN(\u_counter/n19 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/U25  (
	.A1(TOTAL_COUNT[11]),
	.A2(\u_counter/n18 ),
	.Z(\u_counter/n23 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_counter/U24  (
	.I(\u_counter/count[11] ),
	.ZN(\u_counter/n18 ), 
	.VSS(VSS), 
	.VDD(VDD));
   ND3D0 \u_counter/U23  (
	.A1(\u_counter/n17 ),
	.A2(\u_counter/n16 ),
	.A3(\u_counter/n15 ),
	.ZN(\u_counter/n25 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/U22  (
	.A1(TOTAL_COUNT[4]),
	.A2(\u_counter/add_22/n28 ),
	.Z(\u_counter/n15 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/U20  (
	.A1(TOTAL_COUNT[6]),
	.A2(\u_counter/n13 ),
	.Z(\u_counter/n16 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_counter/U19  (
	.I(\u_counter/count[6] ),
	.ZN(\u_counter/n13 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/U18  (
	.A1(TOTAL_COUNT[8]),
	.A2(\u_counter/add_22/n11 ),
	.Z(\u_counter/n17 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR4D0 \u_counter/U16  (
	.A1(\u_counter/n11 ),
	.A2(\u_counter/n10 ),
	.A3(\u_counter/n9 ),
	.A4(\u_counter/n8 ),
	.Z(\u_counter/n26 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/U15  (
	.A1(TOTAL_COUNT[9]),
	.A2(\u_counter/count[9] ),
	.Z(\u_counter/n8 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/U14  (
	.A1(TOTAL_COUNT[1]),
	.A2(\u_counter/count[1] ),
	.Z(\u_counter/n9 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/U13  (
	.A1(TOTAL_COUNT[0]),
	.A2(\u_counter/count[0] ),
	.Z(\u_counter/n10 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/U12  (
	.A1(TOTAL_COUNT[2]),
	.A2(\u_counter/count[2] ),
	.Z(\u_counter/n11 ), 
	.VSS(VSS), 
	.VDD(VDD));
   ND3D0 \u_counter/U11  (
	.A1(\u_counter/n7 ),
	.A2(\u_counter/n6 ),
	.A3(\u_counter/n5 ),
	.ZN(\u_counter/n27 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/U10  (
	.A1(TOTAL_COUNT[10]),
	.A2(\u_counter/n4 ),
	.Z(\u_counter/n5 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_counter/U9  (
	.I(\u_counter/count[10] ),
	.ZN(\u_counter/n4 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/U8  (
	.A1(TOTAL_COUNT[5]),
	.A2(\u_counter/n3 ),
	.Z(\u_counter/n6 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_counter/U7  (
	.I(\u_counter/count[5] ),
	.ZN(\u_counter/n3 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/U6  (
	.A1(TOTAL_COUNT[7]),
	.A2(\u_counter/n2 ),
	.Z(\u_counter/n7 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_counter/U5  (
	.I(\u_counter/count[7] ),
	.ZN(\u_counter/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFFD1 \u_counter/U4  (
	.I(RST_N),
	.Z(\u_counter/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR4D0 \u_counter/U3  (
	.A1(\u_counter/n27 ),
	.A2(\u_counter/n26 ),
	.A3(\u_counter/n25 ),
	.A4(\u_counter/n24 ),
	.Z(\u_counter/n28 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \u_counter/count_reg[0]  (
	.CDN(RST_N),
	.CP(CTS_10),
	.D(\u_counter/N17 ),
	.Q(\u_counter/count[0] ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \u_counter/count_reg[1]  (
	.CDN(\u_counter/n1 ),
	.CP(CTS_12),
	.D(\u_counter/N18 ),
	.Q(\u_counter/count[1] ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \u_counter/count_reg[2]  (
	.CDN(\u_counter/n1 ),
	.CP(CTS_12),
	.D(\u_counter/N19 ),
	.Q(\u_counter/count[2] ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \u_counter/count_reg[3]  (
	.CDN(\u_counter/n1 ),
	.CP(CTS_12),
	.D(\u_counter/N20 ),
	.Q(\u_counter/count[3] ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \u_counter/count_reg[4]  (
	.CDN(\u_counter/n1 ),
	.CP(CTS_12),
	.D(\u_counter/N21 ),
	.Q(\u_counter/count[4] ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \u_counter/count_reg[5]  (
	.CDN(\u_counter/n1 ),
	.CP(CTS_12),
	.D(\u_counter/N22 ),
	.Q(\u_counter/count[5] ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \u_counter/count_reg[6]  (
	.CDN(\u_counter/n1 ),
	.CP(CTS_12),
	.D(\u_counter/N23 ),
	.Q(\u_counter/count[6] ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \u_counter/count_reg[7]  (
	.CDN(\u_counter/n1 ),
	.CP(CTS_12),
	.D(\u_counter/N24 ),
	.Q(\u_counter/count[7] ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \u_counter/count_reg[8]  (
	.CDN(\u_counter/n1 ),
	.CP(CTS_11),
	.D(\u_counter/N25 ),
	.Q(\u_counter/count[8] ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \u_counter/count_reg[9]  (
	.CDN(\u_counter/n1 ),
	.CP(CTS_11),
	.D(\u_counter/N26 ),
	.Q(\u_counter/count[9] ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \u_counter/count_reg[10]  (
	.CDN(\u_counter/n1 ),
	.CP(CTS_11),
	.D(\u_counter/N27 ),
	.Q(\u_counter/count[10] ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \u_counter/count_reg[11]  (
	.CDN(\u_counter/n1 ),
	.CP(CTS_11),
	.D(\u_counter/N28 ),
	.Q(\u_counter/count[11] ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \u_counter/count_reg[12]  (
	.CDN(\u_counter/n1 ),
	.CP(CTS_11),
	.D(\u_counter/N29 ),
	.Q(\u_counter/count[12] ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \u_counter/count_done_reg  (
	.CDN(\u_counter/n1 ),
	.CP(CTS_11),
	.D(\u_counter/N2 ),
	.Q(COUNT_DONE), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_counter/add_22/U89  (
	.I(\u_counter/count[0] ),
	.ZN(\u_counter/N4 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/add_22/U88  (
	.A1(\u_counter/count[1] ),
	.A2(\u_counter/count[0] ),
	.Z(\u_counter/N5 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/add_22/U87  (
	.A1(\u_counter/add_22/n37 ),
	.A2(\u_counter/count[2] ),
	.Z(\u_counter/N6 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \u_counter/add_22/U86  (
	.A1(\u_counter/add_22/n37 ),
	.A2(\u_counter/count[2] ),
	.Z(\u_counter/add_22/n75 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/add_22/U85  (
	.A1(\u_counter/add_22/n75 ),
	.A2(\u_counter/count[3] ),
	.Z(\u_counter/N7 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2D0 \u_counter/add_22/U84  (
	.A1(\u_counter/add_22/n29 ),
	.A2(\u_counter/add_22/n28 ),
	.Z(\u_counter/add_22/n74 ), 
	.VSS(VSS), 
	.VDD(VDD));
   XNR2D0 \u_counter/add_22/U83  (
	.A1(\u_counter/add_22/n74 ),
	.A2(\u_counter/count[5] ),
	.ZN(\u_counter/N9 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/add_22/U82  (
	.A1(\u_counter/add_22/n21 ),
	.A2(\u_counter/count[6] ),
	.Z(\u_counter/N10 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \u_counter/add_22/U81  (
	.A1(\u_counter/add_22/n21 ),
	.A2(\u_counter/count[6] ),
	.Z(\u_counter/add_22/n73 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/add_22/U80  (
	.A1(\u_counter/add_22/n73 ),
	.A2(\u_counter/count[7] ),
	.Z(\u_counter/N11 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_counter/add_22/U79  (
	.A1(\u_counter/add_22/n12 ),
	.A2(\u_counter/count[8] ),
	.ZN(\u_counter/add_22/n9 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/add_22/U78  (
	.A1(\u_counter/add_22/n9 ),
	.A2(\u_counter/add_22/n8 ),
	.Z(\u_counter/N13 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \u_counter/add_22/U77  (
	.A1(\u_counter/add_22/n12 ),
	.A2(\u_counter/add_22/n7 ),
	.Z(\u_counter/add_22/n72 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/add_22/U76  (
	.A1(\u_counter/add_22/n72 ),
	.A2(\u_counter/count[10] ),
	.Z(\u_counter/N14 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/add_22/U75  (
	.A1(\u_counter/add_22/n1 ),
	.A2(\u_counter/count[12] ),
	.Z(\u_counter/N16 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_counter/add_22/U74  (
	.A1(\u_counter/count[2] ),
	.A2(\u_counter/count[3] ),
	.ZN(\u_counter/add_22/n31 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_counter/add_22/U73  (
	.A1(\u_counter/add_22/n31 ),
	.A2(\u_counter/add_22/n38 ),
	.ZN(\u_counter/add_22/n30 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_counter/add_22/U72  (
	.A1(\u_counter/add_22/n7 ),
	.A2(\u_counter/count[10] ),
	.ZN(\u_counter/add_22/n3 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_counter/add_22/U71  (
	.A1(\u_counter/add_22/n13 ),
	.A2(\u_counter/add_22/n3 ),
	.ZN(\u_counter/add_22/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0 \u_counter/add_22/U70  (
	.A(\u_counter/add_22/n2 ),
	.B(\u_counter/count[11] ),
	.CO(\u_counter/add_22/n1 ),
	.S(\u_counter/N15 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_counter/add_22/U66  (
	.I(\u_counter/count[9] ),
	.ZN(\u_counter/add_22/n8 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_counter/add_22/U65  (
	.I(\u_counter/count[8] ),
	.ZN(\u_counter/add_22/n11 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_counter/add_22/U64  (
	.A1(\u_counter/count[1] ),
	.A2(\u_counter/count[0] ),
	.ZN(\u_counter/add_22/n38 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_counter/add_22/U63  (
	.I(\u_counter/count[4] ),
	.ZN(\u_counter/add_22/n28 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_counter/add_22/U62  (
	.A1(\u_counter/count[4] ),
	.A2(\u_counter/count[5] ),
	.ZN(\u_counter/add_22/n22 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \u_counter/add_22/U61  (
	.A1(\u_counter/add_22/n29 ),
	.A2(\u_counter/add_22/n28 ),
	.Z(\u_counter/N8 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_counter/add_22/U60  (
	.A1(\u_counter/add_22/n11 ),
	.A2(\u_counter/add_22/n8 ),
	.ZN(\u_counter/add_22/n7 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_counter/add_22/U59  (
	.A1(\u_counter/add_22/n29 ),
	.A2(\u_counter/add_22/n22 ),
	.ZN(\u_counter/add_22/n21 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_counter/add_22/U58  (
	.I(\u_counter/add_22/n38 ),
	.ZN(\u_counter/add_22/n37 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_counter/add_22/U57  (
	.I(\u_counter/add_22/n13 ),
	.ZN(\u_counter/add_22/n12 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_counter/add_22/U56  (
	.I(\u_counter/add_22/n30 ),
	.ZN(\u_counter/add_22/n29 ), 
	.VSS(VSS), 
	.VDD(VDD));
   XNR2D0 \u_counter/add_22/U12  (
	.A1(\u_counter/add_22/n12 ),
	.A2(\u_counter/add_22/n11 ),
	.ZN(\u_counter/N12 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_up_down_counter_32b_avg/U236  (
	.A1(\u_up_down_counter_32b_avg/n2 ),
	.A2(\u_up_down_counter_32b_avg/n216 ),
	.ZN(\u_up_down_counter_32b_avg/out_count_next [31]), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22D0 \u_up_down_counter_32b_avg/U235  (
	.A1(\u_up_down_counter_32b_avg/n215 ),
	.A2(\u_up_down_counter_32b_avg/n214 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n213 ),
	.ZN(\u_up_down_counter_32b_avg/out_count_next [30]), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U234  (
	.I(CURRENT_SOURCE_ENABLE[31]),
	.ZN(\u_up_down_counter_32b_avg/n214 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22D0 \u_up_down_counter_32b_avg/U233  (
	.A1(\u_up_down_counter_32b_avg/n216 ),
	.A2(\u_up_down_counter_32b_avg/n30 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n212 ),
	.ZN(\u_up_down_counter_32b_avg/out_count_next [29]), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U232  (
	.I(CURRENT_SOURCE_ENABLE[30]),
	.ZN(\u_up_down_counter_32b_avg/n216 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22D0 \u_up_down_counter_32b_avg/U231  (
	.A1(\u_up_down_counter_32b_avg/n30 ),
	.A2(\u_up_down_counter_32b_avg/n213 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n211 ),
	.ZN(\u_up_down_counter_32b_avg/out_count_next [28]), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U230  (
	.I(CURRENT_SOURCE_ENABLE[29]),
	.ZN(\u_up_down_counter_32b_avg/n213 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22D0 \u_up_down_counter_32b_avg/U229  (
	.A1(\u_up_down_counter_32b_avg/n30 ),
	.A2(\u_up_down_counter_32b_avg/n212 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n210 ),
	.ZN(\u_up_down_counter_32b_avg/out_count_next [27]), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U228  (
	.I(CURRENT_SOURCE_ENABLE[28]),
	.ZN(\u_up_down_counter_32b_avg/n212 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22D0 \u_up_down_counter_32b_avg/U227  (
	.A1(\u_up_down_counter_32b_avg/n215 ),
	.A2(\u_up_down_counter_32b_avg/n211 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n209 ),
	.ZN(\u_up_down_counter_32b_avg/out_count_next [26]), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U226  (
	.I(CURRENT_SOURCE_ENABLE[27]),
	.ZN(\u_up_down_counter_32b_avg/n211 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22D0 \u_up_down_counter_32b_avg/U225  (
	.A1(\u_up_down_counter_32b_avg/n215 ),
	.A2(\u_up_down_counter_32b_avg/n210 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n208 ),
	.ZN(\u_up_down_counter_32b_avg/out_count_next [25]), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U224  (
	.I(CURRENT_SOURCE_ENABLE[26]),
	.ZN(\u_up_down_counter_32b_avg/n210 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22D0 \u_up_down_counter_32b_avg/U223  (
	.A1(\u_up_down_counter_32b_avg/n30 ),
	.A2(\u_up_down_counter_32b_avg/n209 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n207 ),
	.ZN(\u_up_down_counter_32b_avg/out_count_next [24]), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U222  (
	.I(CURRENT_SOURCE_ENABLE[25]),
	.ZN(\u_up_down_counter_32b_avg/n209 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22D0 \u_up_down_counter_32b_avg/U221  (
	.A1(\u_up_down_counter_32b_avg/n215 ),
	.A2(\u_up_down_counter_32b_avg/n208 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n206 ),
	.ZN(\u_up_down_counter_32b_avg/out_count_next [23]), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U220  (
	.I(CURRENT_SOURCE_ENABLE[24]),
	.ZN(\u_up_down_counter_32b_avg/n208 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22D0 \u_up_down_counter_32b_avg/U219  (
	.A1(\u_up_down_counter_32b_avg/n215 ),
	.A2(\u_up_down_counter_32b_avg/n207 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n205 ),
	.ZN(\u_up_down_counter_32b_avg/out_count_next [22]), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U218  (
	.I(CURRENT_SOURCE_ENABLE[23]),
	.ZN(\u_up_down_counter_32b_avg/n207 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22D0 \u_up_down_counter_32b_avg/U217  (
	.A1(\u_up_down_counter_32b_avg/n215 ),
	.A2(\u_up_down_counter_32b_avg/n206 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n204 ),
	.ZN(\u_up_down_counter_32b_avg/out_count_next [21]), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U216  (
	.I(CURRENT_SOURCE_ENABLE[22]),
	.ZN(\u_up_down_counter_32b_avg/n206 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22D0 \u_up_down_counter_32b_avg/U215  (
	.A1(\u_up_down_counter_32b_avg/n30 ),
	.A2(\u_up_down_counter_32b_avg/n205 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n203 ),
	.ZN(\u_up_down_counter_32b_avg/out_count_next [20]), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U214  (
	.I(CURRENT_SOURCE_ENABLE[21]),
	.ZN(\u_up_down_counter_32b_avg/n205 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22D0 \u_up_down_counter_32b_avg/U213  (
	.A1(\u_up_down_counter_32b_avg/n215 ),
	.A2(\u_up_down_counter_32b_avg/n204 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n202 ),
	.ZN(\u_up_down_counter_32b_avg/out_count_next [19]), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U212  (
	.I(CURRENT_SOURCE_ENABLE[20]),
	.ZN(\u_up_down_counter_32b_avg/n204 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22D0 \u_up_down_counter_32b_avg/U211  (
	.A1(\u_up_down_counter_32b_avg/n30 ),
	.A2(\u_up_down_counter_32b_avg/n203 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n201 ),
	.ZN(\u_up_down_counter_32b_avg/out_count_next [18]), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U210  (
	.I(CURRENT_SOURCE_ENABLE[19]),
	.ZN(\u_up_down_counter_32b_avg/n203 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22D0 \u_up_down_counter_32b_avg/U209  (
	.A1(\u_up_down_counter_32b_avg/n215 ),
	.A2(\u_up_down_counter_32b_avg/n202 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n200 ),
	.ZN(\u_up_down_counter_32b_avg/out_count_next [17]), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U208  (
	.I(CURRENT_SOURCE_ENABLE[18]),
	.ZN(\u_up_down_counter_32b_avg/n202 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U207  (
	.I(CURRENT_SOURCE_ENABLE[17]),
	.ZN(\u_up_down_counter_32b_avg/n201 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI31D0 \u_up_down_counter_32b_avg/U206  (
	.A1(CURRENT_SOURCE_ENABLE[2]),
	.A2(\u_up_down_counter_32b_avg/n52 ),
	.A3(\u_up_down_counter_32b_avg/n218 ),
	.B(LOOP_BYPASS),
	.ZN(\u_up_down_counter_32b_avg/n195 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U205  (
	.I(CURRENT_SOURCE_ENABLE[0]),
	.ZN(\u_up_down_counter_32b_avg/n197 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U204  (
	.I(CURRENT_SOURCE_ENABLE[1]),
	.ZN(\u_up_down_counter_32b_avg/n198 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U203  (
	.I(CURRENT_SOURCE_ENABLE[2]),
	.ZN(\u_up_down_counter_32b_avg/n194 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI31D0 \u_up_down_counter_32b_avg/U202  (
	.A1(CURRENT_SOURCE_ENABLE[5]),
	.A2(\u_up_down_counter_32b_avg/n52 ),
	.A3(\u_up_down_counter_32b_avg/n218 ),
	.B(LOOP_BYPASS),
	.ZN(\u_up_down_counter_32b_avg/n190 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U201  (
	.I(CURRENT_SOURCE_ENABLE[3]),
	.ZN(\u_up_down_counter_32b_avg/n192 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U200  (
	.I(CURRENT_SOURCE_ENABLE[5]),
	.ZN(\u_up_down_counter_32b_avg/n189 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI31D0 \u_up_down_counter_32b_avg/U199  (
	.A1(CURRENT_SOURCE_ENABLE[8]),
	.A2(\u_up_down_counter_32b_avg/n52 ),
	.A3(\u_up_down_counter_32b_avg/n218 ),
	.B(LOOP_BYPASS),
	.ZN(\u_up_down_counter_32b_avg/n184 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U198  (
	.I(CURRENT_SOURCE_ENABLE[6]),
	.ZN(\u_up_down_counter_32b_avg/n187 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U197  (
	.I(CURRENT_SOURCE_ENABLE[7]),
	.ZN(\u_up_down_counter_32b_avg/n185 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U196  (
	.I(CURRENT_SOURCE_ENABLE[8]),
	.ZN(\u_up_down_counter_32b_avg/n183 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U195  (
	.I(CURRENT_SOURCE_ENABLE[9]),
	.ZN(\u_up_down_counter_32b_avg/n181 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U194  (
	.I(CURRENT_SOURCE_ENABLE[10]),
	.ZN(\u_up_down_counter_32b_avg/n180 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U193  (
	.I(CURRENT_SOURCE_ENABLE[11]),
	.ZN(\u_up_down_counter_32b_avg/n179 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U192  (
	.I(CURRENT_SOURCE_ENABLE[12]),
	.ZN(\u_up_down_counter_32b_avg/n178 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U191  (
	.I(CURRENT_SOURCE_ENABLE[13]),
	.ZN(\u_up_down_counter_32b_avg/n177 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U190  (
	.I(CURRENT_SOURCE_ENABLE[16]),
	.ZN(\u_up_down_counter_32b_avg/n200 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U189  (
	.I(CURRENT_SOURCE_ENABLE[14]),
	.ZN(\u_up_down_counter_32b_avg/n176 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U188  (
	.I(CURRENT_SOURCE_ENABLE[15]),
	.ZN(\u_up_down_counter_32b_avg/n199 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U187  (
	.I(LOOP_BYPASS),
	.ZN(\u_up_down_counter_32b_avg/n175 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21D0 \u_up_down_counter_32b_avg/U186  (
	.A1(\u_up_down_counter_32b_avg/n168 ),
	.A2(\u_up_down_counter_32b_avg/n167 ),
	.B(\u_up_down_counter_32b_avg/n166 ),
	.ZN(\u_up_down_counter_32b_avg/n169 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI221D0 \u_up_down_counter_32b_avg/U185  (
	.A1(\u_up_down_counter_32b_avg/n165 ),
	.A2(\u_up_down_counter_32b_avg/n164 ),
	.B1(\u_up_down_counter_32b_avg/n59 ),
	.B2(\u_up_down_counter_32b_avg/n163 ),
	.C(\u_up_down_counter_32b_avg/n162 ),
	.ZN(\u_up_down_counter_32b_avg/n166 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI32D0 \u_up_down_counter_32b_avg/U184  (
	.A1(\u_up_down_counter_32b_avg/n161 ),
	.A2(COUNTER[14]),
	.A3(\u_up_down_counter_32b_avg/n160 ),
	.B1(COUNTER[15]),
	.B2(\u_up_down_counter_32b_avg/n159 ),
	.ZN(\u_up_down_counter_32b_avg/n162 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U183  (
	.I(UPPER_VOLTAGE_BOUND[14]),
	.ZN(\u_up_down_counter_32b_avg/n160 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22D0 \u_up_down_counter_32b_avg/U182  (
	.A1(COUNTER[13]),
	.A2(\u_up_down_counter_32b_avg/n157 ),
	.B1(COUNTER[12]),
	.B2(\u_up_down_counter_32b_avg/n156 ),
	.ZN(\u_up_down_counter_32b_avg/n163 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U181  (
	.I(UPPER_VOLTAGE_BOUND[12]),
	.ZN(\u_up_down_counter_32b_avg/n156 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U180  (
	.I(UPPER_VOLTAGE_BOUND[13]),
	.ZN(\u_up_down_counter_32b_avg/n157 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI211D0 \u_up_down_counter_32b_avg/U179  (
	.A1(UPPER_VOLTAGE_BOUND[4]),
	.A2(\u_up_down_counter_32b_avg/n144 ),
	.B(\u_up_down_counter_32b_avg/n171 ),
	.C(\u_up_down_counter_32b_avg/n66 ),
	.ZN(\u_up_down_counter_32b_avg/n147 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI31D0 \u_up_down_counter_32b_avg/U178  (
	.A1(\u_up_down_counter_32b_avg/n143 ),
	.A2(\u_up_down_counter_32b_avg/n142 ),
	.A3(\u_up_down_counter_32b_avg/n141 ),
	.B(\u_up_down_counter_32b_avg/n140 ),
	.ZN(\u_up_down_counter_32b_avg/n168 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI32D0 \u_up_down_counter_32b_avg/U177  (
	.A1(\u_up_down_counter_32b_avg/n139 ),
	.A2(COUNTER[2]),
	.A3(\u_up_down_counter_32b_avg/n138 ),
	.B1(COUNTER[3]),
	.B2(\u_up_down_counter_32b_avg/n137 ),
	.ZN(\u_up_down_counter_32b_avg/n140 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U176  (
	.I(\u_up_down_counter_32b_avg/n142 ),
	.ZN(\u_up_down_counter_32b_avg/n139 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI22D0 \u_up_down_counter_32b_avg/U175  (
	.A1(COUNTER[1]),
	.A2(\u_up_down_counter_32b_avg/n136 ),
	.B1(COUNTER[2]),
	.B2(\u_up_down_counter_32b_avg/n138 ),
	.ZN(\u_up_down_counter_32b_avg/n141 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U174  (
	.I(UPPER_VOLTAGE_BOUND[2]),
	.ZN(\u_up_down_counter_32b_avg/n138 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U173  (
	.I(UPPER_VOLTAGE_BOUND[1]),
	.ZN(\u_up_down_counter_32b_avg/n136 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_up_down_counter_32b_avg/U172  (
	.A1(COUNTER[3]),
	.A2(\u_up_down_counter_32b_avg/n137 ),
	.ZN(\u_up_down_counter_32b_avg/n142 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U171  (
	.I(UPPER_VOLTAGE_BOUND[3]),
	.ZN(\u_up_down_counter_32b_avg/n137 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO211D0 \u_up_down_counter_32b_avg/U170  (
	.A1(UPPER_VOLTAGE_BOUND[1]),
	.A2(\u_up_down_counter_32b_avg/n135 ),
	.B(\u_up_down_counter_32b_avg/n134 ),
	.C(UPPER_VOLTAGE_BOUND[0]),
	.Z(\u_up_down_counter_32b_avg/n143 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U169  (
	.I(\u_up_down_counter_32b_avg/n145 ),
	.ZN(\u_up_down_counter_32b_avg/n165 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI32D0 \u_up_down_counter_32b_avg/U168  (
	.A1(\u_up_down_counter_32b_avg/n128 ),
	.A2(COUNTER[6]),
	.A3(\u_up_down_counter_32b_avg/n127 ),
	.B1(\u_up_down_counter_32b_avg/n126 ),
	.B2(\u_up_down_counter_32b_avg/n146 ),
	.ZN(\u_up_down_counter_32b_avg/n132 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI22D0 \u_up_down_counter_32b_avg/U167  (
	.A1(UPPER_VOLTAGE_BOUND[4]),
	.A2(\u_up_down_counter_32b_avg/n144 ),
	.B1(UPPER_VOLTAGE_BOUND[5]),
	.B2(\u_up_down_counter_32b_avg/n125 ),
	.ZN(\u_up_down_counter_32b_avg/n126 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U166  (
	.I(UPPER_VOLTAGE_BOUND[6]),
	.ZN(\u_up_down_counter_32b_avg/n127 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U165  (
	.I(\u_up_down_counter_32b_avg/n123 ),
	.ZN(\u_up_down_counter_32b_avg/n128 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_up_down_counter_32b_avg/U164  (
	.A1(COUNTER[7]),
	.A2(\u_up_down_counter_32b_avg/n122 ),
	.ZN(\u_up_down_counter_32b_avg/n133 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U163  (
	.I(UPPER_VOLTAGE_BOUND[7]),
	.ZN(\u_up_down_counter_32b_avg/n122 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_up_down_counter_32b_avg/U162  (
	.A1(COUNTER[8]),
	.A2(\u_up_down_counter_32b_avg/n150 ),
	.ZN(\u_up_down_counter_32b_avg/n171 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U161  (
	.I(UPPER_VOLTAGE_BOUND[8]),
	.ZN(\u_up_down_counter_32b_avg/n150 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_up_down_counter_32b_avg/U160  (
	.A1(LOWER_VOLTAGE_BOUND[3]),
	.A2(\u_up_down_counter_32b_avg/n100 ),
	.ZN(\u_up_down_counter_32b_avg/n105 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U159  (
	.I(COUNTER[3]),
	.ZN(\u_up_down_counter_32b_avg/n100 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U158  (
	.I(COUNTER[2]),
	.ZN(\u_up_down_counter_32b_avg/n103 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U157  (
	.I(COUNTER[0]),
	.ZN(\u_up_down_counter_32b_avg/n134 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U156  (
	.I(COUNTER[1]),
	.ZN(\u_up_down_counter_32b_avg/n135 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_up_down_counter_32b_avg/U155  (
	.A1(LOWER_VOLTAGE_BOUND[8]),
	.A2(\u_up_down_counter_32b_avg/n89 ),
	.ZN(\u_up_down_counter_32b_avg/n109 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U154  (
	.I(COUNTER[8]),
	.ZN(\u_up_down_counter_32b_avg/n89 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U153  (
	.I(COUNTER[9]),
	.ZN(\u_up_down_counter_32b_avg/n88 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U151  (
	.I(LOWER_VOLTAGE_BOUND[10]),
	.ZN(\u_up_down_counter_32b_avg/n86 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U150  (
	.I(COUNTER[6]),
	.ZN(\u_up_down_counter_32b_avg/n124 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_up_down_counter_32b_avg/U149  (
	.A1(LOWER_VOLTAGE_BOUND[7]),
	.A2(\u_up_down_counter_32b_avg/n78 ),
	.ZN(\u_up_down_counter_32b_avg/n84 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U148  (
	.I(COUNTER[7]),
	.ZN(\u_up_down_counter_32b_avg/n78 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U147  (
	.I(LOWER_VOLTAGE_BOUND[6]),
	.ZN(\u_up_down_counter_32b_avg/n79 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U146  (
	.I(LOWER_VOLTAGE_BOUND[5]),
	.ZN(\u_up_down_counter_32b_avg/n80 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U145  (
	.I(COUNTER[5]),
	.ZN(\u_up_down_counter_32b_avg/n125 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U144  (
	.I(COUNTER[4]),
	.ZN(\u_up_down_counter_32b_avg/n144 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U143  (
	.I(COUNTER[12]),
	.ZN(\u_up_down_counter_32b_avg/n131 ), 
	.VSS(VSS), 
	.VDD(VDD));
   IND3D0 \u_up_down_counter_32b_avg/U142  (
	.A1(LOWER_VOLTAGE_BOUND[8]),
	.B1(\u_up_down_counter_32b_avg/n110 ),
	.B2(COUNTER[8]),
	.ZN(\u_up_down_counter_32b_avg/n94 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI221D0 \u_up_down_counter_32b_avg/U141  (
	.A1(\u_up_down_counter_32b_avg/n22 ),
	.A2(\u_up_down_counter_32b_avg/n198 ),
	.B1(\u_up_down_counter_32b_avg/n3 ),
	.B2(\u_up_down_counter_32b_avg/n197 ),
	.C(\u_up_down_counter_32b_avg/n50 ),
	.ZN(\u_up_down_counter_32b_avg/n48 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_up_down_counter_32b_avg/U140  (
	.A1(COUNTER[9]),
	.A2(\u_up_down_counter_32b_avg/n149 ),
	.ZN(\u_up_down_counter_32b_avg/n66 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22D0 \u_up_down_counter_32b_avg/U138  (
	.A1(\u_up_down_counter_32b_avg/n30 ),
	.A2(\u_up_down_counter_32b_avg/n201 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n199 ),
	.ZN(\u_up_down_counter_32b_avg/out_count_next [16]), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFFD1 \u_up_down_counter_32b_avg/U135  (
	.I(RST_N),
	.Z(\u_up_down_counter_32b_avg/n70 ), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFFD1 \u_up_down_counter_32b_avg/U134  (
	.I(RST_N),
	.Z(\u_up_down_counter_32b_avg/n69 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U133  (
	.I(LOWER_VOLTAGE_BOUND[3]),
	.ZN(\u_up_down_counter_32b_avg/n104 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_up_down_counter_32b_avg/U132  (
	.A1(LOWER_VOLTAGE_BOUND[1]),
	.A2(\u_up_down_counter_32b_avg/n135 ),
	.ZN(\u_up_down_counter_32b_avg/n102 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_up_down_counter_32b_avg/U130  (
	.A1(COUNTER[7]),
	.A2(\u_up_down_counter_32b_avg/n122 ),
	.ZN(\u_up_down_counter_32b_avg/n123 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OA211D0 \u_up_down_counter_32b_avg/U129  (
	.A1(\u_up_down_counter_32b_avg/n133 ),
	.A2(\u_up_down_counter_32b_avg/n132 ),
	.B(\u_up_down_counter_32b_avg/n165 ),
	.C(\u_up_down_counter_32b_avg/n13 ),
	.Z(\u_up_down_counter_32b_avg/n170 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_up_down_counter_32b_avg/U128  (
	.A1(LOWER_VOLTAGE_BOUND[2]),
	.A2(\u_up_down_counter_32b_avg/n103 ),
	.ZN(\u_up_down_counter_32b_avg/n106 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_up_down_counter_32b_avg/U127  (
	.A1(LOWER_VOLTAGE_BOUND[11]),
	.A2(\u_up_down_counter_32b_avg/n92 ),
	.ZN(\u_up_down_counter_32b_avg/n98 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI31D0 \u_up_down_counter_32b_avg/U126  (
	.A1(\u_up_down_counter_32b_avg/n98 ),
	.A2(\u_up_down_counter_32b_avg/n97 ),
	.A3(\u_up_down_counter_32b_avg/n96 ),
	.B(\u_up_down_counter_32b_avg/n63 ),
	.ZN(\u_up_down_counter_32b_avg/n117 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_up_down_counter_32b_avg/U124  (
	.A1(LOWER_VOLTAGE_BOUND[11]),
	.A2(\u_up_down_counter_32b_avg/n92 ),
	.ZN(\u_up_down_counter_32b_avg/n93 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_up_down_counter_32b_avg/U122  (
	.A1(LOWER_VOLTAGE_BOUND[4]),
	.A2(\u_up_down_counter_32b_avg/n144 ),
	.ZN(\u_up_down_counter_32b_avg/n82 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AN3D0 \u_up_down_counter_32b_avg/U121  (
	.A1(\u_up_down_counter_32b_avg/n102 ),
	.A2(\u_up_down_counter_32b_avg/n101 ),
	.A3(\u_up_down_counter_32b_avg/n105 ),
	.Z(\u_up_down_counter_32b_avg/n60 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21D1 \u_up_down_counter_32b_avg/U120  (
	.A1(COUNTER[10]),
	.A2(\u_up_down_counter_32b_avg/n86 ),
	.B(\u_up_down_counter_32b_avg/n93 ),
	.ZN(\u_up_down_counter_32b_avg/n107 ), 
	.VSS(VSS), 
	.VDD(VDD));
   IND2D0 \u_up_down_counter_32b_avg/U119  (
	.A1(LOWER_VOLTAGE_BOUND[9]),
	.B1(COUNTER[9]),
	.ZN(\u_up_down_counter_32b_avg/n95 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INR3D0 \u_up_down_counter_32b_avg/U118  (
	.A1(\u_up_down_counter_32b_avg/n93 ),
	.B1(LOWER_VOLTAGE_BOUND[10]),
	.B2(\u_up_down_counter_32b_avg/n153 ),
	.ZN(\u_up_down_counter_32b_avg/n97 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI22D0 \u_up_down_counter_32b_avg/U117  (
	.A1(LOWER_VOLTAGE_BOUND[13]),
	.A2(\u_up_down_counter_32b_avg/n129 ),
	.B1(LOWER_VOLTAGE_BOUND[12]),
	.B2(\u_up_down_counter_32b_avg/n131 ),
	.ZN(\u_up_down_counter_32b_avg/n77 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI221D0 \u_up_down_counter_32b_avg/U116  (
	.A1(\u_up_down_counter_32b_avg/n3 ),
	.A2(\u_up_down_counter_32b_avg/n185 ),
	.B1(\u_up_down_counter_32b_avg/n52 ),
	.B2(\u_up_down_counter_32b_avg/n187 ),
	.C(\u_up_down_counter_32b_avg/n184 ),
	.ZN(\u_up_down_counter_32b_avg/n39 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI221D0 \u_up_down_counter_32b_avg/U115  (
	.A1(\u_up_down_counter_32b_avg/n3 ),
	.A2(\u_up_down_counter_32b_avg/n20 ),
	.B1(\u_up_down_counter_32b_avg/n52 ),
	.B2(\u_up_down_counter_32b_avg/n192 ),
	.C(\u_up_down_counter_32b_avg/n190 ),
	.ZN(\u_up_down_counter_32b_avg/n36 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI221D0 \u_up_down_counter_32b_avg/U114  (
	.A1(\u_up_down_counter_32b_avg/n3 ),
	.A2(\u_up_down_counter_32b_avg/n198 ),
	.B1(\u_up_down_counter_32b_avg/n52 ),
	.B2(\u_up_down_counter_32b_avg/n197 ),
	.C(\u_up_down_counter_32b_avg/n195 ),
	.ZN(\u_up_down_counter_32b_avg/n33 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_up_down_counter_32b_avg/U112  (
	.A1(LOWER_VOLTAGE_BOUND[15]),
	.A2(\u_up_down_counter_32b_avg/n91 ),
	.ZN(\u_up_down_counter_32b_avg/n119 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_up_down_counter_32b_avg/U111  (
	.A1(LOWER_VOLTAGE_BOUND[6]),
	.A2(\u_up_down_counter_32b_avg/n124 ),
	.ZN(\u_up_down_counter_32b_avg/n85 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U110  (
	.I(LOWER_VOLTAGE_BOUND[7]),
	.ZN(\u_up_down_counter_32b_avg/n83 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI222D0 \u_up_down_counter_32b_avg/U109  (
	.A1(\u_up_down_counter_32b_avg/n3 ),
	.A2(\u_up_down_counter_32b_avg/n180 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n181 ),
	.C1(\u_up_down_counter_32b_avg/n7 ),
	.C2(\u_up_down_counter_32b_avg/n179 ),
	.ZN(\u_up_down_counter_32b_avg/n42 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI222D0 \u_up_down_counter_32b_avg/U108  (
	.A1(\u_up_down_counter_32b_avg/n3 ),
	.A2(\u_up_down_counter_32b_avg/n179 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n180 ),
	.C1(\u_up_down_counter_32b_avg/n7 ),
	.C2(\u_up_down_counter_32b_avg/n178 ),
	.ZN(\u_up_down_counter_32b_avg/n43 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI222D0 \u_up_down_counter_32b_avg/U107  (
	.A1(\u_up_down_counter_32b_avg/n3 ),
	.A2(\u_up_down_counter_32b_avg/n178 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n179 ),
	.C1(\u_up_down_counter_32b_avg/n7 ),
	.C2(\u_up_down_counter_32b_avg/n177 ),
	.ZN(\u_up_down_counter_32b_avg/n44 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI222D0 \u_up_down_counter_32b_avg/U106  (
	.A1(\u_up_down_counter_32b_avg/n3 ),
	.A2(\u_up_down_counter_32b_avg/n199 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n176 ),
	.C1(\u_up_down_counter_32b_avg/n200 ),
	.C2(\u_up_down_counter_32b_avg/n7 ),
	.ZN(\u_up_down_counter_32b_avg/n47 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI222D0 \u_up_down_counter_32b_avg/U105  (
	.A1(\u_up_down_counter_32b_avg/n3 ),
	.A2(\u_up_down_counter_32b_avg/n176 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n177 ),
	.C1(\u_up_down_counter_32b_avg/n199 ),
	.C2(\u_up_down_counter_32b_avg/n7 ),
	.ZN(\u_up_down_counter_32b_avg/n46 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI222D0 \u_up_down_counter_32b_avg/U104  (
	.A1(\u_up_down_counter_32b_avg/n3 ),
	.A2(\u_up_down_counter_32b_avg/n183 ),
	.B1(\u_up_down_counter_32b_avg/n2 ),
	.B2(\u_up_down_counter_32b_avg/n185 ),
	.C1(\u_up_down_counter_32b_avg/n181 ),
	.C2(\u_up_down_counter_32b_avg/n7 ),
	.ZN(\u_up_down_counter_32b_avg/n40 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR3D0 \u_up_down_counter_32b_avg/U103  (
	.A1(\u_up_down_counter_32b_avg/n56 ),
	.A2(\u_up_down_counter_32b_avg/n57 ),
	.A3(\u_up_down_counter_32b_avg/n58 ),
	.Z(\u_up_down_counter_32b_avg/n41 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_up_down_counter_32b_avg/U102  (
	.A1(\u_up_down_counter_32b_avg/n7 ),
	.A2(\u_up_down_counter_32b_avg/n180 ),
	.ZN(\u_up_down_counter_32b_avg/n58 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_up_down_counter_32b_avg/U101  (
	.A1(\u_up_down_counter_32b_avg/n2 ),
	.A2(\u_up_down_counter_32b_avg/n183 ),
	.ZN(\u_up_down_counter_32b_avg/n57 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_up_down_counter_32b_avg/U100  (
	.A1(\u_up_down_counter_32b_avg/n3 ),
	.A2(\u_up_down_counter_32b_avg/n181 ),
	.ZN(\u_up_down_counter_32b_avg/n56 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_up_down_counter_32b_avg/U99  (
	.A1(LOWER_VOLTAGE_BOUND[15]),
	.A2(\u_up_down_counter_32b_avg/n91 ),
	.ZN(\u_up_down_counter_32b_avg/n74 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U98  (
	.I(UPPER_VOLTAGE_BOUND[15]),
	.ZN(\u_up_down_counter_32b_avg/n159 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U97  (
	.I(COUNTER[11]),
	.ZN(\u_up_down_counter_32b_avg/n92 ), 
	.VSS(VSS), 
	.VDD(VDD));
   IOA21D0 \u_up_down_counter_32b_avg/U96  (
	.A1(\u_up_down_counter_32b_avg/n99 ),
	.A2(\u_up_down_counter_32b_avg/n60 ),
	.B(\u_up_down_counter_32b_avg/n55 ),
	.ZN(\u_up_down_counter_32b_avg/n115 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U95  (
	.I(COUNTER[10]),
	.ZN(\u_up_down_counter_32b_avg/n153 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI211D0 \u_up_down_counter_32b_avg/U94  (
	.A1(LOWER_VOLTAGE_BOUND[1]),
	.A2(\u_up_down_counter_32b_avg/n135 ),
	.B(\u_up_down_counter_32b_avg/n134 ),
	.C(LOWER_VOLTAGE_BOUND[0]),
	.ZN(\u_up_down_counter_32b_avg/n99 ), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D0 \u_up_down_counter_32b_avg/U93  (
	.A1(COUNT_DONE),
	.A2(\u_up_down_counter_32b_avg/n174 ),
	.ZN(\u_up_down_counter_32b_avg/n52 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI22D0 \u_up_down_counter_32b_avg/U92  (
	.A1(\u_up_down_counter_32b_avg/n106 ),
	.A2(\u_up_down_counter_32b_avg/n105 ),
	.B1(COUNTER[3]),
	.B2(\u_up_down_counter_32b_avg/n104 ),
	.ZN(\u_up_down_counter_32b_avg/n55 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_up_down_counter_32b_avg/U91  (
	.A1(LOWER_VOLTAGE_BOUND[5]),
	.A2(\u_up_down_counter_32b_avg/n125 ),
	.ZN(\u_up_down_counter_32b_avg/n81 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR3D0 \u_up_down_counter_32b_avg/U90  (
	.A1(\u_up_down_counter_32b_avg/n31 ),
	.A2(\u_up_down_counter_32b_avg/n32 ),
	.A3(\u_up_down_counter_32b_avg/n49 ),
	.Z(\u_up_down_counter_32b_avg/n45 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_up_down_counter_32b_avg/U89  (
	.A1(\u_up_down_counter_32b_avg/n7 ),
	.A2(\u_up_down_counter_32b_avg/n176 ),
	.ZN(\u_up_down_counter_32b_avg/n49 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_up_down_counter_32b_avg/U88  (
	.A1(\u_up_down_counter_32b_avg/n2 ),
	.A2(\u_up_down_counter_32b_avg/n178 ),
	.ZN(\u_up_down_counter_32b_avg/n32 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_up_down_counter_32b_avg/U87  (
	.A1(\u_up_down_counter_32b_avg/n3 ),
	.A2(\u_up_down_counter_32b_avg/n177 ),
	.ZN(\u_up_down_counter_32b_avg/n31 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U86  (
	.I(LOWER_VOLTAGE_BOUND[4]),
	.ZN(\u_up_down_counter_32b_avg/n111 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_up_down_counter_32b_avg/U84  (
	.A1(LOWER_VOLTAGE_BOUND[2]),
	.A2(\u_up_down_counter_32b_avg/n103 ),
	.ZN(\u_up_down_counter_32b_avg/n101 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21D0 \u_up_down_counter_32b_avg/U83  (
	.A1(\u_up_down_counter_32b_avg/n95 ),
	.A2(\u_up_down_counter_32b_avg/n94 ),
	.B(\u_up_down_counter_32b_avg/n107 ),
	.ZN(\u_up_down_counter_32b_avg/n96 ), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D1 \u_up_down_counter_32b_avg/U82  (
	.A1(\u_up_down_counter_32b_avg/n117 ),
	.A2(\u_up_down_counter_32b_avg/n116 ),
	.ZN(\u_up_down_counter_32b_avg/n118 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND1 \u_up_down_counter_32b_avg/U80  (
	.I(\u_up_down_counter_32b_avg/n50 ),
	.ZN(\u_up_down_counter_32b_avg/n30 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INR4D1 \u_up_down_counter_32b_avg/U79  (
	.A1(\u_up_down_counter_32b_avg/n121 ),
	.B1(\u_up_down_counter_32b_avg/n119 ),
	.B2(\u_up_down_counter_32b_avg/n120 ),
	.B3(\u_up_down_counter_32b_avg/n118 ),
	.ZN(\u_up_down_counter_32b_avg/n174 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND1 \u_up_down_counter_32b_avg/U76  (
	.I(\u_up_down_counter_32b_avg/n50 ),
	.ZN(\u_up_down_counter_32b_avg/n215 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR4D0 \u_up_down_counter_32b_avg/U75  (
	.A1(\u_up_down_counter_32b_avg/n62 ),
	.A2(\u_up_down_counter_32b_avg/n147 ),
	.A3(\u_up_down_counter_32b_avg/n146 ),
	.A4(\u_up_down_counter_32b_avg/n145 ),
	.Z(\u_up_down_counter_32b_avg/n167 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2D0 \u_up_down_counter_32b_avg/U74  (
	.A1(UPPER_VOLTAGE_BOUND[6]),
	.A2(\u_up_down_counter_32b_avg/n124 ),
	.Z(\u_up_down_counter_32b_avg/n29 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2D0 \u_up_down_counter_32b_avg/U73  (
	.A1(UPPER_VOLTAGE_BOUND[5]),
	.A2(\u_up_down_counter_32b_avg/n125 ),
	.Z(\u_up_down_counter_32b_avg/n28 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI31D0 \u_up_down_counter_32b_avg/U72  (
	.A1(CURRENT_SOURCE_ENABLE[6]),
	.A2(\u_up_down_counter_32b_avg/n52 ),
	.A3(\u_up_down_counter_32b_avg/n3 ),
	.B(LOOP_BYPASS),
	.ZN(\u_up_down_counter_32b_avg/n188 ), 
	.VSS(VSS), 
	.VDD(VDD));
   ND3D0 \u_up_down_counter_32b_avg/U71  (
	.A1(\u_up_down_counter_32b_avg/n26 ),
	.A2(\u_up_down_counter_32b_avg/n27 ),
	.A3(\u_up_down_counter_32b_avg/n188 ),
	.ZN(\u_up_down_counter_32b_avg/n37 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2D0 \u_up_down_counter_32b_avg/U70  (
	.A1(\u_up_down_counter_32b_avg/n52 ),
	.A2(\u_up_down_counter_32b_avg/n20 ),
	.Z(\u_up_down_counter_32b_avg/n27 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2D0 \u_up_down_counter_32b_avg/U69  (
	.A1(\u_up_down_counter_32b_avg/n3 ),
	.A2(\u_up_down_counter_32b_avg/n189 ),
	.Z(\u_up_down_counter_32b_avg/n26 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D0 \u_up_down_counter_32b_avg/U68  (
	.A1(COUNTER[9]),
	.B1(UPPER_VOLTAGE_BOUND[9]),
	.ZN(\u_up_down_counter_32b_avg/n64 ), 
	.VSS(VSS), 
	.VDD(VDD));
   IOA21D1 \u_up_down_counter_32b_avg/U66  (
	.A1(\u_up_down_counter_32b_avg/n92 ),
	.A2(UPPER_VOLTAGE_BOUND[11]),
	.B(\u_up_down_counter_32b_avg/n154 ),
	.ZN(\u_up_down_counter_32b_avg/n164 ), 
	.VSS(VSS), 
	.VDD(VDD));
   ND3D0 \u_up_down_counter_32b_avg/U65  (
	.A1(\u_up_down_counter_32b_avg/n24 ),
	.A2(\u_up_down_counter_32b_avg/n25 ),
	.A3(\u_up_down_counter_32b_avg/n191 ),
	.ZN(\u_up_down_counter_32b_avg/n35 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2D0 \u_up_down_counter_32b_avg/U64  (
	.A1(\u_up_down_counter_32b_avg/n52 ),
	.A2(\u_up_down_counter_32b_avg/n194 ),
	.Z(\u_up_down_counter_32b_avg/n25 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2D0 \u_up_down_counter_32b_avg/U63  (
	.A1(\u_up_down_counter_32b_avg/n3 ),
	.A2(\u_up_down_counter_32b_avg/n192 ),
	.Z(\u_up_down_counter_32b_avg/n24 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U62  (
	.I(\u_up_down_counter_32b_avg/n52 ),
	.ZN(\u_up_down_counter_32b_avg/n21 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U61  (
	.I(CURRENT_SOURCE_ENABLE[4]),
	.ZN(\u_up_down_counter_32b_avg/n20 ), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D1 \u_up_down_counter_32b_avg/U59  (
	.A1(COUNT_DONE),
	.A2(\u_up_down_counter_32b_avg/n174 ),
	.ZN(\u_up_down_counter_32b_avg/n53 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \u_up_down_counter_32b_avg/U58  (
	.A1(\u_up_down_counter_32b_avg/n85 ),
	.A2(\u_up_down_counter_32b_avg/n84 ),
	.B1(COUNTER[7]),
	.B2(\u_up_down_counter_32b_avg/n83 ),
	.Z(\u_up_down_counter_32b_avg/n17 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OA21D0 \u_up_down_counter_32b_avg/U57  (
	.A1(\u_up_down_counter_32b_avg/n82 ),
	.A2(\u_up_down_counter_32b_avg/n81 ),
	.B(\u_up_down_counter_32b_avg/n4 ),
	.Z(\u_up_down_counter_32b_avg/n16 ), 
	.VSS(VSS), 
	.VDD(VDD));
   IAO21D0 \u_up_down_counter_32b_avg/U56  (
	.A1(\u_up_down_counter_32b_avg/n16 ),
	.A2(\u_up_down_counter_32b_avg/n17 ),
	.B(\u_up_down_counter_32b_avg/n90 ),
	.ZN(\u_up_down_counter_32b_avg/n120 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI31D0 \u_up_down_counter_32b_avg/U55  (
	.A1(CURRENT_SOURCE_ENABLE[7]),
	.A2(\u_up_down_counter_32b_avg/n52 ),
	.A3(\u_up_down_counter_32b_avg/n3 ),
	.B(LOOP_BYPASS),
	.ZN(\u_up_down_counter_32b_avg/n186 ), 
	.VSS(VSS), 
	.VDD(VDD));
   ND3D0 \u_up_down_counter_32b_avg/U54  (
	.A1(\u_up_down_counter_32b_avg/n14 ),
	.A2(\u_up_down_counter_32b_avg/n15 ),
	.A3(\u_up_down_counter_32b_avg/n186 ),
	.ZN(\u_up_down_counter_32b_avg/n38 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2D0 \u_up_down_counter_32b_avg/U53  (
	.A1(\u_up_down_counter_32b_avg/n52 ),
	.A2(\u_up_down_counter_32b_avg/n189 ),
	.Z(\u_up_down_counter_32b_avg/n15 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2D0 \u_up_down_counter_32b_avg/U52  (
	.A1(\u_up_down_counter_32b_avg/n3 ),
	.A2(\u_up_down_counter_32b_avg/n187 ),
	.Z(\u_up_down_counter_32b_avg/n14 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI211D0 \u_up_down_counter_32b_avg/U51  (
	.A1(COUNTER[4]),
	.A2(\u_up_down_counter_32b_avg/n111 ),
	.B(\u_up_down_counter_32b_avg/n110 ),
	.C(\u_up_down_counter_32b_avg/n109 ),
	.ZN(\u_up_down_counter_32b_avg/n112 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2D0 \u_up_down_counter_32b_avg/U49  (
	.A1(\u_up_down_counter_32b_avg/n52 ),
	.A2(\u_up_down_counter_32b_avg/n198 ),
	.Z(\u_up_down_counter_32b_avg/n12 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2D0 \u_up_down_counter_32b_avg/U48  (
	.A1(\u_up_down_counter_32b_avg/n3 ),
	.A2(\u_up_down_counter_32b_avg/n194 ),
	.Z(\u_up_down_counter_32b_avg/n11 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U46  (
	.I(LOWER_VOLTAGE_BOUND[14]),
	.ZN(\u_up_down_counter_32b_avg/n73 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_up_down_counter_32b_avg/U44  (
	.A1(COUNTER[14]),
	.A2(\u_up_down_counter_32b_avg/n73 ),
	.ZN(\u_up_down_counter_32b_avg/n8 ), 
	.VSS(VSS), 
	.VDD(VDD));
   IOA21D0 \u_up_down_counter_32b_avg/U42  (
	.A1(\u_up_down_counter_32b_avg/n67 ),
	.A2(COUNTER[10]),
	.B(\u_up_down_counter_32b_avg/n152 ),
	.ZN(\u_up_down_counter_32b_avg/n62 ), 
	.VSS(VSS), 
	.VDD(VDD));
   ND3D0 \u_up_down_counter_32b_avg/U41  (
	.A1(CURRENT_SOURCE_ENABLE[3]),
	.A2(\u_up_down_counter_32b_avg/n52 ),
	.A3(\u_up_down_counter_32b_avg/n218 ),
	.ZN(\u_up_down_counter_32b_avg/n10 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \u_up_down_counter_32b_avg/U39  (
	.A1(LOWER_VOLTAGE_BOUND[15]),
	.A2(\u_up_down_counter_32b_avg/n91 ),
	.Z(\u_up_down_counter_32b_avg/n6 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U38  (
	.I(\u_up_down_counter_32b_avg/n158 ),
	.ZN(\u_up_down_counter_32b_avg/n161 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_up_down_counter_32b_avg/U37  (
	.A1(COUNTER[15]),
	.A2(\u_up_down_counter_32b_avg/n159 ),
	.ZN(\u_up_down_counter_32b_avg/n158 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U36  (
	.I(\u_up_down_counter_32b_avg/n108 ),
	.ZN(\u_up_down_counter_32b_avg/n63 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2D0 \u_up_down_counter_32b_avg/U35  (
	.A1(\u_up_down_counter_32b_avg/n112 ),
	.A2(\u_up_down_counter_32b_avg/n107 ),
	.Z(\u_up_down_counter_32b_avg/n5 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OA221D0 \u_up_down_counter_32b_avg/U34  (
	.A1(COUNTER[5]),
	.A2(\u_up_down_counter_32b_avg/n80 ),
	.B1(COUNTER[6]),
	.B2(\u_up_down_counter_32b_avg/n79 ),
	.C(\u_up_down_counter_32b_avg/n84 ),
	.Z(\u_up_down_counter_32b_avg/n4 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2 \u_up_down_counter_32b_avg/U33  (
	.I(\u_up_down_counter_32b_avg/n22 ),
	.ZN(\u_up_down_counter_32b_avg/n68 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_up_down_counter_32b_avg/U32  (
	.A1(\u_up_down_counter_32b_avg/n23 ),
	.A2(LOOP_BYPASS),
	.ZN(\u_up_down_counter_32b_avg/n191 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2XD1 \u_up_down_counter_32b_avg/U31  (
	.A1(\u_up_down_counter_32b_avg/n53 ),
	.B1(LOOP_BYPASS),
	.ZN(\u_up_down_counter_32b_avg/n50 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U30  (
	.I(UPPER_VOLTAGE_BOUND[9]),
	.ZN(\u_up_down_counter_32b_avg/n149 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U29  (
	.I(UPPER_VOLTAGE_BOUND[10]),
	.ZN(\u_up_down_counter_32b_avg/n67 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U27  (
	.I(COUNTER[15]),
	.ZN(\u_up_down_counter_32b_avg/n91 ), 
	.VSS(VSS), 
	.VDD(VDD));
   IIND4D0 \u_up_down_counter_32b_avg/U26  (
	.A1(\u_up_down_counter_32b_avg/n107 ),
	.A2(\u_up_down_counter_32b_avg/n108 ),
	.B1(\u_up_down_counter_32b_avg/n110 ),
	.B2(\u_up_down_counter_32b_avg/n109 ),
	.ZN(\u_up_down_counter_32b_avg/n90 ), 
	.VSS(VSS), 
	.VDD(VDD));
   ND3D0 \u_up_down_counter_32b_avg/U25  (
	.A1(\u_up_down_counter_32b_avg/n28 ),
	.A2(\u_up_down_counter_32b_avg/n29 ),
	.A3(\u_up_down_counter_32b_avg/n123 ),
	.ZN(\u_up_down_counter_32b_avg/n146 ), 
	.VSS(VSS), 
	.VDD(VDD));
   IOA21D0 \u_up_down_counter_32b_avg/U24  (
	.A1(\u_up_down_counter_32b_avg/n156 ),
	.A2(COUNTER[12]),
	.B(\u_up_down_counter_32b_avg/n59 ),
	.ZN(\u_up_down_counter_32b_avg/n145 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \u_up_down_counter_32b_avg/U21  (
	.A1(UPPER_VOLTAGE_BOUND[13]),
	.A2(\u_up_down_counter_32b_avg/n129 ),
	.ZN(\u_up_down_counter_32b_avg/n19 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR3D0 \u_up_down_counter_32b_avg/U20  (
	.A1(\u_up_down_counter_32b_avg/n18 ),
	.A2(\u_up_down_counter_32b_avg/n19 ),
	.A3(\u_up_down_counter_32b_avg/n161 ),
	.ZN(\u_up_down_counter_32b_avg/n59 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U19  (
	.I(COUNTER[13]),
	.ZN(\u_up_down_counter_32b_avg/n129 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_up_down_counter_32b_avg/U18  (
	.A1(LOWER_VOLTAGE_BOUND[9]),
	.A2(\u_up_down_counter_32b_avg/n88 ),
	.ZN(\u_up_down_counter_32b_avg/n110 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR3D0 \u_up_down_counter_32b_avg/U17  (
	.A1(\u_up_down_counter_32b_avg/n20 ),
	.A2(\u_up_down_counter_32b_avg/n21 ),
	.A3(\u_up_down_counter_32b_avg/n22 ),
	.ZN(\u_up_down_counter_32b_avg/n23 ), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D2 \u_up_down_counter_32b_avg/U16  (
	.A1(\u_up_down_counter_32b_avg/n173 ),
	.A2(\u_up_down_counter_32b_avg/n175 ),
	.ZN(\u_up_down_counter_32b_avg/n218 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \u_up_down_counter_32b_avg/U15  (
	.I(\u_up_down_counter_32b_avg/n218 ),
	.ZN(\u_up_down_counter_32b_avg/n22 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \u_up_down_counter_32b_avg/U14  (
	.A1(\u_up_down_counter_32b_avg/n50 ),
	.A2(\u_up_down_counter_32b_avg/n218 ),
	.ZN(\u_up_down_counter_32b_avg/n7 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR3D0 \u_up_down_counter_32b_avg/U13  (
	.A1(\u_up_down_counter_32b_avg/n8 ),
	.A2(\u_up_down_counter_32b_avg/n9 ),
	.A3(\u_up_down_counter_32b_avg/n6 ),
	.ZN(\u_up_down_counter_32b_avg/n54 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI21D1 \u_up_down_counter_32b_avg/U11  (
	.A1(\u_up_down_counter_32b_avg/n174 ),
	.A2(\u_up_down_counter_32b_avg/n172 ),
	.B(COUNT_DONE),
	.ZN(\u_up_down_counter_32b_avg/n173 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D1 \u_up_down_counter_32b_avg/U10  (
	.A1(\u_up_down_counter_32b_avg/n173 ),
	.A2(\u_up_down_counter_32b_avg/n175 ),
	.ZN(\u_up_down_counter_32b_avg/n3 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OAI32D0 \u_up_down_counter_32b_avg/U9  (
	.A1(\u_up_down_counter_32b_avg/n150 ),
	.A2(COUNTER[8]),
	.A3(\u_up_down_counter_32b_avg/n64 ),
	.B1(COUNTER[9]),
	.B2(\u_up_down_counter_32b_avg/n149 ),
	.ZN(\u_up_down_counter_32b_avg/n151 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND1 \u_up_down_counter_32b_avg/U8  (
	.I(\u_up_down_counter_32b_avg/n62 ),
	.ZN(\u_up_down_counter_32b_avg/n13 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI32D0 \u_up_down_counter_32b_avg/U7  (
	.A1(UPPER_VOLTAGE_BOUND[10]),
	.A2(\u_up_down_counter_32b_avg/n153 ),
	.A3(\u_up_down_counter_32b_avg/n152 ),
	.B1(\u_up_down_counter_32b_avg/n13 ),
	.B2(\u_up_down_counter_32b_avg/n151 ),
	.ZN(\u_up_down_counter_32b_avg/n154 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \u_up_down_counter_32b_avg/U6  (
	.I(\u_up_down_counter_32b_avg/n1 ),
	.ZN(\u_up_down_counter_32b_avg/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI31D1 \u_up_down_counter_32b_avg/U4  (
	.A1(\u_up_down_counter_32b_avg/n171 ),
	.A2(\u_up_down_counter_32b_avg/n66 ),
	.A3(\u_up_down_counter_32b_avg/n170 ),
	.B(\u_up_down_counter_32b_avg/n169 ),
	.ZN(\u_up_down_counter_32b_avg/n172 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D1 \u_up_down_counter_32b_avg/U3  (
	.A1(\u_up_down_counter_32b_avg/n51 ),
	.A2(\u_up_down_counter_32b_avg/n54 ),
	.ZN(\u_up_down_counter_32b_avg/n108 ), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFCNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[16]  (
	.CDN(RST_N),
	.CP(CTS_12),
	.D(\u_up_down_counter_32b_avg/out_count_next [16]),
	.E(\u_up_down_counter_32b_avg/n68 ),
	.Q(CURRENT_SOURCE_ENABLE[16]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFSNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[2]  (
	.CP(CTS_10),
	.D(\u_up_down_counter_32b_avg/n34 ),
	.Q(CURRENT_SOURCE_ENABLE[2]),
	.SDN(\u_up_down_counter_32b_avg/n70 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFSNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[3]  (
	.CP(CTS_10),
	.D(\u_up_down_counter_32b_avg/n35 ),
	.Q(CURRENT_SOURCE_ENABLE[3]),
	.SDN(\u_up_down_counter_32b_avg/n70 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFSNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[4]  (
	.CP(CTS_10),
	.D(\u_up_down_counter_32b_avg/n36 ),
	.Q(CURRENT_SOURCE_ENABLE[4]),
	.SDN(\u_up_down_counter_32b_avg/n69 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFSNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[5]  (
	.CP(CTS_10),
	.D(\u_up_down_counter_32b_avg/n37 ),
	.Q(CURRENT_SOURCE_ENABLE[5]),
	.SDN(\u_up_down_counter_32b_avg/n69 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFSNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[6]  (
	.CP(CTS_10),
	.D(\u_up_down_counter_32b_avg/n38 ),
	.Q(CURRENT_SOURCE_ENABLE[6]),
	.SDN(\u_up_down_counter_32b_avg/n69 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFSNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[7]  (
	.CP(CTS_10),
	.D(\u_up_down_counter_32b_avg/n39 ),
	.Q(CURRENT_SOURCE_ENABLE[7]),
	.SDN(\u_up_down_counter_32b_avg/n69 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFSNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[8]  (
	.CP(CTS_10),
	.D(\u_up_down_counter_32b_avg/n40 ),
	.Q(CURRENT_SOURCE_ENABLE[8]),
	.SDN(\u_up_down_counter_32b_avg/n69 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFSNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[1]  (
	.CP(CTS_10),
	.D(\u_up_down_counter_32b_avg/n33 ),
	.Q(CURRENT_SOURCE_ENABLE[1]),
	.SDN(\u_up_down_counter_32b_avg/n70 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFSNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[14]  (
	.CP(CTS_12),
	.D(\u_up_down_counter_32b_avg/n46 ),
	.Q(CURRENT_SOURCE_ENABLE[14]),
	.SDN(\u_up_down_counter_32b_avg/n69 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFSNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[15]  (
	.CP(CTS_12),
	.D(\u_up_down_counter_32b_avg/n47 ),
	.Q(CURRENT_SOURCE_ENABLE[15]),
	.SDN(\u_up_down_counter_32b_avg/n69 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFSNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[0]  (
	.CP(CTS_10),
	.D(\u_up_down_counter_32b_avg/n48 ),
	.Q(CURRENT_SOURCE_ENABLE[0]),
	.SDN(\u_up_down_counter_32b_avg/n69 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFSNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[9]  (
	.CP(CTS_10),
	.D(\u_up_down_counter_32b_avg/n41 ),
	.Q(CURRENT_SOURCE_ENABLE[9]),
	.SDN(\u_up_down_counter_32b_avg/n69 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFSNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[13]  (
	.CP(CTS_10),
	.D(\u_up_down_counter_32b_avg/n45 ),
	.Q(CURRENT_SOURCE_ENABLE[13]),
	.SDN(\u_up_down_counter_32b_avg/n69 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFSNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[12]  (
	.CP(CTS_12),
	.D(\u_up_down_counter_32b_avg/n44 ),
	.Q(CURRENT_SOURCE_ENABLE[12]),
	.SDN(\u_up_down_counter_32b_avg/n69 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFSNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[11]  (
	.CP(CTS_10),
	.D(\u_up_down_counter_32b_avg/n43 ),
	.Q(CURRENT_SOURCE_ENABLE[11]),
	.SDN(\u_up_down_counter_32b_avg/n69 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFSNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[10]  (
	.CP(CTS_10),
	.D(\u_up_down_counter_32b_avg/n42 ),
	.Q(CURRENT_SOURCE_ENABLE[10]),
	.SDN(\u_up_down_counter_32b_avg/n69 ), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFCNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[17]  (
	.CDN(RST_N),
	.CP(CTS_12),
	.D(\u_up_down_counter_32b_avg/out_count_next [17]),
	.E(\u_up_down_counter_32b_avg/n68 ),
	.Q(CURRENT_SOURCE_ENABLE[17]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFCNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[18]  (
	.CDN(RST_N),
	.CP(CTS_12),
	.D(\u_up_down_counter_32b_avg/out_count_next [18]),
	.E(\u_up_down_counter_32b_avg/n68 ),
	.Q(CURRENT_SOURCE_ENABLE[18]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFCNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[19]  (
	.CDN(RST_N),
	.CP(CTS_12),
	.D(\u_up_down_counter_32b_avg/out_count_next [19]),
	.E(\u_up_down_counter_32b_avg/n68 ),
	.Q(CURRENT_SOURCE_ENABLE[19]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFCNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[20]  (
	.CDN(RST_N),
	.CP(CTS_12),
	.D(\u_up_down_counter_32b_avg/out_count_next [20]),
	.E(\u_up_down_counter_32b_avg/n68 ),
	.Q(CURRENT_SOURCE_ENABLE[20]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFCNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[21]  (
	.CDN(RST_N),
	.CP(CTS_12),
	.D(\u_up_down_counter_32b_avg/out_count_next [21]),
	.E(\u_up_down_counter_32b_avg/n68 ),
	.Q(CURRENT_SOURCE_ENABLE[21]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFCNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[22]  (
	.CDN(\u_up_down_counter_32b_avg/n70 ),
	.CP(CTS_11),
	.D(\u_up_down_counter_32b_avg/out_count_next [22]),
	.E(\u_up_down_counter_32b_avg/n68 ),
	.Q(CURRENT_SOURCE_ENABLE[22]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFCNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[23]  (
	.CDN(\u_up_down_counter_32b_avg/n70 ),
	.CP(CTS_11),
	.D(\u_up_down_counter_32b_avg/out_count_next [23]),
	.E(\u_up_down_counter_32b_avg/n68 ),
	.Q(CURRENT_SOURCE_ENABLE[23]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFCNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[24]  (
	.CDN(\u_up_down_counter_32b_avg/n70 ),
	.CP(CTS_11),
	.D(\u_up_down_counter_32b_avg/out_count_next [24]),
	.E(\u_up_down_counter_32b_avg/n68 ),
	.Q(CURRENT_SOURCE_ENABLE[24]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFCNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[25]  (
	.CDN(\u_up_down_counter_32b_avg/n70 ),
	.CP(CTS_11),
	.D(\u_up_down_counter_32b_avg/out_count_next [25]),
	.E(\u_up_down_counter_32b_avg/n68 ),
	.Q(CURRENT_SOURCE_ENABLE[25]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFCNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[26]  (
	.CDN(\u_up_down_counter_32b_avg/n70 ),
	.CP(CTS_11),
	.D(\u_up_down_counter_32b_avg/out_count_next [26]),
	.E(\u_up_down_counter_32b_avg/n68 ),
	.Q(CURRENT_SOURCE_ENABLE[26]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFCNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[27]  (
	.CDN(\u_up_down_counter_32b_avg/n70 ),
	.CP(CTS_11),
	.D(\u_up_down_counter_32b_avg/out_count_next [27]),
	.E(\u_up_down_counter_32b_avg/n68 ),
	.Q(CURRENT_SOURCE_ENABLE[27]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFCNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[28]  (
	.CDN(\u_up_down_counter_32b_avg/n70 ),
	.CP(CTS_11),
	.D(\u_up_down_counter_32b_avg/out_count_next [28]),
	.E(\u_up_down_counter_32b_avg/n68 ),
	.Q(CURRENT_SOURCE_ENABLE[28]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFCNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[29]  (
	.CDN(\u_up_down_counter_32b_avg/n70 ),
	.CP(CTS_11),
	.D(\u_up_down_counter_32b_avg/out_count_next [29]),
	.E(\u_up_down_counter_32b_avg/n68 ),
	.Q(CURRENT_SOURCE_ENABLE[29]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFCNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[30]  (
	.CDN(\u_up_down_counter_32b_avg/n70 ),
	.CP(CTS_11),
	.D(\u_up_down_counter_32b_avg/out_count_next [30]),
	.E(\u_up_down_counter_32b_avg/n68 ),
	.Q(CURRENT_SOURCE_ENABLE[30]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFCNQD1 \u_up_down_counter_32b_avg/OUT_COUNT_reg[31]  (
	.CDN(\u_up_down_counter_32b_avg/n70 ),
	.CP(CTS_11),
	.D(\u_up_down_counter_32b_avg/out_count_next [31]),
	.E(\u_up_down_counter_32b_avg/n68 ),
	.Q(CURRENT_SOURCE_ENABLE[31]), 
	.VSS(VSS), 
	.VDD(VDD));
endmodule

