/*
###############################################################
#  Generated by:      Cadence Innovus 16.12-s051_1
#  OS:                Linux x86_64(Host ID ecegrid-thin7.ecn.purdue.edu)
#  Generated on:      Tue Apr  7 21:49:13 2020
#  Design:            oscillator_counter
#  Command:           saveNetlist /home/sparclab/a/ghosh69/march_20_tapeout/current_source_controller/logs/oscillator_counter_power.gate.v -includepowerground -excludeLeafCell
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : L-2016.03-SP2
// Date      : Thu Apr  2 16:53:23 2020
/////////////////////////////////////////////////////////////
module oscillator_counter (
	OSC_OUT, 
	COUNT_DONE, 
	COUNTER, 
	RST_N, 
	VDD, 
	VSS);
   input OSC_OUT;
   input COUNT_DONE;
   output [15:0] COUNTER;
   input RST_N;
   inout VDD;
   inout VSS;

   // Internal wires
   wire CTS_8;
   wire CTS_7;
   wire N4;
   wire N5;
   wire N6;
   wire N7;
   wire N8;
   wire N9;
   wire N10;
   wire N11;
   wire N12;
   wire N13;
   wire N14;
   wire N15;
   wire N16;
   wire N17;
   wire N18;
   wire N19;
   wire n3;
   wire n4;
   wire n6;
   wire n7;
   wire \add_26/n86 ;
   wire \add_26/n85 ;
   wire \add_26/n84 ;
   wire \add_26/n83 ;
   wire \add_26/n43 ;
   wire \add_26/n42 ;
   wire \add_26/n36 ;
   wire \add_26/n35 ;
   wire \add_26/n34 ;
   wire \add_26/n33 ;
   wire \add_26/n27 ;
   wire \add_26/n26 ;
   wire \add_26/n18 ;
   wire \add_26/n17 ;
   wire \add_26/n16 ;
   wire \add_26/n14 ;
   wire \add_26/n13 ;
   wire \add_26/n12 ;
   wire \add_26/n8 ;
   wire \add_26/n7 ;
   wire \add_26/n4 ;
   wire \add_26/n3 ;
   wire \add_26/n2 ;
   wire \add_26/n1 ;
   wire [15:0] internal_counter;

   // Module instantiations
   CKBD4 CTS_ccl_BUF_OSC_OUT_G0_L1_2 (
	.I(OSC_OUT),
	.Z(CTS_8), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD4 CTS_ccl_BUF_OSC_OUT_G0_L1_1 (
	.I(OSC_OUT),
	.Z(CTS_7), 
	.VSS(VSS), 
	.VDD(VDD));
   IND4D0 FE_RC_0_0 (
	.A1(\add_26/n27 ),
	.B1(internal_counter[6]),
	.B2(internal_counter[7]),
	.B3(\add_26/n35 ),
	.ZN(\add_26/n18 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \internal_counter_reg[0]  (
	.CDN(n4),
	.CP(CTS_7),
	.D(N4),
	.Q(internal_counter[0]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \internal_counter_reg[1]  (
	.CDN(n4),
	.CP(CTS_7),
	.D(N5),
	.Q(internal_counter[1]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \internal_counter_reg[2]  (
	.CDN(n3),
	.CP(CTS_7),
	.D(N6),
	.Q(internal_counter[2]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \internal_counter_reg[3]  (
	.CDN(n3),
	.CP(CTS_7),
	.D(N7),
	.Q(internal_counter[3]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \internal_counter_reg[4]  (
	.CDN(n3),
	.CP(CTS_7),
	.D(N8),
	.Q(internal_counter[4]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \internal_counter_reg[5]  (
	.CDN(n3),
	.CP(CTS_7),
	.D(N9),
	.Q(internal_counter[5]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \internal_counter_reg[6]  (
	.CDN(n3),
	.CP(CTS_7),
	.D(N10),
	.Q(internal_counter[6]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \internal_counter_reg[7]  (
	.CDN(n3),
	.CP(CTS_8),
	.D(N11),
	.Q(internal_counter[7]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \internal_counter_reg[8]  (
	.CDN(n3),
	.CP(CTS_8),
	.D(N12),
	.Q(internal_counter[8]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \internal_counter_reg[9]  (
	.CDN(n3),
	.CP(CTS_8),
	.D(N13),
	.Q(internal_counter[9]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \internal_counter_reg[10]  (
	.CDN(n3),
	.CP(CTS_8),
	.D(N14),
	.Q(internal_counter[10]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \internal_counter_reg[11]  (
	.CDN(n3),
	.CP(CTS_8),
	.D(N15),
	.Q(internal_counter[11]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \internal_counter_reg[12]  (
	.CDN(n3),
	.CP(CTS_7),
	.D(N16),
	.Q(internal_counter[12]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \internal_counter_reg[13]  (
	.CDN(n3),
	.CP(CTS_7),
	.D(N17),
	.Q(internal_counter[13]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \internal_counter_reg[14]  (
	.CDN(n3),
	.CP(CTS_8),
	.D(N18),
	.Q(internal_counter[14]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \internal_counter_reg[15]  (
	.CDN(n4),
	.CP(CTS_8),
	.D(N19),
	.Q(internal_counter[15]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFQD1 \COUNTER_reg[0]  (
	.CP(CTS_8),
	.D(internal_counter[0]),
	.E(n7),
	.Q(COUNTER[0]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFQD1 \COUNTER_reg[1]  (
	.CP(CTS_8),
	.D(internal_counter[1]),
	.E(n7),
	.Q(COUNTER[1]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFQD1 \COUNTER_reg[2]  (
	.CP(CTS_7),
	.D(internal_counter[2]),
	.E(n7),
	.Q(COUNTER[2]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFQD1 \COUNTER_reg[3]  (
	.CP(CTS_7),
	.D(internal_counter[3]),
	.E(n7),
	.Q(COUNTER[3]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFQD1 \COUNTER_reg[4]  (
	.CP(CTS_7),
	.D(internal_counter[4]),
	.E(n7),
	.Q(COUNTER[4]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFQD1 \COUNTER_reg[5]  (
	.CP(CTS_7),
	.D(internal_counter[5]),
	.E(n7),
	.Q(COUNTER[5]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFQD1 \COUNTER_reg[6]  (
	.CP(CTS_7),
	.D(internal_counter[6]),
	.E(n4),
	.Q(COUNTER[6]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFQD1 \COUNTER_reg[7]  (
	.CP(CTS_8),
	.D(internal_counter[7]),
	.E(n4),
	.Q(COUNTER[7]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFQD1 \COUNTER_reg[8]  (
	.CP(CTS_8),
	.D(internal_counter[8]),
	.E(n4),
	.Q(COUNTER[8]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFQD1 \COUNTER_reg[9]  (
	.CP(CTS_8),
	.D(internal_counter[9]),
	.E(n4),
	.Q(COUNTER[9]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFQD1 \COUNTER_reg[10]  (
	.CP(CTS_8),
	.D(internal_counter[10]),
	.E(n4),
	.Q(COUNTER[10]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFQD1 \COUNTER_reg[11]  (
	.CP(CTS_8),
	.D(internal_counter[11]),
	.E(n4),
	.Q(COUNTER[11]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFQD1 \COUNTER_reg[12]  (
	.CP(CTS_7),
	.D(internal_counter[12]),
	.E(n4),
	.Q(COUNTER[12]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFQD1 \COUNTER_reg[13]  (
	.CP(CTS_7),
	.D(internal_counter[13]),
	.E(n4),
	.Q(COUNTER[13]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFQD1 \COUNTER_reg[14]  (
	.CP(CTS_8),
	.D(internal_counter[14]),
	.E(n4),
	.Q(COUNTER[14]), 
	.VSS(VSS), 
	.VDD(VDD));
   EDFQD1 \COUNTER_reg[15]  (
	.CP(CTS_8),
	.D(internal_counter[15]),
	.E(n4),
	.Q(COUNTER[15]), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFFD1 U5 (
	.I(n7),
	.Z(n3), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFFD1 U6 (
	.I(n7),
	.Z(n4), 
	.VSS(VSS), 
	.VDD(VDD));
   IND2D0 U8 (
	.A1(COUNT_DONE),
	.B1(RST_N),
	.ZN(n6), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 U9 (
	.I(n6),
	.ZN(n7), 
	.VSS(VSS), 
	.VDD(VDD));
   HICIND1 \add_26/U98  (
	.A(internal_counter[14]),
	.CIN(\add_26/n2 ),
	.CO(\add_26/n1 ),
	.S(N18), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \add_26/U97  (
	.A1(\add_26/n12 ),
	.A2(internal_counter[10]),
	.ZN(\add_26/n8 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \add_26/U96  (
	.A1(\add_26/n18 ),
	.A2(\add_26/n8 ),
	.ZN(\add_26/n7 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \add_26/U95  (
	.A1(internal_counter[2]),
	.A2(internal_counter[3]),
	.ZN(\add_26/n36 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \add_26/U94  (
	.A1(\add_26/n36 ),
	.A2(\add_26/n43 ),
	.ZN(\add_26/n35 ), 
	.VSS(VSS), 
	.VDD(VDD));
   HICIND1 \add_26/U93  (
	.A(internal_counter[12]),
	.CIN(\add_26/n4 ),
	.CO(\add_26/n3 ),
	.S(N16), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \add_26/U92  (
	.A1(\add_26/n26 ),
	.A2(internal_counter[6]),
	.Z(N10), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \add_26/U91  (
	.A1(\add_26/n7 ),
	.A2(internal_counter[11]),
	.Z(N15), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \add_26/U90  (
	.A1(\add_26/n42 ),
	.A2(internal_counter[2]),
	.Z(N6), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2D0 \add_26/U89  (
	.A1(\add_26/n34 ),
	.A2(\add_26/n33 ),
	.Z(\add_26/n86 ), 
	.VSS(VSS), 
	.VDD(VDD));
   XNR2D0 \add_26/U88  (
	.A1(\add_26/n86 ),
	.A2(internal_counter[5]),
	.ZN(N9), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \add_26/U87  (
	.A1(\add_26/n17 ),
	.A2(internal_counter[8]),
	.ZN(\add_26/n14 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \add_26/U86  (
	.A1(\add_26/n14 ),
	.A2(\add_26/n13 ),
	.Z(N13), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \add_26/U85  (
	.A1(\add_26/n42 ),
	.A2(internal_counter[2]),
	.Z(\add_26/n85 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \add_26/U84  (
	.A1(\add_26/n85 ),
	.A2(internal_counter[3]),
	.Z(N7), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \add_26/U83  (
	.A1(\add_26/n26 ),
	.A2(internal_counter[6]),
	.Z(\add_26/n84 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \add_26/U82  (
	.A1(\add_26/n84 ),
	.A2(internal_counter[7]),
	.Z(N11), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D0 \add_26/U81  (
	.A1(\add_26/n17 ),
	.A2(\add_26/n12 ),
	.Z(\add_26/n83 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \add_26/U80  (
	.A1(\add_26/n83 ),
	.A2(internal_counter[10]),
	.Z(N14), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \add_26/U77  (
	.I(internal_counter[9]),
	.ZN(\add_26/n13 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \add_26/U76  (
	.A1(internal_counter[1]),
	.A2(internal_counter[0]),
	.ZN(\add_26/n43 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \add_26/U75  (
	.I(internal_counter[8]),
	.ZN(\add_26/n16 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \add_26/U74  (
	.I(internal_counter[4]),
	.ZN(\add_26/n33 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \add_26/U73  (
	.A1(internal_counter[4]),
	.A2(internal_counter[5]),
	.ZN(\add_26/n27 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \add_26/U72  (
	.A1(\add_26/n16 ),
	.A2(\add_26/n13 ),
	.ZN(\add_26/n12 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0 \add_26/U71  (
	.A1(\add_26/n34 ),
	.A2(\add_26/n27 ),
	.ZN(\add_26/n26 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \add_26/U70  (
	.A1(\add_26/n34 ),
	.A2(\add_26/n33 ),
	.Z(N8), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \add_26/U69  (
	.I(\add_26/n18 ),
	.ZN(\add_26/n17 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \add_26/U68  (
	.I(\add_26/n35 ),
	.ZN(\add_26/n34 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND2D0 \add_26/U67  (
	.A1(\add_26/n7 ),
	.A2(internal_counter[11]),
	.ZN(\add_26/n4 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \add_26/U66  (
	.I(internal_counter[0]),
	.ZN(N4), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \add_26/U65  (
	.A1(\add_26/n1 ),
	.A2(internal_counter[15]),
	.Z(N19), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D0 \add_26/U64  (
	.A1(internal_counter[1]),
	.A2(internal_counter[0]),
	.Z(N5), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND0 \add_26/U62  (
	.I(\add_26/n43 ),
	.ZN(\add_26/n42 ), 
	.VSS(VSS), 
	.VDD(VDD));
   XNR2D0 \add_26/U18  (
	.A1(\add_26/n17 ),
	.A2(\add_26/n16 ),
	.ZN(N12), 
	.VSS(VSS), 
	.VDD(VDD));
   HICOND1 \add_26/U3  (
	.A(\add_26/n3 ),
	.CI(internal_counter[13]),
	.CON(\add_26/n2 ),
	.S(N17), 
	.VSS(VSS), 
	.VDD(VDD));
endmodule

