/*
###############################################################
#  Generated by:      Cadence Innovus 16.12-s051_1
#  OS:                Linux x86_64(Host ID ecegrid-thin3.ecn.purdue.edu)
#  Generated on:      Mon Apr 20 17:49:28 2020
#  Design:            ring_oscillator_3_stage_array_4
#  Command:           saveNetlist /home/sparclab/a/ghosh69/march_20_tapeout/current_source_controller/logs/ring_oscillator_3_stage_array_4_power.gate.v -includepowerground -excludeLeafCell
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : L-2016.03-SP2
// Date      : Sat Apr  4 22:41:04 2020
/////////////////////////////////////////////////////////////
module ring_oscillator_3_stage_array_4 (
	start, 
	osc_out, 
	VDD, 
	VSS);
   input [3:0] start;
   output [3:0] osc_out;
   inout VDD;
   inout VSS;

   // Internal wires
   wire n0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;

   // Module instantiations
   ND2D0 U1 (
	.A1(osc_out[0]),
	.A2(start[0]),
	.ZN(n0), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD0 N0 (
	.I(n0),
	.ZN(n1), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD0 N1 (
	.I(n1),
	.ZN(osc_out[0]), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D0 U2 (
	.A1(osc_out[1]),
	.A2(start[1]),
	.ZN(n2), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD0 N2 (
	.I(n2),
	.ZN(n3), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD0 N3 (
	.I(n3),
	.ZN(osc_out[1]), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D0 U3 (
	.A1(osc_out[2]),
	.A2(start[2]),
	.ZN(n4), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD0 N4 (
	.I(n4),
	.ZN(n5), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD0 N5 (
	.I(n5),
	.ZN(osc_out[2]), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D0 U4 (
	.A1(osc_out[3]),
	.A2(start[3]),
	.ZN(n6), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD0 N6 (
	.I(n6),
	.ZN(n7), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD0 N7 (
	.I(n7),
	.ZN(osc_out[3]), 
	.VSS(VSS), 
	.VDD(VDD));
endmodule

