/*
###############################################################
#  Generated by:      Cadence Innovus 16.12-s051_1
#  OS:                Linux x86_64(Host ID ecegrid-thin3.ecn.purdue.edu)
#  Generated on:      Thu Apr 23 01:23:29 2020
#  Design:            scan_chain_both
#  Command:           saveNetlist /home/sparclab/a/ghosh69/march_20_tapeout/current_source_controller/logs/scan_chain_both_power.gate.v -includepowerground -excludeLeafCell
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : L-2016.03-SP2
// Date      : Wed Apr 22 15:41:34 2020
/////////////////////////////////////////////////////////////
module scan_chain_both (
	SC_CLK1, 
	SC_CLK2, 
	RST_N, 
	SCAN_IN, 
	UPDATE, 
	CAPTURE, 
	PAR_IN, 
	SCAN_OUT, 
	SCAN_REG, 
	VDD, 
	VSS);
   input SC_CLK1;
   input SC_CLK2;
   input RST_N;
   input SCAN_IN;
   input UPDATE;
   input CAPTURE;
   input [28:0] PAR_IN;
   output SCAN_OUT;
   output [28:0] SCAN_REG;
   inout VDD;
   inout VSS;

   // Internal wires
   wire \sc/n6 ;
   wire \sc/n5 ;
   wire \sc/n4 ;
   wire \sc/n3 ;
   wire \sc/n2 ;
   wire \sc/n1 ;
   wire \sc/sc0/n1 ;
   wire \sc/sc0/pos_latch2_in ;
   wire \sc/sc0/pos_latch2_out ;
   wire \sc/sc0/pos_latch1_out ;
   wire \sc/genblk1[0].sci/n2 ;
   wire \sc/genblk1[0].sci/n1 ;
   wire \sc/genblk1[0].sci/pos_latch2_in ;
   wire \sc/genblk1[0].sci/pos_latch2_out ;
   wire \sc/genblk1[0].sci/pos_latch1_out ;
   wire \sc/genblk1[1].sci/n2 ;
   wire \sc/genblk1[1].sci/n1 ;
   wire \sc/genblk1[1].sci/pos_latch2_in ;
   wire \sc/genblk1[1].sci/pos_latch2_out ;
   wire \sc/genblk1[1].sci/pos_latch1_out ;
   wire \sc/genblk1[2].sci/n2 ;
   wire \sc/genblk1[2].sci/n1 ;
   wire \sc/genblk1[2].sci/pos_latch2_in ;
   wire \sc/genblk1[2].sci/pos_latch2_out ;
   wire \sc/genblk1[2].sci/pos_latch1_out ;
   wire \sc/genblk1[3].sci/n2 ;
   wire \sc/genblk1[3].sci/n1 ;
   wire \sc/genblk1[3].sci/pos_latch2_in ;
   wire \sc/genblk1[3].sci/pos_latch2_out ;
   wire \sc/genblk1[3].sci/pos_latch1_out ;
   wire \sc/genblk1[4].sci/n2 ;
   wire \sc/genblk1[4].sci/n1 ;
   wire \sc/genblk1[4].sci/pos_latch2_in ;
   wire \sc/genblk1[4].sci/pos_latch2_out ;
   wire \sc/genblk1[4].sci/pos_latch1_out ;
   wire \sc/genblk1[5].sci/n2 ;
   wire \sc/genblk1[5].sci/n1 ;
   wire \sc/genblk1[5].sci/pos_latch2_in ;
   wire \sc/genblk1[5].sci/pos_latch2_out ;
   wire \sc/genblk1[5].sci/pos_latch1_out ;
   wire \sc/genblk1[6].sci/n2 ;
   wire \sc/genblk1[6].sci/n1 ;
   wire \sc/genblk1[6].sci/pos_latch2_in ;
   wire \sc/genblk1[6].sci/pos_latch2_out ;
   wire \sc/genblk1[6].sci/pos_latch1_out ;
   wire \sc/genblk1[7].sci/n1 ;
   wire \sc/genblk1[7].sci/pos_latch2_in ;
   wire \sc/genblk1[7].sci/pos_latch2_out ;
   wire \sc/genblk1[7].sci/pos_latch1_out ;
   wire \sc/genblk1[8].sci/n1 ;
   wire \sc/genblk1[8].sci/pos_latch2_in ;
   wire \sc/genblk1[8].sci/pos_latch2_out ;
   wire \sc/genblk1[8].sci/pos_latch1_out ;
   wire \sc/genblk1[9].sci/n1 ;
   wire \sc/genblk1[9].sci/pos_latch2_in ;
   wire \sc/genblk1[9].sci/pos_latch2_out ;
   wire \sc/genblk1[9].sci/pos_latch1_out ;
   wire \sc/genblk1[10].sci/n1 ;
   wire \sc/genblk1[10].sci/pos_latch2_in ;
   wire \sc/genblk1[10].sci/pos_latch2_out ;
   wire \sc/genblk1[10].sci/pos_latch1_out ;
   wire \sc/genblk1[11].sci/n1 ;
   wire \sc/genblk1[11].sci/pos_latch2_in ;
   wire \sc/genblk1[11].sci/pos_latch2_out ;
   wire \sc/genblk1[11].sci/pos_latch1_out ;
   wire \sc/genblk1[12].sci/n2 ;
   wire \sc/genblk1[12].sci/n1 ;
   wire \sc/genblk1[12].sci/pos_latch2_in ;
   wire \sc/genblk1[12].sci/pos_latch2_out ;
   wire \sc/genblk1[12].sci/pos_latch1_out ;
   wire \sc/genblk1[13].sci/n2 ;
   wire \sc/genblk1[13].sci/n1 ;
   wire \sc/genblk1[13].sci/pos_latch2_in ;
   wire \sc/genblk1[13].sci/pos_latch2_out ;
   wire \sc/genblk1[13].sci/pos_latch1_out ;
   wire \sc/genblk1[14].sci/n2 ;
   wire \sc/genblk1[14].sci/n1 ;
   wire \sc/genblk1[14].sci/pos_latch2_in ;
   wire \sc/genblk1[14].sci/pos_latch2_out ;
   wire \sc/genblk1[14].sci/pos_latch1_out ;
   wire \sc/genblk1[15].sci/n2 ;
   wire \sc/genblk1[15].sci/n1 ;
   wire \sc/genblk1[15].sci/pos_latch2_in ;
   wire \sc/genblk1[15].sci/pos_latch2_out ;
   wire \sc/genblk1[15].sci/pos_latch1_out ;
   wire \sc/genblk1[16].sci/n2 ;
   wire \sc/genblk1[16].sci/n1 ;
   wire \sc/genblk1[16].sci/pos_latch2_in ;
   wire \sc/genblk1[16].sci/pos_latch2_out ;
   wire \sc/genblk1[16].sci/pos_latch1_out ;
   wire \sc/genblk1[17].sci/n2 ;
   wire \sc/genblk1[17].sci/n1 ;
   wire \sc/genblk1[17].sci/pos_latch2_in ;
   wire \sc/genblk1[17].sci/pos_latch2_out ;
   wire \sc/genblk1[17].sci/pos_latch1_out ;
   wire \sc/genblk1[18].sci/n2 ;
   wire \sc/genblk1[18].sci/n1 ;
   wire \sc/genblk1[18].sci/pos_latch2_in ;
   wire \sc/genblk1[18].sci/pos_latch2_out ;
   wire \sc/genblk1[18].sci/pos_latch1_out ;
   wire \sc/genblk1[19].sci/n1 ;
   wire \sc/genblk1[19].sci/pos_latch2_in ;
   wire \sc/genblk1[19].sci/pos_latch2_out ;
   wire \sc/genblk1[19].sci/pos_latch1_out ;
   wire \sc/genblk1[20].sci/n1 ;
   wire \sc/genblk1[20].sci/pos_latch2_in ;
   wire \sc/genblk1[20].sci/pos_latch2_out ;
   wire \sc/genblk1[20].sci/pos_latch1_out ;
   wire \sc/genblk1[21].sci/n1 ;
   wire \sc/genblk1[21].sci/pos_latch2_in ;
   wire \sc/genblk1[21].sci/pos_latch2_out ;
   wire \sc/genblk1[21].sci/pos_latch1_out ;
   wire \sc/genblk1[22].sci/n1 ;
   wire \sc/genblk1[22].sci/pos_latch2_in ;
   wire \sc/genblk1[22].sci/pos_latch2_out ;
   wire \sc/genblk1[22].sci/pos_latch1_out ;
   wire \sc/genblk1[23].sci/n1 ;
   wire \sc/genblk1[23].sci/pos_latch2_in ;
   wire \sc/genblk1[23].sci/pos_latch2_out ;
   wire \sc/genblk1[23].sci/pos_latch1_out ;
   wire \sc/genblk1[24].sci/n1 ;
   wire \sc/genblk1[24].sci/pos_latch2_in ;
   wire \sc/genblk1[24].sci/pos_latch2_out ;
   wire \sc/genblk1[24].sci/pos_latch1_out ;
   wire \sc/genblk1[25].sci/n1 ;
   wire \sc/genblk1[25].sci/pos_latch2_in ;
   wire \sc/genblk1[25].sci/pos_latch2_out ;
   wire \sc/genblk1[25].sci/pos_latch1_out ;
   wire \sc/genblk1[26].sci/n1 ;
   wire \sc/genblk1[26].sci/pos_latch2_in ;
   wire \sc/genblk1[26].sci/pos_latch2_out ;
   wire \sc/genblk1[26].sci/pos_latch1_out ;
   wire \sc/scN/n1 ;
   wire \sc/scN/pos_latch2_in ;
   wire \sc/scN/pos_latch2_out ;
   wire \sc/scN/pos_latch1_out ;
   wire [27:0] \sc/scan_array ;

   // Module instantiations
   CKBD1 \sc/U6  (
	.I(RST_N),
	.Z(\sc/n6 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD1 \sc/U5  (
	.I(RST_N),
	.Z(\sc/n4 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD1 \sc/U4  (
	.I(RST_N),
	.Z(\sc/n5 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD1 \sc/U3  (
	.I(CAPTURE),
	.Z(\sc/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD1 \sc/U2  (
	.I(CAPTURE),
	.Z(\sc/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD1 \sc/U1  (
	.I(CAPTURE),
	.Z(\sc/n3 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/sc0/U5  (
	.A1(\sc/n3 ),
	.A2(PAR_IN[0]),
	.B1(\sc/sc0/pos_latch1_out ),
	.B2(\sc/sc0/n1 ),
	.Z(\sc/sc0/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/sc0/U4  (
	.A1(\sc/n3 ),
	.A2(PAR_IN[0]),
	.B1(\sc/sc0/pos_latch2_out ),
	.B2(\sc/sc0/n1 ),
	.Z(\sc/scan_array [0]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/sc0/U3  (
	.I(\sc/n3 ),
	.ZN(\sc/sc0/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/sc0/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n4 ),
	.CP(UPDATE),
	.D(\sc/sc0/pos_latch2_out ),
	.Q(SCAN_REG[0]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/sc0/pos_latch2_out_reg  (
	.D(\sc/sc0/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/sc0/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/sc0/pos_latch1_out_reg  (
	.D(SCAN_IN),
	.E(SC_CLK1),
	.Q(\sc/sc0/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[0].sci/U6  (
	.A1(\sc/genblk1[0].sci/n1 ),
	.A2(PAR_IN[1]),
	.B1(\sc/genblk1[0].sci/pos_latch1_out ),
	.B2(\sc/genblk1[0].sci/n2 ),
	.Z(\sc/genblk1[0].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[0].sci/U5  (
	.A1(\sc/genblk1[0].sci/n1 ),
	.A2(PAR_IN[1]),
	.B1(\sc/genblk1[0].sci/pos_latch2_out ),
	.B2(\sc/genblk1[0].sci/n2 ),
	.Z(\sc/scan_array [1]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[0].sci/U4  (
	.I(\sc/n1 ),
	.ZN(\sc/genblk1[0].sci/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[0].sci/U3  (
	.I(\sc/genblk1[0].sci/n2 ),
	.ZN(\sc/genblk1[0].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[0].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n6 ),
	.CP(UPDATE),
	.D(\sc/genblk1[0].sci/pos_latch2_out ),
	.Q(SCAN_REG[1]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[0].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[0].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[0].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[0].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [0]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[0].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[1].sci/U6  (
	.A1(\sc/genblk1[1].sci/n1 ),
	.A2(PAR_IN[2]),
	.B1(\sc/genblk1[1].sci/pos_latch1_out ),
	.B2(\sc/genblk1[1].sci/n2 ),
	.Z(\sc/genblk1[1].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[1].sci/U5  (
	.A1(\sc/genblk1[1].sci/n1 ),
	.A2(PAR_IN[2]),
	.B1(\sc/genblk1[1].sci/pos_latch2_out ),
	.B2(\sc/genblk1[1].sci/n2 ),
	.Z(\sc/scan_array [2]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[1].sci/U4  (
	.I(\sc/n1 ),
	.ZN(\sc/genblk1[1].sci/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[1].sci/U3  (
	.I(\sc/genblk1[1].sci/n2 ),
	.ZN(\sc/genblk1[1].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[1].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n6 ),
	.CP(UPDATE),
	.D(\sc/genblk1[1].sci/pos_latch2_out ),
	.Q(SCAN_REG[2]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[1].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[1].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[1].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[1].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [1]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[1].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[2].sci/U6  (
	.A1(\sc/genblk1[2].sci/n1 ),
	.A2(PAR_IN[3]),
	.B1(\sc/genblk1[2].sci/pos_latch1_out ),
	.B2(\sc/genblk1[2].sci/n2 ),
	.Z(\sc/genblk1[2].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[2].sci/U5  (
	.A1(\sc/genblk1[2].sci/n1 ),
	.A2(PAR_IN[3]),
	.B1(\sc/genblk1[2].sci/pos_latch2_out ),
	.B2(\sc/genblk1[2].sci/n2 ),
	.Z(\sc/scan_array [3]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[2].sci/U4  (
	.I(\sc/n1 ),
	.ZN(\sc/genblk1[2].sci/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[2].sci/U3  (
	.I(\sc/genblk1[2].sci/n2 ),
	.ZN(\sc/genblk1[2].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[2].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n6 ),
	.CP(UPDATE),
	.D(\sc/genblk1[2].sci/pos_latch2_out ),
	.Q(SCAN_REG[3]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[2].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[2].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[2].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[2].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [2]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[2].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[3].sci/U6  (
	.A1(\sc/genblk1[3].sci/n1 ),
	.A2(PAR_IN[4]),
	.B1(\sc/genblk1[3].sci/pos_latch1_out ),
	.B2(\sc/genblk1[3].sci/n2 ),
	.Z(\sc/genblk1[3].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[3].sci/U5  (
	.A1(\sc/genblk1[3].sci/n1 ),
	.A2(PAR_IN[4]),
	.B1(\sc/genblk1[3].sci/pos_latch2_out ),
	.B2(\sc/genblk1[3].sci/n2 ),
	.Z(\sc/scan_array [4]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[3].sci/U4  (
	.I(\sc/n1 ),
	.ZN(\sc/genblk1[3].sci/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[3].sci/U3  (
	.I(\sc/genblk1[3].sci/n2 ),
	.ZN(\sc/genblk1[3].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[3].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n5 ),
	.CP(UPDATE),
	.D(\sc/genblk1[3].sci/pos_latch2_out ),
	.Q(SCAN_REG[4]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[3].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[3].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[3].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[3].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [3]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[3].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[4].sci/U6  (
	.A1(\sc/genblk1[4].sci/n1 ),
	.A2(PAR_IN[5]),
	.B1(\sc/genblk1[4].sci/pos_latch1_out ),
	.B2(\sc/genblk1[4].sci/n2 ),
	.Z(\sc/genblk1[4].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[4].sci/U5  (
	.A1(\sc/genblk1[4].sci/n1 ),
	.A2(PAR_IN[5]),
	.B1(\sc/genblk1[4].sci/pos_latch2_out ),
	.B2(\sc/genblk1[4].sci/n2 ),
	.Z(\sc/scan_array [5]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[4].sci/U4  (
	.I(\sc/n1 ),
	.ZN(\sc/genblk1[4].sci/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[4].sci/U3  (
	.I(\sc/genblk1[4].sci/n2 ),
	.ZN(\sc/genblk1[4].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[4].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n5 ),
	.CP(UPDATE),
	.D(\sc/genblk1[4].sci/pos_latch2_out ),
	.Q(SCAN_REG[5]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[4].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[4].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[4].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[4].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [4]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[4].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[5].sci/U6  (
	.A1(\sc/genblk1[5].sci/n1 ),
	.A2(PAR_IN[6]),
	.B1(\sc/genblk1[5].sci/pos_latch1_out ),
	.B2(\sc/genblk1[5].sci/n2 ),
	.Z(\sc/genblk1[5].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[5].sci/U5  (
	.A1(\sc/genblk1[5].sci/n1 ),
	.A2(PAR_IN[6]),
	.B1(\sc/genblk1[5].sci/pos_latch2_out ),
	.B2(\sc/genblk1[5].sci/n2 ),
	.Z(\sc/scan_array [6]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[5].sci/U4  (
	.I(\sc/n1 ),
	.ZN(\sc/genblk1[5].sci/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[5].sci/U3  (
	.I(\sc/genblk1[5].sci/n2 ),
	.ZN(\sc/genblk1[5].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[5].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n5 ),
	.CP(UPDATE),
	.D(\sc/genblk1[5].sci/pos_latch2_out ),
	.Q(SCAN_REG[6]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[5].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[5].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[5].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[5].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [5]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[5].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[6].sci/U6  (
	.A1(\sc/genblk1[6].sci/n1 ),
	.A2(PAR_IN[7]),
	.B1(\sc/genblk1[6].sci/pos_latch1_out ),
	.B2(\sc/genblk1[6].sci/n2 ),
	.Z(\sc/genblk1[6].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[6].sci/U5  (
	.A1(\sc/genblk1[6].sci/n1 ),
	.A2(PAR_IN[7]),
	.B1(\sc/genblk1[6].sci/pos_latch2_out ),
	.B2(\sc/genblk1[6].sci/n2 ),
	.Z(\sc/scan_array [7]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[6].sci/U4  (
	.I(\sc/n1 ),
	.ZN(\sc/genblk1[6].sci/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[6].sci/U3  (
	.I(\sc/genblk1[6].sci/n2 ),
	.ZN(\sc/genblk1[6].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[6].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n5 ),
	.CP(UPDATE),
	.D(\sc/genblk1[6].sci/pos_latch2_out ),
	.Q(SCAN_REG[7]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[6].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[6].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[6].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[6].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [6]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[6].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[7].sci/U5  (
	.A1(\sc/n1 ),
	.A2(PAR_IN[8]),
	.B1(\sc/genblk1[7].sci/pos_latch1_out ),
	.B2(\sc/genblk1[7].sci/n1 ),
	.Z(\sc/genblk1[7].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[7].sci/U4  (
	.A1(\sc/n1 ),
	.A2(PAR_IN[8]),
	.B1(\sc/genblk1[7].sci/pos_latch2_out ),
	.B2(\sc/genblk1[7].sci/n1 ),
	.Z(\sc/scan_array [8]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[7].sci/U3  (
	.I(\sc/n1 ),
	.ZN(\sc/genblk1[7].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[7].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n5 ),
	.CP(UPDATE),
	.D(\sc/genblk1[7].sci/pos_latch2_out ),
	.Q(SCAN_REG[8]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[7].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[7].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[7].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[7].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [7]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[7].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[8].sci/U5  (
	.A1(\sc/n1 ),
	.A2(PAR_IN[9]),
	.B1(\sc/genblk1[8].sci/pos_latch1_out ),
	.B2(\sc/genblk1[8].sci/n1 ),
	.Z(\sc/genblk1[8].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[8].sci/U4  (
	.A1(\sc/n1 ),
	.A2(PAR_IN[9]),
	.B1(\sc/genblk1[8].sci/pos_latch2_out ),
	.B2(\sc/genblk1[8].sci/n1 ),
	.Z(\sc/scan_array [9]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[8].sci/U3  (
	.I(\sc/n1 ),
	.ZN(\sc/genblk1[8].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[8].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n5 ),
	.CP(UPDATE),
	.D(\sc/genblk1[8].sci/pos_latch2_out ),
	.Q(SCAN_REG[9]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[8].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[8].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[8].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[8].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [8]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[8].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[9].sci/U5  (
	.A1(\sc/n1 ),
	.A2(PAR_IN[10]),
	.B1(\sc/genblk1[9].sci/pos_latch1_out ),
	.B2(\sc/genblk1[9].sci/n1 ),
	.Z(\sc/genblk1[9].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[9].sci/U4  (
	.A1(\sc/n1 ),
	.A2(PAR_IN[10]),
	.B1(\sc/genblk1[9].sci/pos_latch2_out ),
	.B2(\sc/genblk1[9].sci/n1 ),
	.Z(\sc/scan_array [10]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[9].sci/U3  (
	.I(\sc/n1 ),
	.ZN(\sc/genblk1[9].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[9].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n5 ),
	.CP(UPDATE),
	.D(\sc/genblk1[9].sci/pos_latch2_out ),
	.Q(SCAN_REG[10]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[9].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[9].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[9].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[9].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [9]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[9].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[10].sci/U5  (
	.A1(\sc/n1 ),
	.A2(PAR_IN[11]),
	.B1(\sc/genblk1[10].sci/pos_latch1_out ),
	.B2(\sc/genblk1[10].sci/n1 ),
	.Z(\sc/genblk1[10].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[10].sci/U4  (
	.A1(\sc/n1 ),
	.A2(PAR_IN[11]),
	.B1(\sc/genblk1[10].sci/pos_latch2_out ),
	.B2(\sc/genblk1[10].sci/n1 ),
	.Z(\sc/scan_array [11]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[10].sci/U3  (
	.I(\sc/n1 ),
	.ZN(\sc/genblk1[10].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[10].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n5 ),
	.CP(UPDATE),
	.D(\sc/genblk1[10].sci/pos_latch2_out ),
	.Q(SCAN_REG[11]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[10].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[10].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[10].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[10].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [10]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[10].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[11].sci/U5  (
	.A1(\sc/n1 ),
	.A2(PAR_IN[12]),
	.B1(\sc/genblk1[11].sci/pos_latch1_out ),
	.B2(\sc/genblk1[11].sci/n1 ),
	.Z(\sc/genblk1[11].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[11].sci/U4  (
	.A1(\sc/n1 ),
	.A2(PAR_IN[12]),
	.B1(\sc/genblk1[11].sci/pos_latch2_out ),
	.B2(\sc/genblk1[11].sci/n1 ),
	.Z(\sc/scan_array [12]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[11].sci/U3  (
	.I(\sc/n1 ),
	.ZN(\sc/genblk1[11].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[11].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n5 ),
	.CP(UPDATE),
	.D(\sc/genblk1[11].sci/pos_latch2_out ),
	.Q(SCAN_REG[12]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[11].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[11].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[11].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[11].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [11]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[11].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[12].sci/U6  (
	.A1(\sc/genblk1[12].sci/n1 ),
	.A2(PAR_IN[13]),
	.B1(\sc/genblk1[12].sci/pos_latch1_out ),
	.B2(\sc/genblk1[12].sci/n2 ),
	.Z(\sc/genblk1[12].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[12].sci/U5  (
	.A1(\sc/genblk1[12].sci/n1 ),
	.A2(PAR_IN[13]),
	.B1(\sc/genblk1[12].sci/pos_latch2_out ),
	.B2(\sc/genblk1[12].sci/n2 ),
	.Z(\sc/scan_array [13]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[12].sci/U4  (
	.I(\sc/n2 ),
	.ZN(\sc/genblk1[12].sci/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[12].sci/U3  (
	.I(\sc/genblk1[12].sci/n2 ),
	.ZN(\sc/genblk1[12].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[12].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n5 ),
	.CP(UPDATE),
	.D(\sc/genblk1[12].sci/pos_latch2_out ),
	.Q(SCAN_REG[13]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[12].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[12].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[12].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[12].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [12]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[12].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[13].sci/U6  (
	.A1(\sc/genblk1[13].sci/n1 ),
	.A2(PAR_IN[14]),
	.B1(\sc/genblk1[13].sci/pos_latch1_out ),
	.B2(\sc/genblk1[13].sci/n2 ),
	.Z(\sc/genblk1[13].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[13].sci/U5  (
	.A1(\sc/genblk1[13].sci/n1 ),
	.A2(PAR_IN[14]),
	.B1(\sc/genblk1[13].sci/pos_latch2_out ),
	.B2(\sc/genblk1[13].sci/n2 ),
	.Z(\sc/scan_array [14]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[13].sci/U4  (
	.I(\sc/n2 ),
	.ZN(\sc/genblk1[13].sci/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[13].sci/U3  (
	.I(\sc/genblk1[13].sci/n2 ),
	.ZN(\sc/genblk1[13].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[13].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n5 ),
	.CP(UPDATE),
	.D(\sc/genblk1[13].sci/pos_latch2_out ),
	.Q(SCAN_REG[14]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[13].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[13].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[13].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[13].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [13]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[13].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[14].sci/U6  (
	.A1(\sc/genblk1[14].sci/n1 ),
	.A2(PAR_IN[15]),
	.B1(\sc/genblk1[14].sci/pos_latch1_out ),
	.B2(\sc/genblk1[14].sci/n2 ),
	.Z(\sc/genblk1[14].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[14].sci/U5  (
	.A1(\sc/genblk1[14].sci/n1 ),
	.A2(PAR_IN[15]),
	.B1(\sc/genblk1[14].sci/pos_latch2_out ),
	.B2(\sc/genblk1[14].sci/n2 ),
	.Z(\sc/scan_array [15]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[14].sci/U4  (
	.I(\sc/n2 ),
	.ZN(\sc/genblk1[14].sci/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[14].sci/U3  (
	.I(\sc/genblk1[14].sci/n2 ),
	.ZN(\sc/genblk1[14].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[14].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n5 ),
	.CP(UPDATE),
	.D(\sc/genblk1[14].sci/pos_latch2_out ),
	.Q(SCAN_REG[15]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[14].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[14].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[14].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[14].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [14]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[14].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[15].sci/U6  (
	.A1(\sc/genblk1[15].sci/n1 ),
	.A2(PAR_IN[16]),
	.B1(\sc/genblk1[15].sci/pos_latch1_out ),
	.B2(\sc/genblk1[15].sci/n2 ),
	.Z(\sc/genblk1[15].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[15].sci/U5  (
	.A1(\sc/genblk1[15].sci/n1 ),
	.A2(PAR_IN[16]),
	.B1(\sc/genblk1[15].sci/pos_latch2_out ),
	.B2(\sc/genblk1[15].sci/n2 ),
	.Z(\sc/scan_array [16]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[15].sci/U4  (
	.I(\sc/n2 ),
	.ZN(\sc/genblk1[15].sci/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[15].sci/U3  (
	.I(\sc/genblk1[15].sci/n2 ),
	.ZN(\sc/genblk1[15].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[15].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n5 ),
	.CP(UPDATE),
	.D(\sc/genblk1[15].sci/pos_latch2_out ),
	.Q(SCAN_REG[16]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[15].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[15].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[15].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[15].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [15]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[15].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[16].sci/U6  (
	.A1(\sc/genblk1[16].sci/n1 ),
	.A2(PAR_IN[17]),
	.B1(\sc/genblk1[16].sci/pos_latch1_out ),
	.B2(\sc/genblk1[16].sci/n2 ),
	.Z(\sc/genblk1[16].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[16].sci/U5  (
	.A1(\sc/genblk1[16].sci/n1 ),
	.A2(PAR_IN[17]),
	.B1(\sc/genblk1[16].sci/pos_latch2_out ),
	.B2(\sc/genblk1[16].sci/n2 ),
	.Z(\sc/scan_array [17]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[16].sci/U4  (
	.I(\sc/n2 ),
	.ZN(\sc/genblk1[16].sci/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[16].sci/U3  (
	.I(\sc/genblk1[16].sci/n2 ),
	.ZN(\sc/genblk1[16].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[16].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n4 ),
	.CP(UPDATE),
	.D(\sc/genblk1[16].sci/pos_latch2_out ),
	.Q(SCAN_REG[17]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[16].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[16].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[16].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[16].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [16]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[16].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[17].sci/U6  (
	.A1(\sc/genblk1[17].sci/n1 ),
	.A2(PAR_IN[18]),
	.B1(\sc/genblk1[17].sci/pos_latch1_out ),
	.B2(\sc/genblk1[17].sci/n2 ),
	.Z(\sc/genblk1[17].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[17].sci/U5  (
	.A1(\sc/genblk1[17].sci/n1 ),
	.A2(PAR_IN[18]),
	.B1(\sc/genblk1[17].sci/pos_latch2_out ),
	.B2(\sc/genblk1[17].sci/n2 ),
	.Z(\sc/scan_array [18]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[17].sci/U4  (
	.I(\sc/n2 ),
	.ZN(\sc/genblk1[17].sci/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[17].sci/U3  (
	.I(\sc/genblk1[17].sci/n2 ),
	.ZN(\sc/genblk1[17].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[17].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n4 ),
	.CP(UPDATE),
	.D(\sc/genblk1[17].sci/pos_latch2_out ),
	.Q(SCAN_REG[18]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[17].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[17].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[17].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[17].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [17]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[17].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[18].sci/U6  (
	.A1(\sc/genblk1[18].sci/n1 ),
	.A2(PAR_IN[19]),
	.B1(\sc/genblk1[18].sci/pos_latch1_out ),
	.B2(\sc/genblk1[18].sci/n2 ),
	.Z(\sc/genblk1[18].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[18].sci/U5  (
	.A1(\sc/genblk1[18].sci/n1 ),
	.A2(PAR_IN[19]),
	.B1(\sc/genblk1[18].sci/pos_latch2_out ),
	.B2(\sc/genblk1[18].sci/n2 ),
	.Z(\sc/scan_array [19]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[18].sci/U4  (
	.I(\sc/n2 ),
	.ZN(\sc/genblk1[18].sci/n2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[18].sci/U3  (
	.I(\sc/genblk1[18].sci/n2 ),
	.ZN(\sc/genblk1[18].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[18].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n4 ),
	.CP(UPDATE),
	.D(\sc/genblk1[18].sci/pos_latch2_out ),
	.Q(SCAN_REG[19]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[18].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[18].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[18].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[18].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [18]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[18].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[19].sci/U5  (
	.A1(\sc/n2 ),
	.A2(PAR_IN[20]),
	.B1(\sc/genblk1[19].sci/pos_latch1_out ),
	.B2(\sc/genblk1[19].sci/n1 ),
	.Z(\sc/genblk1[19].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[19].sci/U4  (
	.A1(\sc/n2 ),
	.A2(PAR_IN[20]),
	.B1(\sc/genblk1[19].sci/pos_latch2_out ),
	.B2(\sc/genblk1[19].sci/n1 ),
	.Z(\sc/scan_array [20]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[19].sci/U3  (
	.I(\sc/n2 ),
	.ZN(\sc/genblk1[19].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[19].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n4 ),
	.CP(UPDATE),
	.D(\sc/genblk1[19].sci/pos_latch2_out ),
	.Q(SCAN_REG[20]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[19].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[19].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[19].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[19].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [19]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[19].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[20].sci/U5  (
	.A1(\sc/n2 ),
	.A2(PAR_IN[21]),
	.B1(\sc/genblk1[20].sci/pos_latch1_out ),
	.B2(\sc/genblk1[20].sci/n1 ),
	.Z(\sc/genblk1[20].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[20].sci/U4  (
	.A1(\sc/n2 ),
	.A2(PAR_IN[21]),
	.B1(\sc/genblk1[20].sci/pos_latch2_out ),
	.B2(\sc/genblk1[20].sci/n1 ),
	.Z(\sc/scan_array [21]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[20].sci/U3  (
	.I(\sc/n2 ),
	.ZN(\sc/genblk1[20].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[20].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n4 ),
	.CP(UPDATE),
	.D(\sc/genblk1[20].sci/pos_latch2_out ),
	.Q(SCAN_REG[21]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[20].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[20].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[20].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[20].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [20]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[20].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[21].sci/U5  (
	.A1(\sc/n2 ),
	.A2(PAR_IN[22]),
	.B1(\sc/genblk1[21].sci/pos_latch1_out ),
	.B2(\sc/genblk1[21].sci/n1 ),
	.Z(\sc/genblk1[21].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[21].sci/U4  (
	.A1(\sc/n2 ),
	.A2(PAR_IN[22]),
	.B1(\sc/genblk1[21].sci/pos_latch2_out ),
	.B2(\sc/genblk1[21].sci/n1 ),
	.Z(\sc/scan_array [22]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[21].sci/U3  (
	.I(\sc/n2 ),
	.ZN(\sc/genblk1[21].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[21].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n4 ),
	.CP(UPDATE),
	.D(\sc/genblk1[21].sci/pos_latch2_out ),
	.Q(SCAN_REG[22]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[21].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[21].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[21].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[21].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [21]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[21].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[22].sci/U5  (
	.A1(\sc/n2 ),
	.A2(PAR_IN[23]),
	.B1(\sc/genblk1[22].sci/pos_latch1_out ),
	.B2(\sc/genblk1[22].sci/n1 ),
	.Z(\sc/genblk1[22].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[22].sci/U4  (
	.A1(\sc/n2 ),
	.A2(PAR_IN[23]),
	.B1(\sc/genblk1[22].sci/pos_latch2_out ),
	.B2(\sc/genblk1[22].sci/n1 ),
	.Z(\sc/scan_array [23]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[22].sci/U3  (
	.I(\sc/n2 ),
	.ZN(\sc/genblk1[22].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[22].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n4 ),
	.CP(UPDATE),
	.D(\sc/genblk1[22].sci/pos_latch2_out ),
	.Q(SCAN_REG[23]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[22].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[22].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[22].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[22].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [22]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[22].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[23].sci/U5  (
	.A1(\sc/n2 ),
	.A2(PAR_IN[24]),
	.B1(\sc/genblk1[23].sci/pos_latch1_out ),
	.B2(\sc/genblk1[23].sci/n1 ),
	.Z(\sc/genblk1[23].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[23].sci/U4  (
	.A1(\sc/n2 ),
	.A2(PAR_IN[24]),
	.B1(\sc/genblk1[23].sci/pos_latch2_out ),
	.B2(\sc/genblk1[23].sci/n1 ),
	.Z(\sc/scan_array [24]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[23].sci/U3  (
	.I(\sc/n2 ),
	.ZN(\sc/genblk1[23].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[23].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n4 ),
	.CP(UPDATE),
	.D(\sc/genblk1[23].sci/pos_latch2_out ),
	.Q(SCAN_REG[24]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[23].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[23].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[23].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[23].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [23]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[23].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[24].sci/U5  (
	.A1(\sc/n3 ),
	.A2(PAR_IN[25]),
	.B1(\sc/genblk1[24].sci/pos_latch1_out ),
	.B2(\sc/genblk1[24].sci/n1 ),
	.Z(\sc/genblk1[24].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[24].sci/U4  (
	.A1(\sc/n3 ),
	.A2(PAR_IN[25]),
	.B1(\sc/genblk1[24].sci/pos_latch2_out ),
	.B2(\sc/genblk1[24].sci/n1 ),
	.Z(\sc/scan_array [25]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[24].sci/U3  (
	.I(\sc/n3 ),
	.ZN(\sc/genblk1[24].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[24].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n4 ),
	.CP(UPDATE),
	.D(\sc/genblk1[24].sci/pos_latch2_out ),
	.Q(SCAN_REG[25]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[24].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[24].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[24].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[24].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [24]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[24].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[25].sci/U5  (
	.A1(\sc/n3 ),
	.A2(PAR_IN[26]),
	.B1(\sc/genblk1[25].sci/pos_latch1_out ),
	.B2(\sc/genblk1[25].sci/n1 ),
	.Z(\sc/genblk1[25].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[25].sci/U4  (
	.A1(\sc/n3 ),
	.A2(PAR_IN[26]),
	.B1(\sc/genblk1[25].sci/pos_latch2_out ),
	.B2(\sc/genblk1[25].sci/n1 ),
	.Z(\sc/scan_array [26]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[25].sci/U3  (
	.I(\sc/n3 ),
	.ZN(\sc/genblk1[25].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[25].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n4 ),
	.CP(UPDATE),
	.D(\sc/genblk1[25].sci/pos_latch2_out ),
	.Q(SCAN_REG[26]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[25].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[25].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[25].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[25].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [25]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[25].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[26].sci/U5  (
	.A1(\sc/n3 ),
	.A2(PAR_IN[27]),
	.B1(\sc/genblk1[26].sci/pos_latch1_out ),
	.B2(\sc/genblk1[26].sci/n1 ),
	.Z(\sc/genblk1[26].sci/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/genblk1[26].sci/U4  (
	.A1(\sc/n3 ),
	.A2(PAR_IN[27]),
	.B1(\sc/genblk1[26].sci/pos_latch2_out ),
	.B2(\sc/genblk1[26].sci/n1 ),
	.Z(\sc/scan_array [27]), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/genblk1[26].sci/U3  (
	.I(\sc/n3 ),
	.ZN(\sc/genblk1[26].sci/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/genblk1[26].sci/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n4 ),
	.CP(UPDATE),
	.D(\sc/genblk1[26].sci/pos_latch2_out ),
	.Q(SCAN_REG[27]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[26].sci/pos_latch2_out_reg  (
	.D(\sc/genblk1[26].sci/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/genblk1[26].sci/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/genblk1[26].sci/pos_latch1_out_reg  (
	.D(\sc/scan_array [26]),
	.E(SC_CLK1),
	.Q(\sc/genblk1[26].sci/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/scN/U5  (
	.A1(\sc/n3 ),
	.A2(PAR_IN[28]),
	.B1(\sc/scN/pos_latch1_out ),
	.B2(\sc/scN/n1 ),
	.Z(\sc/scN/pos_latch2_in ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D0 \sc/scN/U4  (
	.A1(\sc/n3 ),
	.A2(PAR_IN[28]),
	.B1(\sc/scN/pos_latch2_out ),
	.B2(\sc/scN/n1 ),
	.Z(SCAN_OUT), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 \sc/scN/U3  (
	.I(\sc/n3 ),
	.ZN(\sc/scN/n1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFCNQD1 \sc/scN/SCAN_OUT_UPDT_2_reg  (
	.CDN(\sc/n4 ),
	.CP(UPDATE),
	.D(\sc/scN/pos_latch2_out ),
	.Q(SCAN_REG[28]), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/scN/pos_latch2_out_reg  (
	.D(\sc/scN/pos_latch2_in ),
	.E(SC_CLK2),
	.Q(\sc/scN/pos_latch2_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   LHQD1 \sc/scN/pos_latch1_out_reg  (
	.D(\sc/scan_array [27]),
	.E(SC_CLK1),
	.Q(\sc/scN/pos_latch1_out ), 
	.VSS(VSS), 
	.VDD(VDD));
endmodule

